-- ============================================================
-- RPT_HSF10_RESPREDICT_STATISTICS
-- forecast/预测均值 (按年度) (weekly)
-- EPS / EPS增速 / PE 多年度均值
-- 样本行数: 100, 字段数: 15
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_hsf10_respredict_statistics (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  YEAR INTEGER NOT NULL,
  YEAR_MARK VARCHAR NOT NULL,
  EPS DOUBLE NOT NULL,
  EPS_RATIO DOUBLE NOT NULL,
  PE DOUBLE,
  ROE DOUBLE,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  PARENT_NETPROFIT_RATIO DOUBLE NOT NULL,
  TOTAL_OPERATE_INCOME DOUBLE,
  TOTAL_OPERATE_INCOME_RATIO DOUBLE,
  OPERATE_PROFIT DOUBLE NOT NULL,
  RANK INTEGER NOT NULL,
  PRIMARY KEY (SECUCODE)
);
