-- ============================================================
-- RPT_HSF10_RES_ORGRATING
-- forecast/评级统计 (weekly)
-- 综合评级 + 各档家数
-- 样本行数: 100, 字段数: 17
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_hsf10_res_orgrating (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  TRADE_MARKET_CODE VARCHAR NOT NULL,
  DATE_TYPE_CODE INTEGER NOT NULL,
  DATE_TYPE VARCHAR NOT NULL,
  COMPRE_RATING_NUM DOUBLE,
  COMPRE_RATING VARCHAR,
  RATING_ORG_NUM INTEGER,
  RATING_BUY_NUM INTEGER,
  RATING_ADD_NUM INTEGER,
  RATING_NEUTRAL_NUM INTEGER,
  -- RATING_REDUCE_NUM: 全部样本为空, 默认 TEXT
  RATING_REDUCE_NUM VARCHAR,
  -- RATING_SALE_NUM: 全部样本为空, 默认 TEXT
  RATING_SALE_NUM VARCHAR,
  SECURITY_CODE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE)
);
