-- ============================================================
-- RPT_PCF10_DIVIDENDNEW_RANK
-- dividend/分红排名 (quarterly)
-- 样本行数: 100, 字段数: 17
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_dividendnew_rank (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  INDUSTRY_CODE VARCHAR NOT NULL,
  INDUSTRY_NAME VARCHAR NOT NULL,
  INDUSTRY_NUM INTEGER NOT NULL,
  DATA_TYPE VARCHAR NOT NULL,
  CORRE_SECUCODE VARCHAR NOT NULL,
  CORRE_SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECURITY_NAME VARCHAR NOT NULL,
  DIVIDEND_RATIO DOUBLE NOT NULL,
  DIVIDEND_RANK INTEGER NOT NULL,
  IS_SELF VARCHAR NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  ASSIGN_TYPE VARCHAR NOT NULL,
  REPORT VARCHAR,
  NEW_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SECUCODE, DATA_TYPE)
);
