-- ============================================================
-- RPT_F10_DIVIDEND_SEO
-- dividend/融资明细 (增发/配股) (event)
-- 样本行数: 100, 字段数: 14
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividend_seo (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  ISSUE_NUM INTEGER NOT NULL,
  NET_RAISE_FUNDS DOUBLE,
  ISSUE_PRICE DOUBLE NOT NULL,
  LISTING_STATE VARCHAR NOT NULL,
  ISSUE_WAY_EXPLAIN VARCHAR NOT NULL,
  REG_DATE TIMESTAMP,
  LISTING_DATE TIMESTAMP,
  RECEIVE_DATE TIMESTAMP,
  SEO_PURPOSE VARCHAR,
  TOTAL_RAISE_FUNDS DOUBLE,
  PRIMARY KEY (SECUCODE, NOTICE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_dividend_seo_notice_date ON rpt_f10_dividend_seo(NOTICE_DATE);
