-- ============================================================
-- RPT_PCF10_INDUSTRY_DBFX
-- peer/杜邦分析比较 (quarterly)
-- 样本行数: 100, 字段数: 23
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_industry_dbfx (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECUCODE VARCHAR NOT NULL,
  CORRE_SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECURITY_NAME VARCHAR NOT NULL,
  ROEPJ_L3 DOUBLE NOT NULL,
  ROEPJ_L2 DOUBLE NOT NULL,
  ROEPJ_L1 DOUBLE NOT NULL,
  ROE_AVG DOUBLE NOT NULL,
  XSJLL_L3 DOUBLE NOT NULL,
  XSJLL_L2 DOUBLE NOT NULL,
  XSJLL_L1 DOUBLE NOT NULL,
  XSJLL_AVG DOUBLE NOT NULL,
  TOAZZL_L3 DOUBLE NOT NULL,
  TOAZZL_L2 DOUBLE NOT NULL,
  TOAZZL_L1 DOUBLE NOT NULL,
  TOAZZL_AVG DOUBLE NOT NULL,
  QYCS_L3 DOUBLE NOT NULL,
  QYCS_L2 DOUBLE NOT NULL,
  QYCS_L1 DOUBLE NOT NULL,
  QYCS_AVG DOUBLE NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  TOTAL_COUNT INTEGER NOT NULL,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_pcf10_industry_dbfx_report_date ON rpt_pcf10_industry_dbfx(REPORT_DATE);
