-- ============================================================
-- RPT_F10_FINANCE_GCASHFLOW
-- financial/现金流量表 (累计) (quarterly)
-- 样本行数: 98, 字段数: 254
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_gcashflow (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  SALES_SERVICES DOUBLE,
  DEPOSIT_INTERBANK_ADD DOUBLE,
  -- LOAN_PBC_ADD: 全部样本为空, 默认 TEXT
  LOAN_PBC_ADD VARCHAR,
  -- OFI_BF_ADD: 全部样本为空, 默认 TEXT
  OFI_BF_ADD VARCHAR,
  -- RECEIVE_ORIGIC_PREMIUM: 全部样本为空, 默认 TEXT
  RECEIVE_ORIGIC_PREMIUM VARCHAR,
  -- RECEIVE_REINSURE_NET: 全部样本为空, 默认 TEXT
  RECEIVE_REINSURE_NET VARCHAR,
  -- INSURED_INVEST_ADD: 全部样本为空, 默认 TEXT
  INSURED_INVEST_ADD VARCHAR,
  -- DISPOSAL_TFA_ADD: 全部样本为空, 默认 TEXT
  DISPOSAL_TFA_ADD VARCHAR,
  RECEIVE_INTEREST_COMMISSION DOUBLE,
  -- BORROW_FUND_ADD: 全部样本为空, 默认 TEXT
  BORROW_FUND_ADD VARCHAR,
  LOAN_ADVANCE_REDUCE INTEGER,
  -- REPO_BUSINESS_ADD: 全部样本为空, 默认 TEXT
  REPO_BUSINESS_ADD VARCHAR,
  RECEIVE_TAX_REFUND DOUBLE,
  RECEIVE_OTHER_OPERATE DOUBLE,
  OPERATE_INFLOW_OTHER INTEGER,
  OPERATE_INFLOW_BALANCE INTEGER,
  TOTAL_OPERATE_INFLOW DOUBLE,
  BUY_SERVICES DOUBLE,
  LOAN_ADVANCE_ADD DOUBLE,
  PBC_INTERBANK_ADD DOUBLE,
  -- PAY_ORIGIC_COMPENSATE: 全部样本为空, 默认 TEXT
  PAY_ORIGIC_COMPENSATE VARCHAR,
  PAY_INTEREST_COMMISSION DOUBLE,
  -- PAY_POLICY_BONUS: 全部样本为空, 默认 TEXT
  PAY_POLICY_BONUS VARCHAR,
  PAY_STAFF_CASH DOUBLE,
  PAY_ALL_TAX DOUBLE,
  PAY_OTHER_OPERATE DOUBLE,
  OPERATE_OUTFLOW_OTHER BIGINT,
  OPERATE_OUTFLOW_BALANCE DOUBLE,
  TOTAL_OPERATE_OUTFLOW DOUBLE,
  OPERATE_NETCASH_OTHER INTEGER,
  OPERATE_NETCASH_BALANCE DOUBLE,
  NETCASH_OPERATE DOUBLE NOT NULL,
  WITHDRAW_INVEST DOUBLE,
  RECEIVE_INVEST_INCOME DOUBLE,
  DISPOSAL_LONG_ASSET DOUBLE,
  -- DISPOSAL_SUBSIDIARY_OTHER: 全部样本为空, 默认 TEXT
  DISPOSAL_SUBSIDIARY_OTHER VARCHAR,
  -- REDUCE_PLEDGE_TIMEDEPOSITS: 全部样本为空, 默认 TEXT
  REDUCE_PLEDGE_TIMEDEPOSITS VARCHAR,
  RECEIVE_OTHER_INVEST DOUBLE,
  INVEST_INFLOW_OTHER INTEGER,
  INVEST_INFLOW_BALANCE INTEGER,
  TOTAL_INVEST_INFLOW DOUBLE,
  CONSTRUCT_LONG_ASSET DOUBLE,
  INVEST_PAY_CASH DOUBLE,
  -- PLEDGE_LOAN_ADD: 全部样本为空, 默认 TEXT
  PLEDGE_LOAN_ADD VARCHAR,
  -- OBTAIN_SUBSIDIARY_OTHER: 全部样本为空, 默认 TEXT
  OBTAIN_SUBSIDIARY_OTHER VARCHAR,
  -- ADD_PLEDGE_TIMEDEPOSITS: 全部样本为空, 默认 TEXT
  ADD_PLEDGE_TIMEDEPOSITS VARCHAR,
  PAY_OTHER_INVEST DOUBLE,
  INVEST_OUTFLOW_OTHER INTEGER,
  INVEST_OUTFLOW_BALANCE INTEGER,
  TOTAL_INVEST_OUTFLOW DOUBLE,
  INVEST_NETCASH_OTHER INTEGER,
  INVEST_NETCASH_BALANCE DOUBLE,
  NETCASH_INVEST DOUBLE NOT NULL,
  ACCEPT_INVEST_CASH DOUBLE,
  SUBSIDIARY_ACCEPT_INVEST INTEGER,
  RECEIVE_LOAN_CASH INTEGER,
  -- ISSUE_BOND: 全部样本为空, 默认 TEXT
  ISSUE_BOND VARCHAR,
  RECEIVE_OTHER_FINANCE DOUBLE,
  FINANCE_INFLOW_OTHER INTEGER,
  FINANCE_INFLOW_BALANCE INTEGER,
  TOTAL_FINANCE_INFLOW DOUBLE,
  PAY_DEBT_CASH INTEGER,
  ASSIGN_DIVIDEND_PORFIT DOUBLE,
  SUBSIDIARY_PAY_DIVIDEND DOUBLE,
  -- BUY_SUBSIDIARY_EQUITY: 全部样本为空, 默认 TEXT
  BUY_SUBSIDIARY_EQUITY VARCHAR,
  PAY_OTHER_FINANCE DOUBLE,
  SUBSIDIARY_REDUCE_CASH INTEGER,
  FINANCE_OUTFLOW_OTHER INTEGER,
  FINANCE_OUTFLOW_BALANCE INTEGER,
  TOTAL_FINANCE_OUTFLOW DOUBLE,
  FINANCE_NETCASH_OTHER INTEGER,
  FINANCE_NETCASH_BALANCE DOUBLE,
  NETCASH_FINANCE DOUBLE,
  RATE_CHANGE_EFFECT DOUBLE,
  CCE_ADD_OTHER INTEGER,
  CCE_ADD_BALANCE INTEGER,
  CCE_ADD DOUBLE NOT NULL,
  BEGIN_CCE DOUBLE,
  -- END_CCE_OTHER: 全部样本为空, 默认 TEXT
  END_CCE_OTHER VARCHAR,
  END_CCE_BALANCE INTEGER,
  END_CCE DOUBLE,
  NETPROFIT DOUBLE,
  ASSET_IMPAIRMENT DOUBLE,
  FA_IR_DEPR DOUBLE,
  OILGAS_BIOLOGY_DEPR DOUBLE,
  -- IR_DEPR: 全部样本为空, 默认 TEXT
  IR_DEPR VARCHAR,
  IA_AMORTIZE DOUBLE,
  LPE_AMORTIZE DOUBLE,
  -- DEFER_INCOME_AMORTIZE: 全部样本为空, 默认 TEXT
  DEFER_INCOME_AMORTIZE VARCHAR,
  PREPAID_EXPENSE_REDUCE DOUBLE,
  ACCRUED_EXPENSE_ADD DOUBLE,
  DISPOSAL_LONGASSET_LOSS DOUBLE,
  FA_SCRAP_LOSS DOUBLE,
  FAIRVALUE_CHANGE_LOSS DOUBLE,
  FINANCE_EXPENSE DOUBLE,
  INVEST_LOSS DOUBLE,
  DEFER_TAX DOUBLE,
  DT_ASSET_REDUCE DOUBLE,
  DT_LIAB_ADD DOUBLE,
  -- PREDICT_LIAB_ADD: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_ADD VARCHAR,
  INVENTORY_REDUCE DOUBLE,
  OPERATE_RECE_REDUCE DOUBLE,
  OPERATE_PAYABLE_ADD DOUBLE,
  OTHER DOUBLE,
  OPERATE_NETCASH_OTHERNOTE INTEGER,
  OPERATE_NETCASH_BALANCENOTE DOUBLE,
  NETCASH_OPERATENOTE DOUBLE,
  -- DEBT_TRANSFER_CAPITAL: 全部样本为空, 默认 TEXT
  DEBT_TRANSFER_CAPITAL VARCHAR,
  -- CONVERT_BOND_1YEAR: 全部样本为空, 默认 TEXT
  CONVERT_BOND_1YEAR VARCHAR,
  -- FINLEASE_OBTAIN_FA: 全部样本为空, 默认 TEXT
  FINLEASE_OBTAIN_FA VARCHAR,
  UNINVOLVE_INVESTFIN_OTHER INTEGER,
  END_CASH DOUBLE,
  BEGIN_CASH DOUBLE,
  END_CASH_EQUIVALENTS BIGINT,
  BEGIN_CASH_EQUIVALENTS BIGINT,
  -- CCE_ADD_OTHERNOTE: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHERNOTE VARCHAR,
  CCE_ADD_BALANCENOTE DOUBLE,
  CCE_ADDNOTE DOUBLE,
  SALES_SERVICES_YOY DOUBLE,
  DEPOSIT_INTERBANK_ADD_YOY DOUBLE,
  -- LOAN_PBC_ADD_YOY: 全部样本为空, 默认 TEXT
  LOAN_PBC_ADD_YOY VARCHAR,
  -- OFI_BF_ADD_YOY: 全部样本为空, 默认 TEXT
  OFI_BF_ADD_YOY VARCHAR,
  -- RECEIVE_ORIGIC_PREMIUM_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_ORIGIC_PREMIUM_YOY VARCHAR,
  -- RECEIVE_REINSURE_NET_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_REINSURE_NET_YOY VARCHAR,
  -- INSURED_INVEST_ADD_YOY: 全部样本为空, 默认 TEXT
  INSURED_INVEST_ADD_YOY VARCHAR,
  -- DISPOSAL_TFA_ADD_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_TFA_ADD_YOY VARCHAR,
  RECEIVE_INTEREST_COMMISSION_YOY DOUBLE,
  -- BORROW_FUND_ADD_YOY: 全部样本为空, 默认 TEXT
  BORROW_FUND_ADD_YOY VARCHAR,
  -- LOAN_ADVANCE_REDUCE_YOY: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_REDUCE_YOY VARCHAR,
  -- REPO_BUSINESS_ADD_YOY: 全部样本为空, 默认 TEXT
  REPO_BUSINESS_ADD_YOY VARCHAR,
  RECEIVE_TAX_REFUND_YOY DOUBLE,
  RECEIVE_OTHER_OPERATE_YOY DOUBLE,
  -- OPERATE_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_OTHER_YOY VARCHAR,
  -- OPERATE_INFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_BALANCE_YOY VARCHAR,
  TOTAL_OPERATE_INFLOW_YOY DOUBLE,
  BUY_SERVICES_YOY DOUBLE,
  LOAN_ADVANCE_ADD_YOY DOUBLE,
  PBC_INTERBANK_ADD_YOY DOUBLE,
  -- PAY_ORIGIC_COMPENSATE_YOY: 全部样本为空, 默认 TEXT
  PAY_ORIGIC_COMPENSATE_YOY VARCHAR,
  PAY_INTEREST_COMMISSION_YOY DOUBLE,
  -- PAY_POLICY_BONUS_YOY: 全部样本为空, 默认 TEXT
  PAY_POLICY_BONUS_YOY VARCHAR,
  PAY_STAFF_CASH_YOY DOUBLE,
  PAY_ALL_TAX_YOY DOUBLE,
  PAY_OTHER_OPERATE_YOY DOUBLE,
  OPERATE_OUTFLOW_OTHER_YOY DOUBLE,
  OPERATE_OUTFLOW_BALANCE_YOY INTEGER,
  TOTAL_OPERATE_OUTFLOW_YOY DOUBLE,
  -- OPERATE_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHER_YOY VARCHAR,
  OPERATE_NETCASH_BALANCE_YOY INTEGER,
  NETCASH_OPERATE_YOY DOUBLE,
  WITHDRAW_INVEST_YOY DOUBLE,
  RECEIVE_INVEST_INCOME_YOY DOUBLE,
  DISPOSAL_LONG_ASSET_YOY DOUBLE,
  -- DISPOSAL_SUBSIDIARY_OTHER_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_SUBSIDIARY_OTHER_YOY VARCHAR,
  -- REDUCE_PLEDGE_TIMEDEPOSITS_YOY: 全部样本为空, 默认 TEXT
  REDUCE_PLEDGE_TIMEDEPOSITS_YOY VARCHAR,
  RECEIVE_OTHER_INVEST_YOY DOUBLE,
  -- INVEST_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_OTHER_YOY VARCHAR,
  -- INVEST_INFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_BALANCE_YOY VARCHAR,
  TOTAL_INVEST_INFLOW_YOY DOUBLE,
  CONSTRUCT_LONG_ASSET_YOY DOUBLE,
  INVEST_PAY_CASH_YOY DOUBLE,
  -- PLEDGE_LOAN_ADD_YOY: 全部样本为空, 默认 TEXT
  PLEDGE_LOAN_ADD_YOY VARCHAR,
  -- OBTAIN_SUBSIDIARY_OTHER_YOY: 全部样本为空, 默认 TEXT
  OBTAIN_SUBSIDIARY_OTHER_YOY VARCHAR,
  -- ADD_PLEDGE_TIMEDEPOSITS_YOY: 全部样本为空, 默认 TEXT
  ADD_PLEDGE_TIMEDEPOSITS_YOY VARCHAR,
  PAY_OTHER_INVEST_YOY DOUBLE,
  -- INVEST_OUTFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_OTHER_YOY VARCHAR,
  -- INVEST_OUTFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_BALANCE_YOY VARCHAR,
  TOTAL_INVEST_OUTFLOW_YOY DOUBLE,
  -- INVEST_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_OTHER_YOY VARCHAR,
  INVEST_NETCASH_BALANCE_YOY INTEGER,
  NETCASH_INVEST_YOY DOUBLE,
  ACCEPT_INVEST_CASH_YOY DOUBLE,
  SUBSIDIARY_ACCEPT_INVEST_YOY DOUBLE,
  -- RECEIVE_LOAN_CASH_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_LOAN_CASH_YOY VARCHAR,
  -- ISSUE_BOND_YOY: 全部样本为空, 默认 TEXT
  ISSUE_BOND_YOY VARCHAR,
  RECEIVE_OTHER_FINANCE_YOY DOUBLE,
  -- FINANCE_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_OTHER_YOY VARCHAR,
  FINANCE_INFLOW_BALANCE_YOY INTEGER,
  TOTAL_FINANCE_INFLOW_YOY DOUBLE,
  PAY_DEBT_CASH_YOY DOUBLE,
  ASSIGN_DIVIDEND_PORFIT_YOY DOUBLE,
  SUBSIDIARY_PAY_DIVIDEND_YOY DOUBLE,
  -- BUY_SUBSIDIARY_EQUITY_YOY: 全部样本为空, 默认 TEXT
  BUY_SUBSIDIARY_EQUITY_YOY VARCHAR,
  PAY_OTHER_FINANCE_YOY DOUBLE,
  -- SUBSIDIARY_REDUCE_CASH_YOY: 全部样本为空, 默认 TEXT
  SUBSIDIARY_REDUCE_CASH_YOY VARCHAR,
  -- FINANCE_OUTFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_OTHER_YOY VARCHAR,
  -- FINANCE_OUTFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_BALANCE_YOY VARCHAR,
  TOTAL_FINANCE_OUTFLOW_YOY DOUBLE,
  -- FINANCE_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_OTHER_YOY VARCHAR,
  FINANCE_NETCASH_BALANCE_YOY INTEGER,
  NETCASH_FINANCE_YOY DOUBLE,
  RATE_CHANGE_EFFECT_YOY DOUBLE,
  -- CCE_ADD_OTHER_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHER_YOY VARCHAR,
  -- CCE_ADD_BALANCE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCE_YOY VARCHAR,
  CCE_ADD_YOY DOUBLE,
  BEGIN_CCE_YOY DOUBLE,
  -- END_CCE_OTHER_YOY: 全部样本为空, 默认 TEXT
  END_CCE_OTHER_YOY VARCHAR,
  -- END_CCE_BALANCE_YOY: 全部样本为空, 默认 TEXT
  END_CCE_BALANCE_YOY VARCHAR,
  END_CCE_YOY DOUBLE,
  NETPROFIT_YOY DOUBLE,
  ASSET_IMPAIRMENT_YOY DOUBLE,
  FA_IR_DEPR_YOY DOUBLE,
  OILGAS_BIOLOGY_DEPR_YOY DOUBLE,
  -- IR_DEPR_YOY: 全部样本为空, 默认 TEXT
  IR_DEPR_YOY VARCHAR,
  IA_AMORTIZE_YOY DOUBLE,
  LPE_AMORTIZE_YOY DOUBLE,
  -- DEFER_INCOME_AMORTIZE_YOY: 全部样本为空, 默认 TEXT
  DEFER_INCOME_AMORTIZE_YOY VARCHAR,
  PREPAID_EXPENSE_REDUCE_YOY DOUBLE,
  ACCRUED_EXPENSE_ADD_YOY DOUBLE,
  DISPOSAL_LONGASSET_LOSS_YOY DOUBLE,
  FA_SCRAP_LOSS_YOY DOUBLE,
  FAIRVALUE_CHANGE_LOSS_YOY DOUBLE,
  FINANCE_EXPENSE_YOY DOUBLE,
  INVEST_LOSS_YOY DOUBLE,
  DEFER_TAX_YOY DOUBLE,
  DT_ASSET_REDUCE_YOY DOUBLE,
  DT_LIAB_ADD_YOY DOUBLE,
  -- PREDICT_LIAB_ADD_YOY: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_ADD_YOY VARCHAR,
  INVENTORY_REDUCE_YOY DOUBLE,
  OPERATE_RECE_REDUCE_YOY DOUBLE,
  OPERATE_PAYABLE_ADD_YOY DOUBLE,
  OTHER_YOY DOUBLE,
  -- OPERATE_NETCASH_OTHERNOTE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHERNOTE_YOY VARCHAR,
  OPERATE_NETCASH_BALANCENOTE_YOY DOUBLE,
  NETCASH_OPERATENOTE_YOY DOUBLE,
  -- DEBT_TRANSFER_CAPITAL_YOY: 全部样本为空, 默认 TEXT
  DEBT_TRANSFER_CAPITAL_YOY VARCHAR,
  -- CONVERT_BOND_1YEAR_YOY: 全部样本为空, 默认 TEXT
  CONVERT_BOND_1YEAR_YOY VARCHAR,
  -- FINLEASE_OBTAIN_FA_YOY: 全部样本为空, 默认 TEXT
  FINLEASE_OBTAIN_FA_YOY VARCHAR,
  -- UNINVOLVE_INVESTFIN_OTHER_YOY: 全部样本为空, 默认 TEXT
  UNINVOLVE_INVESTFIN_OTHER_YOY VARCHAR,
  END_CASH_YOY DOUBLE,
  BEGIN_CASH_YOY DOUBLE,
  END_CASH_EQUIVALENTS_YOY DOUBLE,
  BEGIN_CASH_EQUIVALENTS_YOY DOUBLE,
  -- CCE_ADD_OTHERNOTE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHERNOTE_YOY VARCHAR,
  CCE_ADD_BALANCENOTE_YOY INTEGER,
  CCE_ADDNOTE_YOY DOUBLE,
  OPINION_TYPE VARCHAR,
  -- OSOPINION_TYPE: 全部样本为空, 默认 TEXT
  OSOPINION_TYPE VARCHAR,
  MINORITY_INTEREST DOUBLE,
  MINORITY_INTEREST_YOY DOUBLE,
  USERIGHT_ASSET_AMORTIZE DOUBLE,
  USERIGHT_ASSET_AMORTIZE_YOY DOUBLE,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_gcashflow_report_date ON rpt_f10_finance_gcashflow(REPORT_DATE);
