-- ============================================================
-- RPT_F10_CORETHEME_BOARDTYPE
-- themes/概念题材 (static)
-- 样本行数: 100, 字段数: 13
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_coretheme_boardtype (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  BOARD_CODE VARCHAR NOT NULL,
  BOARD_NAME VARCHAR NOT NULL,
  SELECTED_BOARD_REASON VARCHAR,
  IS_PRECISE VARCHAR NOT NULL,
  BOARD_RANK INTEGER NOT NULL,
  -- BOARD_YIELD: 全部样本为空, 默认 TEXT
  BOARD_YIELD VARCHAR,
  NEW_BOARD_CODE VARCHAR NOT NULL,
  DERIVE_BOARD_CODE VARCHAR NOT NULL,
  -- BOARD_TYPE: 全部样本为空, 默认 TEXT
  BOARD_TYPE VARCHAR,
  -- BOARD_LEVEL: 全部样本为空, 默认 TEXT
  BOARD_LEVEL VARCHAR,
  PRIMARY KEY (SECUCODE, BOARD_CODE)
);
