-- ============================================================
-- RPT_HSF10_RES_ORGPREDICT
-- forecast/机构预测 (按机构) (weekly)
-- 样本行数: 100, 字段数: 22
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_hsf10_res_orgpredict (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  PUBLISH_DATE TIMESTAMP NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_NAME_ABBR VARCHAR NOT NULL,
  YEAR1 INTEGER NOT NULL,
  YEAR_MARK1 VARCHAR NOT NULL,
  EPS1 DOUBLE NOT NULL,
  PE1 DOUBLE NOT NULL,
  YEAR2 INTEGER,
  YEAR_MARK2 VARCHAR,
  EPS2 DOUBLE,
  PE2 DOUBLE,
  YEAR3 INTEGER,
  YEAR_MARK3 VARCHAR,
  EPS3 DOUBLE,
  PE3 DOUBLE,
  YEAR4 INTEGER,
  YEAR_MARK4 VARCHAR,
  EPS4 DOUBLE,
  PE4 DOUBLE,
  PRIMARY KEY (SECUCODE, ORG_CODE)
);
