-- ============================================================
-- RPT_PCF10_MARKETPER
-- peer/市场表现 (daily)
-- 样本行数: 100, 字段数: 12
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_marketper (
  SECUCODE VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  CHANGERATE INTEGER NOT NULL,
  HS300_CHANGERATE INTEGER NOT NULL,
  TIME_TYPE INTEGER NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  HS300_NAME VARCHAR NOT NULL,
  HS300_SECUCODE VARCHAR NOT NULL,
  BOARD_CHANGERATE INTEGER NOT NULL,
  BOARD_NAME VARCHAR NOT NULL,
  BOARD_CODE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_pcf10_marketper_trade_date ON rpt_pcf10_marketper(TRADE_DATE);
