-- ============================================================
-- RPT_F10_FINANCE_GINCOME
-- financial/利润表 (累计) (quarterly)
-- 样本行数: 100, 字段数: 203
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_gincome (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  TOTAL_OPERATE_INCOME DOUBLE NOT NULL,
  TOTAL_OPERATE_INCOME_YOY DOUBLE,
  OPERATE_INCOME DOUBLE NOT NULL,
  OPERATE_INCOME_YOY DOUBLE,
  INTEREST_INCOME DOUBLE,
  INTEREST_INCOME_YOY DOUBLE,
  -- EARNED_PREMIUM: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM VARCHAR,
  -- EARNED_PREMIUM_YOY: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM_YOY VARCHAR,
  FEE_COMMISSION_INCOME DOUBLE,
  FEE_COMMISSION_INCOME_YOY DOUBLE,
  OTHER_BUSINESS_INCOME DOUBLE,
  -- OTHER_BUSINESS_INCOME_YOY: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_INCOME_YOY VARCHAR,
  -- TOI_OTHER: 全部样本为空, 默认 TEXT
  TOI_OTHER VARCHAR,
  -- TOI_OTHER_YOY: 全部样本为空, 默认 TEXT
  TOI_OTHER_YOY VARCHAR,
  TOTAL_OPERATE_COST DOUBLE NOT NULL,
  TOTAL_OPERATE_COST_YOY DOUBLE,
  OPERATE_COST DOUBLE NOT NULL,
  OPERATE_COST_YOY DOUBLE,
  INTEREST_EXPENSE DOUBLE,
  INTEREST_EXPENSE_YOY DOUBLE,
  FEE_COMMISSION_EXPENSE DOUBLE,
  FEE_COMMISSION_EXPENSE_YOY DOUBLE,
  RESEARCH_EXPENSE DOUBLE,
  RESEARCH_EXPENSE_YOY DOUBLE,
  -- SURRENDER_VALUE: 全部样本为空, 默认 TEXT
  SURRENDER_VALUE VARCHAR,
  -- SURRENDER_VALUE_YOY: 全部样本为空, 默认 TEXT
  SURRENDER_VALUE_YOY VARCHAR,
  -- NET_COMPENSATE_EXPENSE: 全部样本为空, 默认 TEXT
  NET_COMPENSATE_EXPENSE VARCHAR,
  -- NET_COMPENSATE_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  NET_COMPENSATE_EXPENSE_YOY VARCHAR,
  NET_CONTRACT_RESERVE INTEGER,
  -- NET_CONTRACT_RESERVE_YOY: 全部样本为空, 默认 TEXT
  NET_CONTRACT_RESERVE_YOY VARCHAR,
  -- POLICY_BONUS_EXPENSE: 全部样本为空, 默认 TEXT
  POLICY_BONUS_EXPENSE VARCHAR,
  -- POLICY_BONUS_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  POLICY_BONUS_EXPENSE_YOY VARCHAR,
  -- REINSURE_EXPENSE: 全部样本为空, 默认 TEXT
  REINSURE_EXPENSE VARCHAR,
  -- REINSURE_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  REINSURE_EXPENSE_YOY VARCHAR,
  -- OTHER_BUSINESS_COST: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_COST VARCHAR,
  -- OTHER_BUSINESS_COST_YOY: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_COST_YOY VARCHAR,
  OPERATE_TAX_ADD DOUBLE NOT NULL,
  OPERATE_TAX_ADD_YOY DOUBLE,
  SALE_EXPENSE DOUBLE NOT NULL,
  SALE_EXPENSE_YOY DOUBLE,
  MANAGE_EXPENSE DOUBLE NOT NULL,
  MANAGE_EXPENSE_YOY DOUBLE,
  -- ME_RESEARCH_EXPENSE: 全部样本为空, 默认 TEXT
  ME_RESEARCH_EXPENSE VARCHAR,
  -- ME_RESEARCH_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  ME_RESEARCH_EXPENSE_YOY VARCHAR,
  FINANCE_EXPENSE DOUBLE NOT NULL,
  FINANCE_EXPENSE_YOY DOUBLE,
  FE_INTEREST_EXPENSE DOUBLE,
  FE_INTEREST_EXPENSE_YOY DOUBLE,
  FE_INTEREST_INCOME DOUBLE,
  FE_INTEREST_INCOME_YOY DOUBLE,
  ASSET_IMPAIRMENT_LOSS DOUBLE,
  ASSET_IMPAIRMENT_LOSS_YOY DOUBLE,
  -- CREDIT_IMPAIRMENT_LOSS: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_LOSS VARCHAR,
  -- CREDIT_IMPAIRMENT_LOSS_YOY: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_LOSS_YOY VARCHAR,
  TOC_OTHER INTEGER,
  -- TOC_OTHER_YOY: 全部样本为空, 默认 TEXT
  TOC_OTHER_YOY VARCHAR,
  FAIRVALUE_CHANGE_INCOME DOUBLE,
  FAIRVALUE_CHANGE_INCOME_YOY DOUBLE,
  INVEST_INCOME DOUBLE,
  INVEST_INCOME_YOY DOUBLE,
  INVEST_JOINT_INCOME DOUBLE,
  -- INVEST_JOINT_INCOME_YOY: 全部样本为空, 默认 TEXT
  INVEST_JOINT_INCOME_YOY VARCHAR,
  -- NET_EXPOSURE_INCOME: 全部样本为空, 默认 TEXT
  NET_EXPOSURE_INCOME VARCHAR,
  -- NET_EXPOSURE_INCOME_YOY: 全部样本为空, 默认 TEXT
  NET_EXPOSURE_INCOME_YOY VARCHAR,
  -- EXCHANGE_INCOME: 全部样本为空, 默认 TEXT
  EXCHANGE_INCOME VARCHAR,
  -- EXCHANGE_INCOME_YOY: 全部样本为空, 默认 TEXT
  EXCHANGE_INCOME_YOY VARCHAR,
  ASSET_DISPOSAL_INCOME DOUBLE,
  ASSET_DISPOSAL_INCOME_YOY DOUBLE,
  ASSET_IMPAIRMENT_INCOME DOUBLE,
  -- ASSET_IMPAIRMENT_INCOME_YOY: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_INCOME_YOY VARCHAR,
  CREDIT_IMPAIRMENT_INCOME DOUBLE,
  CREDIT_IMPAIRMENT_INCOME_YOY DOUBLE,
  OTHER_INCOME DOUBLE,
  OTHER_INCOME_YOY DOUBLE,
  OPERATE_PROFIT_OTHER INTEGER,
  -- OPERATE_PROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_PROFIT_OTHER_YOY VARCHAR,
  OPERATE_PROFIT_BALANCE DOUBLE,
  OPERATE_PROFIT_BALANCE_YOY DOUBLE,
  OPERATE_PROFIT DOUBLE NOT NULL,
  OPERATE_PROFIT_YOY DOUBLE,
  NONBUSINESS_INCOME DOUBLE NOT NULL,
  NONBUSINESS_INCOME_YOY DOUBLE,
  NONCURRENT_DISPOSAL_INCOME DOUBLE,
  NONCURRENT_DISPOSAL_INCOME_YOY DOUBLE,
  NONBUSINESS_EXPENSE DOUBLE,
  NONBUSINESS_EXPENSE_YOY DOUBLE,
  NONCURRENT_DISPOSAL_LOSS DOUBLE,
  NONCURRENT_DISPOSAL_LOSS_YOY DOUBLE,
  EFFECT_TP_OTHER INTEGER,
  -- EFFECT_TP_OTHER_YOY: 全部样本为空, 默认 TEXT
  EFFECT_TP_OTHER_YOY VARCHAR,
  TOTAL_PROFIT_BALANCE INTEGER,
  TOTAL_PROFIT_BALANCE_YOY DOUBLE,
  TOTAL_PROFIT DOUBLE NOT NULL,
  TOTAL_PROFIT_YOY DOUBLE,
  INCOME_TAX DOUBLE NOT NULL,
  INCOME_TAX_YOY DOUBLE,
  -- EFFECT_NETPROFIT_OTHER: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_OTHER VARCHAR,
  -- EFFECT_NETPROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_OTHER_YOY VARCHAR,
  EFFECT_NETPROFIT_BALANCE INTEGER,
  -- EFFECT_NETPROFIT_BALANCE_YOY: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_BALANCE_YOY VARCHAR,
  -- UNCONFIRM_INVEST_LOSS: 全部样本为空, 默认 TEXT
  UNCONFIRM_INVEST_LOSS VARCHAR,
  -- UNCONFIRM_INVEST_LOSS_YOY: 全部样本为空, 默认 TEXT
  UNCONFIRM_INVEST_LOSS_YOY VARCHAR,
  NETPROFIT DOUBLE NOT NULL,
  NETPROFIT_YOY DOUBLE,
  -- PRECOMBINE_PROFIT: 全部样本为空, 默认 TEXT
  PRECOMBINE_PROFIT VARCHAR,
  -- PRECOMBINE_PROFIT_YOY: 全部样本为空, 默认 TEXT
  PRECOMBINE_PROFIT_YOY VARCHAR,
  CONTINUED_NETPROFIT DOUBLE,
  CONTINUED_NETPROFIT_YOY DOUBLE,
  -- DISCONTINUED_NETPROFIT: 全部样本为空, 默认 TEXT
  DISCONTINUED_NETPROFIT VARCHAR,
  -- DISCONTINUED_NETPROFIT_YOY: 全部样本为空, 默认 TEXT
  DISCONTINUED_NETPROFIT_YOY VARCHAR,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  PARENT_NETPROFIT_YOY DOUBLE,
  MINORITY_INTEREST DOUBLE NOT NULL,
  MINORITY_INTEREST_YOY DOUBLE,
  DEDUCT_PARENT_NETPROFIT DOUBLE,
  DEDUCT_PARENT_NETPROFIT_YOY DOUBLE,
  -- NETPROFIT_OTHER: 全部样本为空, 默认 TEXT
  NETPROFIT_OTHER VARCHAR,
  -- NETPROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  NETPROFIT_OTHER_YOY VARCHAR,
  -- NETPROFIT_BALANCE: 全部样本为空, 默认 TEXT
  NETPROFIT_BALANCE VARCHAR,
  -- NETPROFIT_BALANCE_YOY: 全部样本为空, 默认 TEXT
  NETPROFIT_BALANCE_YOY VARCHAR,
  BASIC_EPS DOUBLE,
  BASIC_EPS_YOY DOUBLE,
  DILUTED_EPS DOUBLE,
  DILUTED_EPS_YOY DOUBLE,
  OTHER_COMPRE_INCOME DOUBLE,
  OTHER_COMPRE_INCOME_YOY DOUBLE,
  PARENT_OCI DOUBLE,
  PARENT_OCI_YOY DOUBLE,
  MINORITY_OCI DOUBLE,
  -- MINORITY_OCI_YOY: 全部样本为空, 默认 TEXT
  MINORITY_OCI_YOY VARCHAR,
  -- PARENT_OCI_OTHER: 全部样本为空, 默认 TEXT
  PARENT_OCI_OTHER VARCHAR,
  -- PARENT_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  PARENT_OCI_OTHER_YOY VARCHAR,
  -- PARENT_OCI_BALANCE: 全部样本为空, 默认 TEXT
  PARENT_OCI_BALANCE VARCHAR,
  -- PARENT_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  PARENT_OCI_BALANCE_YOY VARCHAR,
  -- UNABLE_OCI: 全部样本为空, 默认 TEXT
  UNABLE_OCI VARCHAR,
  -- UNABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_YOY VARCHAR,
  -- CREDITRISK_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  CREDITRISK_FAIRVALUE_CHANGE VARCHAR,
  -- CREDITRISK_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  CREDITRISK_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- OTHERRIGHT_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  OTHERRIGHT_FAIRVALUE_CHANGE VARCHAR,
  -- OTHERRIGHT_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  OTHERRIGHT_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- SETUP_PROFIT_CHANGE: 全部样本为空, 默认 TEXT
  SETUP_PROFIT_CHANGE VARCHAR,
  -- SETUP_PROFIT_CHANGE_YOY: 全部样本为空, 默认 TEXT
  SETUP_PROFIT_CHANGE_YOY VARCHAR,
  -- RIGHTLAW_UNABLE_OCI: 全部样本为空, 默认 TEXT
  RIGHTLAW_UNABLE_OCI VARCHAR,
  -- RIGHTLAW_UNABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  RIGHTLAW_UNABLE_OCI_YOY VARCHAR,
  -- UNABLE_OCI_OTHER: 全部样本为空, 默认 TEXT
  UNABLE_OCI_OTHER VARCHAR,
  -- UNABLE_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_OTHER_YOY VARCHAR,
  -- UNABLE_OCI_BALANCE: 全部样本为空, 默认 TEXT
  UNABLE_OCI_BALANCE VARCHAR,
  -- UNABLE_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_BALANCE_YOY VARCHAR,
  ABLE_OCI DOUBLE,
  ABLE_OCI_YOY DOUBLE,
  -- RIGHTLAW_ABLE_OCI: 全部样本为空, 默认 TEXT
  RIGHTLAW_ABLE_OCI VARCHAR,
  -- RIGHTLAW_ABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  RIGHTLAW_ABLE_OCI_YOY VARCHAR,
  -- AFA_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  AFA_FAIRVALUE_CHANGE VARCHAR,
  -- AFA_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  AFA_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- HMI_AFA: 全部样本为空, 默认 TEXT
  HMI_AFA VARCHAR,
  -- HMI_AFA_YOY: 全部样本为空, 默认 TEXT
  HMI_AFA_YOY VARCHAR,
  -- CASHFLOW_HEDGE_VALID: 全部样本为空, 默认 TEXT
  CASHFLOW_HEDGE_VALID VARCHAR,
  -- CASHFLOW_HEDGE_VALID_YOY: 全部样本为空, 默认 TEXT
  CASHFLOW_HEDGE_VALID_YOY VARCHAR,
  CREDITOR_FAIRVALUE_CHANGE DOUBLE,
  -- CREDITOR_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  CREDITOR_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- CREDITOR_IMPAIRMENT_RESERVE: 全部样本为空, 默认 TEXT
  CREDITOR_IMPAIRMENT_RESERVE VARCHAR,
  -- CREDITOR_IMPAIRMENT_RESERVE_YOY: 全部样本为空, 默认 TEXT
  CREDITOR_IMPAIRMENT_RESERVE_YOY VARCHAR,
  -- FINANCE_OCI_AMT: 全部样本为空, 默认 TEXT
  FINANCE_OCI_AMT VARCHAR,
  -- FINANCE_OCI_AMT_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OCI_AMT_YOY VARCHAR,
  CONVERT_DIFF DOUBLE,
  CONVERT_DIFF_YOY DOUBLE,
  -- ABLE_OCI_OTHER: 全部样本为空, 默认 TEXT
  ABLE_OCI_OTHER VARCHAR,
  -- ABLE_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  ABLE_OCI_OTHER_YOY VARCHAR,
  -- ABLE_OCI_BALANCE: 全部样本为空, 默认 TEXT
  ABLE_OCI_BALANCE VARCHAR,
  -- ABLE_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  ABLE_OCI_BALANCE_YOY VARCHAR,
  -- OCI_OTHER: 全部样本为空, 默认 TEXT
  OCI_OTHER VARCHAR,
  -- OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  OCI_OTHER_YOY VARCHAR,
  -- OCI_BALANCE: 全部样本为空, 默认 TEXT
  OCI_BALANCE VARCHAR,
  -- OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OCI_BALANCE_YOY VARCHAR,
  TOTAL_COMPRE_INCOME DOUBLE,
  TOTAL_COMPRE_INCOME_YOY DOUBLE,
  PARENT_TCI DOUBLE,
  PARENT_TCI_YOY DOUBLE,
  MINORITY_TCI DOUBLE,
  MINORITY_TCI_YOY DOUBLE,
  -- PRECOMBINE_TCI: 全部样本为空, 默认 TEXT
  PRECOMBINE_TCI VARCHAR,
  -- PRECOMBINE_TCI_YOY: 全部样本为空, 默认 TEXT
  PRECOMBINE_TCI_YOY VARCHAR,
  EFFECT_TCI_BALANCE INTEGER,
  -- EFFECT_TCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  EFFECT_TCI_BALANCE_YOY VARCHAR,
  -- TCI_OTHER: 全部样本为空, 默认 TEXT
  TCI_OTHER VARCHAR,
  -- TCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  TCI_OTHER_YOY VARCHAR,
  TCI_BALANCE INTEGER,
  -- TCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  TCI_BALANCE_YOY VARCHAR,
  -- ACF_END_INCOME: 全部样本为空, 默认 TEXT
  ACF_END_INCOME VARCHAR,
  -- ACF_END_INCOME_YOY: 全部样本为空, 默认 TEXT
  ACF_END_INCOME_YOY VARCHAR,
  OPINION_TYPE VARCHAR,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_gincome_report_date ON rpt_f10_finance_gincome(REPORT_DATE);
