-- ============================================================
-- RPT_F10_DIVIDENDNEW_PROFILE
-- dividend/分红融资概览 (quarterly)
-- 样本行数: 100, 字段数: 29
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividendnew_profile (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  TOTAL_DIVIDEND DOUBLE NOT NULL,
  TOTAL_RAISE_FUND DOUBLE NOT NULL,
  DIVIDEND_NUM INTEGER NOT NULL,
  TOTAL_NUM INTEGER NOT NULL,
  DIVIDEND_RATIO DOUBLE NOT NULL,
  DIVIDEND_PAY_RATIO DOUBLE NOT NULL,
  DIVIDEND_FINANCE_RATIO DOUBLE NOT NULL,
  IPO_NUM INTEGER NOT NULL,
  IPO_RAISE_FUND DOUBLE,
  SEO_NUM INTEGER NOT NULL,
  SEO_RAISE_FUND DOUBLE,
  ALLOTMENT_NUM INTEGER NOT NULL,
  ALLOTMENT_RAISE_FUND DOUBLE,
  PREFERRED_NUM INTEGER NOT NULL,
  PREFERRED_RAISE_FUND BIGINT,
  BOND_NUM INTEGER NOT NULL,
  BOND_RAISE_FUND BIGINT,
  RF_NUM INTEGER NOT NULL,
  RF_RAISE_FUND DOUBLE,
  DIVIDEND_RATIO_TTB DOUBLE NOT NULL,
  TOTAL_DIVIDEND_A DOUBLE NOT NULL,
  DIVIDEND_NEWRATIO DOUBLE NOT NULL,
  DIVIDEND_NEWRATIO_TTB DOUBLE NOT NULL,
  SUMCASH_HYA DOUBLE,
  SUMCASH_YSS DOUBLE,
  SUMCASH_LFY DOUBLE,
  PRIMARY KEY (SECUCODE)
);
