-- ============================================================
-- RPT_F10_EH_HOLDERNUM
-- shareholder/股东人数趋势 (quarterly)
-- 户数 / 集中度 / 人均流通股 / TOP10 占比
-- 样本行数: 100, 字段数: 38
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_eh_holdernum (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  HOLDER_TOTAL_NUM INTEGER NOT NULL,
  TOTAL_NUM_RATIO DOUBLE,
  HOLDER_A_NUM INTEGER NOT NULL,
  HOLDER_ANUM_RATIO DOUBLE,
  AVG_FREE_SHARES INTEGER,
  AVG_FREESHARES_RATIO DOUBLE,
  PRICE DOUBLE,
  AVG_HOLD_AMT DOUBLE,
  HOLD_FOCUS VARCHAR,
  HOLD_RATIO_TOTAL DOUBLE,
  -- FREEHOLD_RATIO_TOTAL: 全部样本为空, 默认 TEXT
  FREEHOLD_RATIO_TOTAL VARCHAR,
  -- HOLDER_B_NUM: 全部样本为空, 默认 TEXT
  HOLDER_B_NUM VARCHAR,
  -- HOLDER_H_NUM: 全部样本为空, 默认 TEXT
  HOLDER_H_NUM VARCHAR,
  -- HOLDER_BNUM_RATIO: 全部样本为空, 默认 TEXT
  HOLDER_BNUM_RATIO VARCHAR,
  -- HOLDER_HNUM_RATIO: 全部样本为空, 默认 TEXT
  HOLDER_HNUM_RATIO VARCHAR,
  HOLDER_TOTAL_NUMCHANGE INTEGER,
  AVG_TOTAL_SHARES DOUBLE NOT NULL,
  AVG_FREE_A_SHARES DOUBLE,
  NOTICE_DATE TIMESTAMP NOT NULL,
  -- FHOLD_RATIO_TOTAL: 全部样本为空, 默认 TEXT
  FHOLD_RATIO_TOTAL VARCHAR,
  SECURITY_TYPE VARCHAR NOT NULL,
  HOLDER_RATIO_TOTAL DOUBLE,
  A_MARK VARCHAR NOT NULL,
  B_MARK VARCHAR NOT NULL,
  H_MARK VARCHAR NOT NULL,
  TOTAL_HOLD_NUM INTEGER,
  -- TOTAL_SHAREHOLD_NUM: 全部样本为空, 默认 TEXT
  TOTAL_SHAREHOLD_NUM VARCHAR,
  MARKET VARCHAR NOT NULL,
  AVGCURSHARE DOUBLE,
  CHANGEWITHLAST DOUBLE,
  LISTING_STATE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  IS_APPROXIMATION VARCHAR,
  IS_DEFAULT VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, END_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_eh_holdernum_end_date ON rpt_f10_eh_holdernum(END_DATE);
