-- ============================================================
-- RPT_HSF10_RESPREDICT_COUNTSTATISTICS
-- forecast/预测统计扩展 (weekly)
-- 样本行数: 100, 字段数: 20
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_hsf10_respredict_countstatistics (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  YEAR INTEGER NOT NULL,
  YEAR_MARK VARCHAR NOT NULL,
  EPS DOUBLE NOT NULL,
  EPS_LASTMONTHS DOUBLE NOT NULL,
  BVPS DOUBLE NOT NULL,
  ROE DOUBLE,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  TOTAL_OPERATE_INCOME DOUBLE NOT NULL,
  OPERATE_PROFIT DOUBLE NOT NULL,
  -- EPS_COUNT: 全部样本为空, 默认 TEXT
  EPS_COUNT VARCHAR,
  -- EPS_LASTMONTHS_COUNT: 全部样本为空, 默认 TEXT
  EPS_LASTMONTHS_COUNT VARCHAR,
  -- BVPS_COUNT: 全部样本为空, 默认 TEXT
  BVPS_COUNT VARCHAR,
  -- ROE_COUNT: 全部样本为空, 默认 TEXT
  ROE_COUNT VARCHAR,
  -- PARENT_NETPROFIT_COUNT: 全部样本为空, 默认 TEXT
  PARENT_NETPROFIT_COUNT VARCHAR,
  -- TOTAL_OPERATE_INCOME_COUNT: 全部样本为空, 默认 TEXT
  TOTAL_OPERATE_INCOME_COUNT VARCHAR,
  -- OPERATE_PROFIT_COUNT: 全部样本为空, 默认 TEXT
  OPERATE_PROFIT_COUNT VARCHAR,
  RANK INTEGER NOT NULL,
  PRIMARY KEY (SECUCODE)
);
