-- ============================================================
-- RPT_F10_PUBLIC_OP_HOLDINGORG
-- profile/参股控股 (static)
-- 样本行数: 100, 字段数: 14
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_public_op_holdingorg (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  HOLD_ORG_NAME VARCHAR NOT NULL,
  REG_CAPITAL VARCHAR NOT NULL,
  ORG_HOLD_RATIO INTEGER NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_RANK INTEGER NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  HOLD_TYPE VARCHAR NOT NULL,
  ACTUAL_INVEST_AMT VARCHAR,
  NETPROFIT VARCHAR,
  MAIN_PRODUCTS VARCHAR,
  REPORT_DATE TIMESTAMP NOT NULL,
  IS_MAXREPORTDATE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE)
);
