-- ============================================================
-- RPT_F10_DIVIDEND_MAIN
-- dividend/分红明细 (event)
-- 替代 ak.stock_history_dividend_detail
-- 样本行数: 100, 字段数: 30
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividend_main (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  IMPL_PLAN_PROFILE VARCHAR NOT NULL,
  ASSIGN_PROGRESS VARCHAR NOT NULL,
  EQUITY_RECORD_DATE TIMESTAMP,
  EX_DIVIDEND_DATE TIMESTAMP,
  PAY_CASH_DATE TIMESTAMP,
  IS_UNASSIGN VARCHAR NOT NULL,
  REPORT_DATE VARCHAR NOT NULL,
  ASSIGN_OBJECT VARCHAR,
  IMPL_PLAN_NEWPROFILE VARCHAR NOT NULL,
  NEW_PROFILE VARCHAR NOT NULL,
  GMDECISION_NOTICE_DATE TIMESTAMP,
  INFO_CODE VARCHAR NOT NULL,
  DAT_YAGGR TIMESTAMP,
  TOTAL_DIVIDEND DOUBLE,
  TOTAL_DIVIDEND_A DOUBLE,
  REPORT_TIME TIMESTAMP NOT NULL,
  DAT_YAGGR_TODAY VARCHAR NOT NULL,
  NOTICE_TODAY VARCHAR NOT NULL,
  GMDECISION_TODAY VARCHAR NOT NULL,
  DIRECTORSUPERVISOR_TODAY VARCHAR NOT NULL,
  EQUITY_TODAY VARCHAR NOT NULL,
  EX_DIVIDEND_TODAY VARCHAR NOT NULL,
  PAYCASH_TODAY VARCHAR NOT NULL,
  IS_PAYCASH VARCHAR NOT NULL,
  IS_EQUITY_RECENT VARCHAR NOT NULL,
  -- LAST_TRADE_DATE: 全部样本为空, 默认 TEXT
  LAST_TRADE_DATE VARCHAR,
  PRIMARY KEY (SECUCODE, NOTICE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_dividend_main_notice_date ON rpt_f10_dividend_main(NOTICE_DATE);
