-- ============================================================
-- RPT_MAIN_ORGHOLDDETAIL
-- shareholder/机构持仓明细 (按机构) (quarterly)
-- 样本行数: 100, 字段数: 35
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_main_orgholddetail (
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  HOLDER_CODE VARCHAR NOT NULL,
  HOLDER_NAME VARCHAR NOT NULL,
  TOTAL_SHARES INTEGER NOT NULL,
  HOLD_VALUE BIGINT NOT NULL,
  TOTALSHARES_RATIO DOUBLE NOT NULL,
  FREESHARES_RATIO DOUBLE NOT NULL,
  FREE_MARKET_CAP BIGINT NOT NULL,
  FREE_SHARES INTEGER NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  FUND_CODE VARCHAR,
  FUND_DERIVECODE VARCHAR,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  F9_ORG_TYPE VARCHAR NOT NULL,
  F9_ORGTYPE_NAME VARCHAR NOT NULL,
  F9_HOLDER_NAME VARCHAR NOT NULL,
  ORG_NAME VARCHAR NOT NULL,
  NETVALUE_RATIO DOUBLE,
  REPORT_DATE_TYPE VARCHAR NOT NULL,
  REPORT_DATE_TYPECODE VARCHAR NOT NULL,
  FSR_CONTAIN_LOCK DOUBLE NOT NULL,
  HOLD_ORG_CODE_SOURCE VARCHAR,
  HOLDER_ORG_CODE VARCHAR NOT NULL,
  FUND_MANAGER VARCHAR,
  FUND_TYPE VARCHAR,
  FSR_CHANGE INTEGER NOT NULL,
  FSR_RATE_CHANGE DOUBLE NOT NULL,
  CHANGE_TYPE VARCHAR NOT NULL,
  FSR_RATE_CHANGE_NEW DOUBLE NOT NULL,
  CHANGE_TYPE_NEW VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE)
);
