-- ============================================================
-- RPT_F10_RELATE_RANK
-- related/同行业/概念/地域排名 (daily)
-- BOARD_TYPE_NEW=2 行业 / 3 概念 / 4 地域
-- 样本行数: 100, 字段数: 17
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_relate_rank (
  BOARD_CODE VARCHAR NOT NULL,
  BOARD_NAME VARCHAR NOT NULL,
  BOARD_TYPE_NEW VARCHAR NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  TOTAL_CAP DOUBLE NOT NULL,
  FREECAP DOUBLE NOT NULL,
  TOTAL_OPERATEINCOME DOUBLE NOT NULL,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  TOTALOPERATEREVETZ DOUBLE NOT NULL,
  PARENTNETPROFITTZ DOUBLE NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  CHANGE3 DOUBLE NOT NULL,
  CHANGE6 DOUBLE NOT NULL,
  CHANGE12 DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, BOARD_CODE)
);
