-- ============================================================
-- RPT_DATA_BLOCKTRADE
-- trading/大宗交易 (event)
-- 样本行数: 100, 字段数: 37
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_data_blocktrade (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  SECURITY_TYPE VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  DEAL_PRICE DOUBLE NOT NULL,
  PREMIUM_RATIO DOUBLE NOT NULL,
  DEAL_VOLUME INTEGER NOT NULL,
  DEAL_AMT DOUBLE NOT NULL,
  BUYER_NAME VARCHAR NOT NULL,
  SELLER_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  DAILY_RANK INTEGER NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  TRADE_UNIT VARCHAR NOT NULL,
  TURNOVER_RATE DOUBLE,
  CHANGE_RATE DOUBLE NOT NULL,
  CHANGE_RATE_1DAYS DOUBLE,
  -- CHANGE_RATE_5DAYS: 全部样本为空, 默认 TEXT
  CHANGE_RATE_5DAYS VARCHAR,
  BUYER_CODE VARCHAR NOT NULL,
  SELLER_CODE VARCHAR NOT NULL,
  PREMIUM_TURNOVER INTEGER NOT NULL,
  DISCOUNT_TURNOVER DOUBLE NOT NULL,
  UNLIMITED_A_SHARES BIGINT,
  TRADE_MARKET_OLD VARCHAR NOT NULL,
  SECURITY_TYPE_WEB VARCHAR NOT NULL,
  -- CHANGE_RATE_10DAYS: 全部样本为空, 默认 TEXT
  CHANGE_RATE_10DAYS VARCHAR,
  -- CHANGE_RATE_20DAYS: 全部样本为空, 默认 TEXT
  CHANGE_RATE_20DAYS VARCHAR,
  TRADE_MARKET_CODE VARCHAR NOT NULL,
  IS_SYSDATE INTEGER NOT NULL,
  FREE_SHARES_RATIO DOUBLE,
  TOTAL_SHARES_RATIO DOUBLE,
  INDEX_CLOSE DOUBLE,
  PRE_CLOSE_PRICE DOUBLE,
  TOTAL_SHARES BIGINT,
  DISCOUNT_RATIO DOUBLE,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_data_blocktrade_trade_date ON rpt_data_blocktrade(TRADE_DATE);
