-- ============================================================
-- RPT_F10_EH_EQUITY
-- share_capital/股本结构 / 历年变动 (event)
-- pageSize=1 取最新; 全量取历史变动
-- 样本行数: 100, 字段数: 69
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_eh_equity (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  CHANGE_REASON VARCHAR NOT NULL,
  LIMITED_SHARES BIGINT,
  UNLIMITED_SHARES BIGINT,
  TOTAL_SHARES BIGINT NOT NULL,
  LIMITED_SHARES_RATIO DOUBLE,
  LISTED_SHARES_RATIO DOUBLE,
  TOTAL_SHARES_RATIO VARCHAR NOT NULL,
  LISTED_A_SHARES BIGINT,
  LIMITED_A_SHARES BIGINT,
  LISTED_A_SHARES_RATIO DOUBLE,
  LIMITED_A_SHARES_RATIO DOUBLE,
  -- B_FREE_SHARE: 全部样本为空, 默认 TEXT
  B_FREE_SHARE VARCHAR,
  H_FREE_SHARE INTEGER,
  -- B_FREE_SHARE_RATIO: 全部样本为空, 默认 TEXT
  B_FREE_SHARE_RATIO VARCHAR,
  H_FREE_SHARE_RATIO DOUBLE,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NON_FREE_SHARES INTEGER,
  NON_FREESHARES_RATIO INTEGER,
  -- LIMITED_B_SHARES: 全部样本为空, 默认 TEXT
  LIMITED_B_SHARES VARCHAR,
  -- LIMITED_BSHARES_RATIO: 全部样本为空, 默认 TEXT
  LIMITED_BSHARES_RATIO VARCHAR,
  -- OTHER_FREE_SHARES: 全部样本为空, 默认 TEXT
  OTHER_FREE_SHARES VARCHAR,
  -- OTHER_FREESHARES_RATIO: 全部样本为空, 默认 TEXT
  OTHER_FREESHARES_RATIO VARCHAR,
  LIMITED_STATE_SHARES INTEGER,
  LIMITED_STATE_LEGAL INTEGER,
  LIMITED_OTHARS BIGINT,
  LIMITED_DOMESTIC_NOSTATE BIGINT,
  LIMITED_DOMESTIC_NATURAL INTEGER,
  LOCK_SHARES INTEGER,
  LIMITED_FOREIGN_SHARES INTEGER,
  LIMITED_OVERSEAS_NOSTATE INTEGER,
  LIMITED_OVERSEAS_NATURAL INTEGER,
  -- LIMITED_H_SHARES: 全部样本为空, 默认 TEXT
  LIMITED_H_SHARES VARCHAR,
  SPONSOR_SHARES INTEGER,
  STATE_SPONSOR_SHARES INTEGER,
  SPONSOR_SOCIAL_SHARES INTEGER,
  RAISE_SHARES INTEGER,
  RAISE_STATE_SHARES INTEGER,
  RAISE_DOMESTIC_SHARES INTEGER,
  RAISE_OVERSEAS_SHARES INTEGER,
  NOTICE_DATE TIMESTAMP NOT NULL,
  LISTING_DATE TIMESTAMP NOT NULL,
  LIMITED_SHARES_CHANGE INTEGER,
  UNLIMITED_SHARES_CHANGE INTEGER,
  TOTAL_SHARES_CHANGE INTEGER NOT NULL,
  LISTED_ASHARES_CHANGE INTEGER,
  LIMITED_ASHARES_CHANGE INTEGER,
  -- B_FREESHARE_CHANGE: 全部样本为空, 默认 TEXT
  B_FREESHARE_CHANGE VARCHAR,
  H_FREESHARE_CHANGE INTEGER,
  LIMITED_BSHARES_CHANGE INTEGER NOT NULL,
  NONFREE_SHARES_CHANGE INTEGER,
  -- OTHERFREE_SHARES_CHANGE: 全部样本为空, 默认 TEXT
  OTHERFREE_SHARES_CHANGE VARCHAR,
  FREE_SHARES BIGINT NOT NULL,
  CHANGE_REASON_EXPLAIN VARCHAR NOT NULL,
  -- LIMITED_H_SHARES_RATIO: 全部样本为空, 默认 TEXT
  LIMITED_H_SHARES_RATIO VARCHAR,
  -- LIMITED_H_SHARES_CHANGE: 全部样本为空, 默认 TEXT
  LIMITED_H_SHARES_CHANGE VARCHAR,
  IS_FREE_WINDOW VARCHAR NOT NULL,
  IS_LIMITED_WINDOW VARCHAR NOT NULL,
  LISTED_A_RATIOPC DOUBLE,
  -- LISTED_B_RATIOPC: 全部样本为空, 默认 TEXT
  LISTED_B_RATIOPC VARCHAR,
  LISTED_H_RATIOPC DOUBLE,
  -- LISTED_OTHER_RATIOPC: 全部样本为空, 默认 TEXT
  LISTED_OTHER_RATIOPC VARCHAR,
  LISTED_SUM_RATIOPC INTEGER NOT NULL,
  MARKET_CODE VARCHAR NOT NULL,
  IS_USE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, END_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_eh_equity_end_date ON rpt_f10_eh_equity(END_DATE);
