-- ============================================================
-- RPT_F10_ORGINFO_MANAINTRO
-- executives/高管列表 / 简介 (static)
-- 样本行数: 100, 字段数: 30
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_orginfo_manaintro (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  PERSON_NAME VARCHAR NOT NULL,
  INCUMBENT_DATE TIMESTAMP NOT NULL,
  POSITION VARCHAR NOT NULL,
  SEX VARCHAR NOT NULL,
  HIGH_DEGREE VARCHAR,
  AGE VARCHAR,
  RESUME VARCHAR NOT NULL,
  HOLD_NUM INTEGER,
  SALARY INTEGER,
  INCUMBENT_TIME VARCHAR NOT NULL,
  POSITION_TYPE_CODE VARCHAR NOT NULL,
  EM_2LEVEL_CLASSIF VARCHAR NOT NULL,
  EM_2LEVEL_CLASSIFCODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  PERSON_CODE VARCHAR NOT NULL,
  IS_COMPARE VARCHAR NOT NULL,
  POSITION_RANK INTEGER NOT NULL,
  -- PERSON_RANK: 全部样本为空, 默认 TEXT
  PERSON_RANK VARCHAR,
  REPORT_DATE TIMESTAMP,
  NATIONALITY VARCHAR,
  BIRTH_YEAR VARCHAR,
  HOLD_RATIO DOUBLE,
  IS_DSH VARCHAR NOT NULL,
  IS_JSH VARCHAR NOT NULL,
  IS_GLC VARCHAR NOT NULL,
  IND_HOLD_NUM INTEGER,
  IND_HOLD_RATIO DOUBLE,
  PRIMARY KEY (SECUCODE, PERSON_NAME)
);
