-- ============================================================
-- RPT_BILLBOARD_DAILYDETAILS
-- trading/龙虎榜单 (操盘版) (event)
-- 个股龙虎榜每日明细
-- 样本行数: 100, 字段数: 17
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_billboard_dailydetails (
  SECURITY_CODE VARCHAR NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  EXPLANATION VARCHAR NOT NULL,
  CHANGE_RATE DOUBLE NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  ACCUM_AMOUNT BIGINT NOT NULL,
  ACCUM_VOLUME INTEGER NOT NULL,
  TOTAL_BUY DOUBLE NOT NULL,
  TOTAL_SELL DOUBLE NOT NULL,
  TOTAL_NET DOUBLE NOT NULL,
  CHANGE_TYPE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  TRADE_ID VARCHAR NOT NULL,
  TURNRATE DOUBLE,
  TOTAL_BUYRIOTOP DOUBLE NOT NULL,
  TOTAL_SELLRIOTOP DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_billboard_dailydetails_trade_date ON rpt_billboard_dailydetails(TRADE_DATE);
