-- ============================================================
-- RPT_F10_FINANCE_GINCOMEQC
-- financial/利润表 (单季) (quarterly)
-- 样本行数: 100, 字段数: 299
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_gincomeqc (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  -- OPINION_TYPE: 全部样本为空, 默认 TEXT
  OPINION_TYPE VARCHAR,
  -- OSOPINION_TYPE: 全部样本为空, 默认 TEXT
  OSOPINION_TYPE VARCHAR,
  TOTAL_OPERATE_INCOME DOUBLE,
  TOTAL_OPERATE_INCOME_QOQ DOUBLE,
  OPERATE_INCOME DOUBLE,
  OPERATE_INCOME_QOQ DOUBLE,
  INTEREST_INCOME DOUBLE,
  INTEREST_INCOME_QOQ DOUBLE,
  EARNED_PREMIUM INTEGER,
  -- EARNED_PREMIUM_QOQ: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM_QOQ VARCHAR,
  FEE_COMMISSION_INCOME DOUBLE,
  FEE_COMMISSION_INCOME_QOQ DOUBLE,
  -- OTHER_BUSINESS_INCOME: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_INCOME VARCHAR,
  -- OTHER_BUSINESS_INCOME_QOQ: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_INCOME_QOQ VARCHAR,
  TOI_OTHER INTEGER,
  -- TOI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  TOI_OTHER_QOQ VARCHAR,
  TOTAL_OPERATE_COST DOUBLE NOT NULL,
  TOTAL_OPERATE_COST_QOQ DOUBLE NOT NULL,
  OPERATE_COST DOUBLE,
  OPERATE_COST_QOQ DOUBLE,
  INTEREST_EXPENSE DOUBLE,
  INTEREST_EXPENSE_QOQ DOUBLE,
  FEE_COMMISSION_EXPENSE DOUBLE,
  FEE_COMMISSION_EXPENSE_QOQ DOUBLE,
  -- RESEARCH_EXPENSE: 全部样本为空, 默认 TEXT
  RESEARCH_EXPENSE VARCHAR,
  -- RESEARCH_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  RESEARCH_EXPENSE_QOQ VARCHAR,
  SURRENDER_VALUE INTEGER,
  -- SURRENDER_VALUE_QOQ: 全部样本为空, 默认 TEXT
  SURRENDER_VALUE_QOQ VARCHAR,
  NET_COMPENSATE_EXPENSE INTEGER,
  -- NET_COMPENSATE_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  NET_COMPENSATE_EXPENSE_QOQ VARCHAR,
  NET_CONTRACT_RESERVE INTEGER,
  -- NET_CONTRACT_RESERVE_QOQ: 全部样本为空, 默认 TEXT
  NET_CONTRACT_RESERVE_QOQ VARCHAR,
  POLICY_BONUS_EXPENSE INTEGER,
  -- POLICY_BONUS_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  POLICY_BONUS_EXPENSE_QOQ VARCHAR,
  REINSURE_EXPENSE INTEGER,
  -- REINSURE_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  REINSURE_EXPENSE_QOQ VARCHAR,
  -- OTHER_BUSINESS_COST: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_COST VARCHAR,
  -- OTHER_BUSINESS_COST_QOQ: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_COST_QOQ VARCHAR,
  OPERATE_TAX_ADD DOUBLE,
  OPERATE_TAX_ADD_QOQ DOUBLE,
  SALE_EXPENSE DOUBLE,
  SALE_EXPENSE_QOQ DOUBLE,
  MANAGE_EXPENSE DOUBLE NOT NULL,
  MANAGE_EXPENSE_QOQ DOUBLE NOT NULL,
  -- ME_RESEARCH_EXPENSE: 全部样本为空, 默认 TEXT
  ME_RESEARCH_EXPENSE VARCHAR,
  -- ME_RESEARCH_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  ME_RESEARCH_EXPENSE_QOQ VARCHAR,
  FINANCE_EXPENSE DOUBLE NOT NULL,
  FINANCE_EXPENSE_QOQ DOUBLE NOT NULL,
  -- FE_INTEREST_EXPENSE: 全部样本为空, 默认 TEXT
  FE_INTEREST_EXPENSE VARCHAR,
  -- FE_INTEREST_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  FE_INTEREST_EXPENSE_QOQ VARCHAR,
  -- FE_INTEREST_INCOME: 全部样本为空, 默认 TEXT
  FE_INTEREST_INCOME VARCHAR,
  -- FE_INTEREST_INCOME_QOQ: 全部样本为空, 默认 TEXT
  FE_INTEREST_INCOME_QOQ VARCHAR,
  ASSET_IMPAIRMENT_LOSS DOUBLE,
  ASSET_IMPAIRMENT_LOSS_QOQ DOUBLE,
  -- CREDIT_IMPAIRMENT_LOSS: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_LOSS VARCHAR,
  -- CREDIT_IMPAIRMENT_LOSS_QOQ: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_LOSS_QOQ VARCHAR,
  -- OTHER_INCOME: 全部样本为空, 默认 TEXT
  OTHER_INCOME VARCHAR,
  -- OTHER_INCOME_QOQ: 全部样本为空, 默认 TEXT
  OTHER_INCOME_QOQ VARCHAR,
  TOC_OTHER INTEGER,
  -- TOC_OTHER_QOQ: 全部样本为空, 默认 TEXT
  TOC_OTHER_QOQ VARCHAR,
  INVEST_INCOME DOUBLE,
  INVEST_INCOME_QOQ DOUBLE,
  INVEST_JOINT_INCOME DOUBLE,
  INVEST_JOINT_INCOME_QOQ DOUBLE,
  -- ACF_END_INCOME: 全部样本为空, 默认 TEXT
  ACF_END_INCOME VARCHAR,
  -- ACF_END_INCOME_QOQ: 全部样本为空, 默认 TEXT
  ACF_END_INCOME_QOQ VARCHAR,
  EXCHANGE_INCOME INTEGER,
  -- EXCHANGE_INCOME_QOQ: 全部样本为空, 默认 TEXT
  EXCHANGE_INCOME_QOQ VARCHAR,
  -- NET_EXPOSURE_INCOME: 全部样本为空, 默认 TEXT
  NET_EXPOSURE_INCOME VARCHAR,
  -- NET_EXPOSURE_INCOME_QOQ: 全部样本为空, 默认 TEXT
  NET_EXPOSURE_INCOME_QOQ VARCHAR,
  FAIRVALUE_CHANGE_INCOME DOUBLE,
  FAIRVALUE_CHANGE_INCOME_QOQ DOUBLE,
  -- ASSET_DISPOSAL_INCOME: 全部样本为空, 默认 TEXT
  ASSET_DISPOSAL_INCOME VARCHAR,
  -- ASSET_DISPOSAL_INCOME_QOQ: 全部样本为空, 默认 TEXT
  ASSET_DISPOSAL_INCOME_QOQ VARCHAR,
  -- CREDIT_IMPAIRMENT_INCOME: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_INCOME VARCHAR,
  -- CREDIT_IMPAIRMENT_INCOME_QOQ: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_INCOME_QOQ VARCHAR,
  -- ASSET_IMPAIRMENT_INCOME: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_INCOME VARCHAR,
  -- ASSET_IMPAIRMENT_INCOME_QOQ: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_INCOME_QOQ VARCHAR,
  OPERATE_PROFIT DOUBLE NOT NULL,
  OPERATE_PROFIT_QOQ DOUBLE NOT NULL,
  NONBUSINESS_INCOME DOUBLE,
  NONBUSINESS_INCOME_QOQ DOUBLE,
  -- NONCURRENT_DISPOSAL_INCOME: 全部样本为空, 默认 TEXT
  NONCURRENT_DISPOSAL_INCOME VARCHAR,
  -- NONCURRENT_DISPOSAL_INCOME_QOQ: 全部样本为空, 默认 TEXT
  NONCURRENT_DISPOSAL_INCOME_QOQ VARCHAR,
  NONBUSINESS_EXPENSE DOUBLE,
  NONBUSINESS_EXPENSE_QOQ DOUBLE,
  NONCURRENT_DISPOSAL_LOSS DOUBLE,
  NONCURRENT_DISPOSAL_LOSS_QOQ DOUBLE,
  OPERATE_PROFIT_OTHER INTEGER,
  -- OPERATE_PROFIT_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_PROFIT_OTHER_QOQ VARCHAR,
  OPERATE_PROFIT_BALANCE INTEGER,
  -- OPERATE_PROFIT_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_PROFIT_BALANCE_QOQ VARCHAR,
  TOTAL_PROFIT DOUBLE NOT NULL,
  TOTAL_PROFIT_QOQ DOUBLE NOT NULL,
  EFFECT_TP_OTHER INTEGER,
  -- EFFECT_TP_OTHER_QOQ: 全部样本为空, 默认 TEXT
  EFFECT_TP_OTHER_QOQ VARCHAR,
  TOTAL_PROFIT_BALANCE INTEGER,
  -- TOTAL_PROFIT_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  TOTAL_PROFIT_BALANCE_QOQ VARCHAR,
  INCOME_TAX DOUBLE,
  INCOME_TAX_QOQ DOUBLE,
  NETPROFIT DOUBLE NOT NULL,
  NETPROFIT_QOQ DOUBLE NOT NULL,
  -- CONTINUED_NETPROFIT: 全部样本为空, 默认 TEXT
  CONTINUED_NETPROFIT VARCHAR,
  -- CONTINUED_NETPROFIT_QOQ: 全部样本为空, 默认 TEXT
  CONTINUED_NETPROFIT_QOQ VARCHAR,
  -- DISCONTINUED_NETPROFIT: 全部样本为空, 默认 TEXT
  DISCONTINUED_NETPROFIT VARCHAR,
  -- DISCONTINUED_NETPROFIT_QOQ: 全部样本为空, 默认 TEXT
  DISCONTINUED_NETPROFIT_QOQ VARCHAR,
  -- NETPROFIT_OTHER: 全部样本为空, 默认 TEXT
  NETPROFIT_OTHER VARCHAR,
  -- NETPROFIT_OTHER_QOQ: 全部样本为空, 默认 TEXT
  NETPROFIT_OTHER_QOQ VARCHAR,
  -- NETPROFIT_BALANCE: 全部样本为空, 默认 TEXT
  NETPROFIT_BALANCE VARCHAR,
  -- NETPROFIT_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  NETPROFIT_BALANCE_QOQ VARCHAR,
  -- EFFECT_NETPROFIT_OTHER: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_OTHER VARCHAR,
  -- EFFECT_NETPROFIT_OTHER_QOQ: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_OTHER_QOQ VARCHAR,
  EFFECT_NETPROFIT_BALANCE INTEGER,
  -- EFFECT_NETPROFIT_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_BALANCE_QOQ VARCHAR,
  UNCONFIRM_INVEST_LOSS DOUBLE,
  UNCONFIRM_INVEST_LOSS_QOQ DOUBLE,
  MINORITY_INTEREST DOUBLE,
  MINORITY_INTEREST_QOQ DOUBLE,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  PARENT_NETPROFIT_QOQ DOUBLE NOT NULL,
  BASIC_EPS DOUBLE,
  BASIC_EPS_QOQ DOUBLE,
  DILUTED_EPS DOUBLE,
  DILUTED_EPS_QOQ DOUBLE,
  -- UNABLE_OCI: 全部样本为空, 默认 TEXT
  UNABLE_OCI VARCHAR,
  -- UNABLE_OCI_QOQ: 全部样本为空, 默认 TEXT
  UNABLE_OCI_QOQ VARCHAR,
  -- CREDITRISK_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  CREDITRISK_FAIRVALUE_CHANGE VARCHAR,
  -- CREDITRISK_FAIRVALUE_CHANGE_QOQ: 全部样本为空, 默认 TEXT
  CREDITRISK_FAIRVALUE_CHANGE_QOQ VARCHAR,
  -- OTHERRIGHT_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  OTHERRIGHT_FAIRVALUE_CHANGE VARCHAR,
  -- OTHERRIGHT_FAIRVALUE_CHANGE_QOQ: 全部样本为空, 默认 TEXT
  OTHERRIGHT_FAIRVALUE_CHANGE_QOQ VARCHAR,
  -- SETUP_PROFIT_CHANGE: 全部样本为空, 默认 TEXT
  SETUP_PROFIT_CHANGE VARCHAR,
  -- SETUP_PROFIT_CHANGE_QOQ: 全部样本为空, 默认 TEXT
  SETUP_PROFIT_CHANGE_QOQ VARCHAR,
  -- RIGHTLAW_UNABLE_OCI: 全部样本为空, 默认 TEXT
  RIGHTLAW_UNABLE_OCI VARCHAR,
  -- RIGHTLAW_UNABLE_OCI_QOQ: 全部样本为空, 默认 TEXT
  RIGHTLAW_UNABLE_OCI_QOQ VARCHAR,
  -- UNABLE_OCI_OTHER: 全部样本为空, 默认 TEXT
  UNABLE_OCI_OTHER VARCHAR,
  -- UNABLE_OCI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  UNABLE_OCI_OTHER_QOQ VARCHAR,
  -- UNABLE_OCI_BALANCE: 全部样本为空, 默认 TEXT
  UNABLE_OCI_BALANCE VARCHAR,
  -- UNABLE_OCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  UNABLE_OCI_BALANCE_QOQ VARCHAR,
  -- ABLE_OCI: 全部样本为空, 默认 TEXT
  ABLE_OCI VARCHAR,
  -- ABLE_OCI_QOQ: 全部样本为空, 默认 TEXT
  ABLE_OCI_QOQ VARCHAR,
  -- RIGHTLAW_ABLE_OCI: 全部样本为空, 默认 TEXT
  RIGHTLAW_ABLE_OCI VARCHAR,
  -- RIGHTLAW_ABLE_OCI_QOQ: 全部样本为空, 默认 TEXT
  RIGHTLAW_ABLE_OCI_QOQ VARCHAR,
  -- AFA_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  AFA_FAIRVALUE_CHANGE VARCHAR,
  -- AFA_FAIRVALUE_CHANGE_QOQ: 全部样本为空, 默认 TEXT
  AFA_FAIRVALUE_CHANGE_QOQ VARCHAR,
  -- HMI_AFA: 全部样本为空, 默认 TEXT
  HMI_AFA VARCHAR,
  -- HMI_AFA_QOQ: 全部样本为空, 默认 TEXT
  HMI_AFA_QOQ VARCHAR,
  -- CASHFLOW_HEDGE_VALID: 全部样本为空, 默认 TEXT
  CASHFLOW_HEDGE_VALID VARCHAR,
  -- CASHFLOW_HEDGE_VALID_QOQ: 全部样本为空, 默认 TEXT
  CASHFLOW_HEDGE_VALID_QOQ VARCHAR,
  -- CREDITOR_FAIRVALUE_CHANGE: 全部样本为空, 默认 TEXT
  CREDITOR_FAIRVALUE_CHANGE VARCHAR,
  -- CREDITOR_FAIRVALUE_CHANGE_QOQ: 全部样本为空, 默认 TEXT
  CREDITOR_FAIRVALUE_CHANGE_QOQ VARCHAR,
  -- CREDITOR_IMPAIRMENT_RESERVE: 全部样本为空, 默认 TEXT
  CREDITOR_IMPAIRMENT_RESERVE VARCHAR,
  -- CREDITOR_IMPAIRMENT_RESERVE_QOQ: 全部样本为空, 默认 TEXT
  CREDITOR_IMPAIRMENT_RESERVE_QOQ VARCHAR,
  -- FINANCE_OCI_AMT: 全部样本为空, 默认 TEXT
  FINANCE_OCI_AMT VARCHAR,
  -- FINANCE_OCI_AMT_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_OCI_AMT_QOQ VARCHAR,
  -- CONVERT_DIFF: 全部样本为空, 默认 TEXT
  CONVERT_DIFF VARCHAR,
  -- CONVERT_DIFF_QOQ: 全部样本为空, 默认 TEXT
  CONVERT_DIFF_QOQ VARCHAR,
  -- ABLE_OCI_OTHER: 全部样本为空, 默认 TEXT
  ABLE_OCI_OTHER VARCHAR,
  -- ABLE_OCI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  ABLE_OCI_OTHER_QOQ VARCHAR,
  -- ABLE_OCI_BALANCE: 全部样本为空, 默认 TEXT
  ABLE_OCI_BALANCE VARCHAR,
  -- ABLE_OCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  ABLE_OCI_BALANCE_QOQ VARCHAR,
  -- OCI_OTHER: 全部样本为空, 默认 TEXT
  OCI_OTHER VARCHAR,
  -- OCI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OCI_OTHER_QOQ VARCHAR,
  -- OCI_BALANCE: 全部样本为空, 默认 TEXT
  OCI_BALANCE VARCHAR,
  -- OCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  OCI_BALANCE_QOQ VARCHAR,
  OTHER_COMPRE_INCOME DOUBLE,
  OTHER_COMPRE_INCOME_QOQ DOUBLE,
  -- PARENT_OCI: 全部样本为空, 默认 TEXT
  PARENT_OCI VARCHAR,
  -- PARENT_OCI_QOQ: 全部样本为空, 默认 TEXT
  PARENT_OCI_QOQ VARCHAR,
  -- MINORITY_OCI: 全部样本为空, 默认 TEXT
  MINORITY_OCI VARCHAR,
  -- MINORITY_OCI_QOQ: 全部样本为空, 默认 TEXT
  MINORITY_OCI_QOQ VARCHAR,
  -- PARENT_OCI_OTHER: 全部样本为空, 默认 TEXT
  PARENT_OCI_OTHER VARCHAR,
  -- PARENT_OCI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  PARENT_OCI_OTHER_QOQ VARCHAR,
  -- PARENT_OCI_BALANCE: 全部样本为空, 默认 TEXT
  PARENT_OCI_BALANCE VARCHAR,
  -- PARENT_OCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  PARENT_OCI_BALANCE_QOQ VARCHAR,
  TOTAL_COMPRE_INCOME DOUBLE,
  TOTAL_COMPRE_INCOME_QOQ DOUBLE,
  PARENT_TCI DOUBLE,
  PARENT_TCI_QOQ DOUBLE,
  MINORITY_TCI DOUBLE,
  MINORITY_TCI_QOQ DOUBLE,
  EFFECT_TCI_BALANCE INTEGER,
  -- EFFECT_TCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  EFFECT_TCI_BALANCE_QOQ VARCHAR,
  -- TCI_OTHER: 全部样本为空, 默认 TEXT
  TCI_OTHER VARCHAR,
  -- TCI_OTHER_QOQ: 全部样本为空, 默认 TEXT
  TCI_OTHER_QOQ VARCHAR,
  TCI_BALANCE INTEGER,
  -- TCI_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  TCI_BALANCE_QOQ VARCHAR,
  PRECOMBINE_PROFIT DOUBLE,
  -- PRECOMBINE_PROFIT_QOQ: 全部样本为空, 默认 TEXT
  PRECOMBINE_PROFIT_QOQ VARCHAR,
  -- PRECOMBINE_TCI: 全部样本为空, 默认 TEXT
  PRECOMBINE_TCI VARCHAR,
  -- PRECOMBINE_TCI_QOQ: 全部样本为空, 默认 TEXT
  PRECOMBINE_TCI_QOQ VARCHAR,
  DEDUCT_PARENT_NETPROFIT DOUBLE,
  DEDUCT_PARENT_NETPROFIT_QOQ DOUBLE,
  TOTAL_OPERATE_INCOME_YOY DOUBLE,
  OPERATE_INCOME_YOY DOUBLE,
  INTEREST_INCOME_YOY DOUBLE,
  -- EARNED_PREMIUM_YOY: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM_YOY VARCHAR,
  FEE_COMMISSION_INCOME_YOY DOUBLE,
  -- OTHER_BUSINESS_INCOME_YOY: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_INCOME_YOY VARCHAR,
  -- TOI_OTHER_YOY: 全部样本为空, 默认 TEXT
  TOI_OTHER_YOY VARCHAR,
  TOTAL_OPERATE_COST_YOY DOUBLE NOT NULL,
  OPERATE_COST_YOY DOUBLE,
  INTEREST_EXPENSE_YOY DOUBLE,
  FEE_COMMISSION_EXPENSE_YOY DOUBLE,
  -- RESEARCH_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  RESEARCH_EXPENSE_YOY VARCHAR,
  -- SURRENDER_VALUE_YOY: 全部样本为空, 默认 TEXT
  SURRENDER_VALUE_YOY VARCHAR,
  -- NET_COMPENSATE_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  NET_COMPENSATE_EXPENSE_YOY VARCHAR,
  -- NET_CONTRACT_RESERVE_YOY: 全部样本为空, 默认 TEXT
  NET_CONTRACT_RESERVE_YOY VARCHAR,
  -- POLICY_BONUS_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  POLICY_BONUS_EXPENSE_YOY VARCHAR,
  -- REINSURE_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  REINSURE_EXPENSE_YOY VARCHAR,
  -- OTHER_BUSINESS_COST_YOY: 全部样本为空, 默认 TEXT
  OTHER_BUSINESS_COST_YOY VARCHAR,
  OPERATE_TAX_ADD_YOY DOUBLE,
  SALE_EXPENSE_YOY DOUBLE,
  MANAGE_EXPENSE_YOY DOUBLE NOT NULL,
  -- ME_RESEARCH_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  ME_RESEARCH_EXPENSE_YOY VARCHAR,
  FINANCE_EXPENSE_YOY DOUBLE NOT NULL,
  -- FE_INTEREST_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  FE_INTEREST_EXPENSE_YOY VARCHAR,
  -- FE_INTEREST_INCOME_YOY: 全部样本为空, 默认 TEXT
  FE_INTEREST_INCOME_YOY VARCHAR,
  ASSET_IMPAIRMENT_LOSS_YOY DOUBLE,
  -- CREDIT_IMPAIRMENT_LOSS_YOY: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_LOSS_YOY VARCHAR,
  -- OTHER_INCOME_YOY: 全部样本为空, 默认 TEXT
  OTHER_INCOME_YOY VARCHAR,
  -- TOC_OTHER_YOY: 全部样本为空, 默认 TEXT
  TOC_OTHER_YOY VARCHAR,
  INVEST_INCOME_YOY DOUBLE,
  INVEST_JOINT_INCOME_YOY DOUBLE,
  -- ACF_END_INCOME_YOY: 全部样本为空, 默认 TEXT
  ACF_END_INCOME_YOY VARCHAR,
  -- EXCHANGE_INCOME_YOY: 全部样本为空, 默认 TEXT
  EXCHANGE_INCOME_YOY VARCHAR,
  -- NET_EXPOSURE_INCOME_YOY: 全部样本为空, 默认 TEXT
  NET_EXPOSURE_INCOME_YOY VARCHAR,
  FAIRVALUE_CHANGE_INCOME_YOY DOUBLE,
  -- ASSET_DISPOSAL_INCOME_YOY: 全部样本为空, 默认 TEXT
  ASSET_DISPOSAL_INCOME_YOY VARCHAR,
  -- CREDIT_IMPAIRMENT_INCOME_YOY: 全部样本为空, 默认 TEXT
  CREDIT_IMPAIRMENT_INCOME_YOY VARCHAR,
  -- ASSET_IMPAIRMENT_INCOME_YOY: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_INCOME_YOY VARCHAR,
  OPERATE_PROFIT_YOY DOUBLE NOT NULL,
  NONBUSINESS_INCOME_YOY DOUBLE,
  -- NONCURRENT_DISPOSAL_INCOME_YOY: 全部样本为空, 默认 TEXT
  NONCURRENT_DISPOSAL_INCOME_YOY VARCHAR,
  NONBUSINESS_EXPENSE_YOY DOUBLE,
  NONCURRENT_DISPOSAL_LOSS_YOY DOUBLE,
  -- OPERATE_PROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_PROFIT_OTHER_YOY VARCHAR,
  OPERATE_PROFIT_BALANCE_YOY DOUBLE,
  TOTAL_PROFIT_YOY DOUBLE NOT NULL,
  -- EFFECT_TP_OTHER_YOY: 全部样本为空, 默认 TEXT
  EFFECT_TP_OTHER_YOY VARCHAR,
  TOTAL_PROFIT_BALANCE_YOY INTEGER,
  INCOME_TAX_YOY DOUBLE,
  NETPROFIT_YOY DOUBLE NOT NULL,
  -- CONTINUED_NETPROFIT_YOY: 全部样本为空, 默认 TEXT
  CONTINUED_NETPROFIT_YOY VARCHAR,
  -- DISCONTINUED_NETPROFIT_YOY: 全部样本为空, 默认 TEXT
  DISCONTINUED_NETPROFIT_YOY VARCHAR,
  -- NETPROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  NETPROFIT_OTHER_YOY VARCHAR,
  -- NETPROFIT_BALANCE_YOY: 全部样本为空, 默认 TEXT
  NETPROFIT_BALANCE_YOY VARCHAR,
  -- EFFECT_NETPROFIT_OTHER_YOY: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_OTHER_YOY VARCHAR,
  -- EFFECT_NETPROFIT_BALANCE_YOY: 全部样本为空, 默认 TEXT
  EFFECT_NETPROFIT_BALANCE_YOY VARCHAR,
  UNCONFIRM_INVEST_LOSS_YOY DOUBLE,
  MINORITY_INTEREST_YOY DOUBLE,
  PARENT_NETPROFIT_YOY DOUBLE NOT NULL,
  BASIC_EPS_YOY DOUBLE,
  DILUTED_EPS_YOY DOUBLE,
  -- UNABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_YOY VARCHAR,
  -- CREDITRISK_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  CREDITRISK_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- OTHERRIGHT_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  OTHERRIGHT_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- SETUP_PROFIT_CHANGE_YOY: 全部样本为空, 默认 TEXT
  SETUP_PROFIT_CHANGE_YOY VARCHAR,
  -- RIGHTLAW_UNABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  RIGHTLAW_UNABLE_OCI_YOY VARCHAR,
  -- UNABLE_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_OTHER_YOY VARCHAR,
  -- UNABLE_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  UNABLE_OCI_BALANCE_YOY VARCHAR,
  -- ABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  ABLE_OCI_YOY VARCHAR,
  -- RIGHTLAW_ABLE_OCI_YOY: 全部样本为空, 默认 TEXT
  RIGHTLAW_ABLE_OCI_YOY VARCHAR,
  -- AFA_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  AFA_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- HMI_AFA_YOY: 全部样本为空, 默认 TEXT
  HMI_AFA_YOY VARCHAR,
  -- CASHFLOW_HEDGE_VALID_YOY: 全部样本为空, 默认 TEXT
  CASHFLOW_HEDGE_VALID_YOY VARCHAR,
  -- CREDITOR_FAIRVALUE_CHANGE_YOY: 全部样本为空, 默认 TEXT
  CREDITOR_FAIRVALUE_CHANGE_YOY VARCHAR,
  -- CREDITOR_IMPAIRMENT_RESERVE_YOY: 全部样本为空, 默认 TEXT
  CREDITOR_IMPAIRMENT_RESERVE_YOY VARCHAR,
  -- FINANCE_OCI_AMT_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OCI_AMT_YOY VARCHAR,
  -- CONVERT_DIFF_YOY: 全部样本为空, 默认 TEXT
  CONVERT_DIFF_YOY VARCHAR,
  -- ABLE_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  ABLE_OCI_OTHER_YOY VARCHAR,
  -- ABLE_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  ABLE_OCI_BALANCE_YOY VARCHAR,
  -- OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  OCI_OTHER_YOY VARCHAR,
  -- OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OCI_BALANCE_YOY VARCHAR,
  OTHER_COMPRE_INCOME_YOY DOUBLE,
  -- PARENT_OCI_YOY: 全部样本为空, 默认 TEXT
  PARENT_OCI_YOY VARCHAR,
  -- MINORITY_OCI_YOY: 全部样本为空, 默认 TEXT
  MINORITY_OCI_YOY VARCHAR,
  -- PARENT_OCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  PARENT_OCI_OTHER_YOY VARCHAR,
  -- PARENT_OCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  PARENT_OCI_BALANCE_YOY VARCHAR,
  TOTAL_COMPRE_INCOME_YOY DOUBLE,
  PARENT_TCI_YOY DOUBLE,
  MINORITY_TCI_YOY DOUBLE,
  -- EFFECT_TCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  EFFECT_TCI_BALANCE_YOY VARCHAR,
  -- TCI_OTHER_YOY: 全部样本为空, 默认 TEXT
  TCI_OTHER_YOY VARCHAR,
  -- TCI_BALANCE_YOY: 全部样本为空, 默认 TEXT
  TCI_BALANCE_YOY VARCHAR,
  -- PRECOMBINE_PROFIT_YOY: 全部样本为空, 默认 TEXT
  PRECOMBINE_PROFIT_YOY VARCHAR,
  -- PRECOMBINE_TCI_YOY: 全部样本为空, 默认 TEXT
  PRECOMBINE_TCI_YOY VARCHAR,
  DEDUCT_PARENT_NETPROFIT_YOY DOUBLE,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_gincomeqc_report_date ON rpt_f10_finance_gincomeqc(REPORT_DATE);
