-- ============================================================
-- RPT_F10_EH_FREEHOLDERS
-- shareholder/十大流通股东 ⭐ (quarterly)
-- 项目主用 (流通股口径 alpha)
-- 样本行数: 100, 字段数: 40
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_eh_freeholders (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  HOLDER_NAME VARCHAR NOT NULL,
  HOLD_NUM INTEGER NOT NULL,
  FREE_HOLDNUM_RATIO DOUBLE NOT NULL,
  HOLD_NUM_CHANGE VARCHAR NOT NULL,
  CHANGE_RATIO DOUBLE,
  IS_HOLDORG VARCHAR NOT NULL,
  HOLDER_RANK INTEGER NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  HOLDER_CODE VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  HOLDER_STATE VARCHAR,
  HOLDER_MARKET_CAP DOUBLE NOT NULL,
  HOLD_RATIO DOUBLE NOT NULL,
  HOLD_CHANGE VARCHAR NOT NULL,
  HOLD_RATIO_CHANGE DOUBLE,
  HOLDER_TYPE VARCHAR NOT NULL,
  SHARES_TYPE VARCHAR NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  HOLDER_NEW VARCHAR NOT NULL,
  FREE_RATIO_QOQ VARCHAR NOT NULL,
  HOLDER_STATEE VARCHAR,
  IS_REPORT VARCHAR NOT NULL,
  HOLDER_CODE_OLD VARCHAR NOT NULL,
  HOLDER_NEWTYPE VARCHAR NOT NULL,
  HOLDNUM_CHANGE_NAME VARCHAR NOT NULL,
  IS_MAX_REPORTDATE VARCHAR NOT NULL,
  COOPERATION_HOLDER_MARK VARCHAR NOT NULL,
  MXID VARCHAR NOT NULL,
  LISTING_STATE VARCHAR NOT NULL,
  XZCHANGE INTEGER,
  NEW_CHANGE_RATIO VARCHAR NOT NULL,
  HOLDER_STATE_NEW VARCHAR NOT NULL,
  HOLD_ORG_CODE_SOURCE VARCHAR,
  HOLD_CHANGE_RATIOTB DOUBLE,
  HOLD_NUM_ABBR VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, END_DATE, HOLDER_RANK)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_eh_freeholders_end_date ON rpt_f10_eh_freeholders(END_DATE);
