-- ============================================================
-- RPT_PCF10_ORG_ISSUEINFO
-- profile/发行信息 (once)
-- 样本行数: 100, 字段数: 25
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_org_issueinfo (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  FOUND_DATE TIMESTAMP NOT NULL,
  LISTING_DATE TIMESTAMP NOT NULL,
  AFTER_ISSUE_PE DOUBLE,
  ONLINE_ISSUE_DATE TIMESTAMP,
  ISSUE_WAY VARCHAR NOT NULL,
  PAR_VALUE INTEGER NOT NULL,
  TOTAL_ISSUE_NUM INTEGER,
  ISSUE_PRICE DOUBLE,
  DEC_SUMISSUEFEE INTEGER,
  TOTAL_FUNDS INTEGER,
  NET_RAISE_FUNDS INTEGER,
  OPEN_PRICE DOUBLE NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  TURNOVERRATE DOUBLE,
  HIGH_PRICE DOUBLE NOT NULL,
  -- OFFLINE_VAP_RATIO: 全部样本为空, 默认 TEXT
  OFFLINE_VAP_RATIO VARCHAR,
  ONLINE_ISSUE_LWR DOUBLE,
  SECURITY_TYPE VARCHAR NOT NULL,
  -- OVERALLOTMENT: 全部样本为空, 默认 TEXT
  OVERALLOTMENT VARCHAR,
  TYPE VARCHAR NOT NULL,
  TRADE_MARKET_CODE VARCHAR NOT NULL,
  STR_ZHUCHENGXIAO VARCHAR,
  STR_BAOJIAN VARCHAR,
  PRIMARY KEY (SECUCODE)
);
