-- ============================================================
-- RPT_F10_MAIN_ORGHOLDDETAILS
-- shareholder/机构持仓概览 (ORG_TYPE 分桶) (quarterly)
-- ORG_TYPE: 01 基金 / 02 QFII / 03 社保 / 04 券商 / 05 保险 / 06 信托
-- 样本行数: 100, 字段数: 18
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_main_orgholddetails (
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  TOTAL_ORG_NUM INTEGER NOT NULL,
  TOTAL_FREE_SHARES BIGINT NOT NULL,
  TOTAL_MARKET_CAP DOUBLE NOT NULL,
  TOTAL_SHARES_RATIO DOUBLE NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  IS_INCREASE VARCHAR,
  IS_COMPLETE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  FREE_SHARES_CHANGE DOUBLE,
  CHANGE_RATIO DOUBLE,
  ORG_NAME_TYPE VARCHAR NOT NULL,
  ALL_SHARES_RATIO DOUBLE NOT NULL,
  TOTAL_SHARES BIGINT NOT NULL,
  TOTAL_FREE_SHARES_CHANGE BIGINT NOT NULL,
  CLOSE_PRICE DOUBLE,
  PRIMARY KEY (SECUCODE, ORG_TYPE)
);
