-- ============================================================
-- RPT_PCF10_INDUSTRY_CVALUE
-- peer/估值同行比较 (quarterly)
-- PEG/PE/PS 多年度 + 行业平均/中值/排名
-- 样本行数: 100, 字段数: 26
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_industry_cvalue (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECUCODE VARCHAR NOT NULL,
  CORRE_SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECURITY_NAME VARCHAR NOT NULL,
  PE DOUBLE NOT NULL,
  PE_TTM DOUBLE NOT NULL,
  PE_1Y DOUBLE,
  PE_2Y DOUBLE,
  PE_3Y DOUBLE,
  PS DOUBLE NOT NULL,
  PS_TTM DOUBLE NOT NULL,
  PS_1Y DOUBLE,
  PS_2Y DOUBLE,
  PS_3Y DOUBLE,
  PB DOUBLE NOT NULL,
  PB_MRQ DOUBLE NOT NULL,
  PCE_TTM DOUBLE NOT NULL,
  PCE DOUBLE NOT NULL,
  PCF_TTM DOUBLE NOT NULL,
  PCF DOUBLE NOT NULL,
  PEG DOUBLE,
  REPORT_DATE TIMESTAMP NOT NULL,
  TOTAL_COUNT INTEGER NOT NULL,
  PAIMING INTEGER,
  QYBS DOUBLE,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_pcf10_industry_cvalue_report_date ON rpt_pcf10_industry_cvalue(REPORT_DATE);
