-- ============================================================
-- RPT_F10_FINANCE_DUPONT
-- financial/杜邦分析 (quarterly)
-- 样本行数: 100, 字段数: 75
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_dupont (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  NETPROFIT DOUBLE NOT NULL,
  TOTAL_OPERATE_INCOME DOUBLE NOT NULL,
  TOTAL_ASSETS DOUBLE,
  TOTAL_LIABILITIES DOUBLE,
  TOTAL_CURRENT_ASSETS DOUBLE,
  TOTAL_NONCURRENT_ASSETS DOUBLE,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  SALE_NPR DOUBLE NOT NULL,
  TOTAL_ASSETS_TR DOUBLE NOT NULL,
  JROA DOUBLE,
  PARENT_NETPROFIT_RATIO DOUBLE NOT NULL,
  EQUITY_MULTIPLIER DOUBLE,
  ROE DOUBLE NOT NULL,
  DEBT_ASSET_RATIO DOUBLE,
  TOTAL_INCOME DOUBLE NOT NULL,
  TOTAL_COST DOUBLE NOT NULL,
  TOTAL_EXPENSE DOUBLE NOT NULL,
  MONETARYFUNDS DOUBLE,
  TRADE_FINASSET DOUBLE,
  NOTE_RECE DOUBLE,
  ACCOUNTS_RECE DOUBLE,
  FINANCE_RECE DOUBLE,
  OTHER_RECE DOUBLE,
  INVENTORY DOUBLE,
  CREDITOR_INVEST DOUBLE,
  LONG_EQUITY_INVEST DOUBLE,
  INVEST_REALESTATE DOUBLE,
  FIXED_ASSET DOUBLE,
  CIP DOUBLE,
  USERIGHT_ASSET DOUBLE,
  INTANGIBLE_ASSET DOUBLE,
  DEVELOP_EXPENSE DOUBLE,
  GOODWILL DOUBLE,
  LONG_PREPAID_EXPENSE DOUBLE,
  DEFER_TAX_ASSET DOUBLE,
  INVEST_INCOME DOUBLE,
  EXCHANGE_INCOME DOUBLE,
  FAIRVALUE_CHANGE_INCOME DOUBLE,
  ASSET_DISPOSAL_INCOME DOUBLE,
  OPERATE_COST DOUBLE,
  -- SURRENDER_VALUE: 全部样本为空, 默认 TEXT
  SURRENDER_VALUE VARCHAR,
  -- NET_COMPENSATE_EXPENSE: 全部样本为空, 默认 TEXT
  NET_COMPENSATE_EXPENSE VARCHAR,
  -- NET_CONTRACT_RESERVE: 全部样本为空, 默认 TEXT
  NET_CONTRACT_RESERVE VARCHAR,
  -- POLICY_BONUS_EXPENSE: 全部样本为空, 默认 TEXT
  POLICY_BONUS_EXPENSE VARCHAR,
  OPERATE_TAX_ADD DOUBLE,
  INCOME_TAX DOUBLE NOT NULL,
  ASSET_IMPAIRMENT_INCOME DOUBLE,
  CREDIT_IMPAIRMENT_INCOME DOUBLE,
  NONBUSINESS_EXPENSE DOUBLE,
  FINANCE_EXPENSE DOUBLE,
  SALE_EXPENSE DOUBLE,
  MANAGE_EXPENSE DOUBLE NOT NULL,
  RESEARCH_EXPENSE DOUBLE,
  -- INTEREST_NI: 全部样本为空, 默认 TEXT
  INTEREST_NI VARCHAR,
  -- FEE_COMMISSION_NI: 全部样本为空, 默认 TEXT
  FEE_COMMISSION_NI VARCHAR,
  -- EARNED_PREMIUM: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM VARCHAR,
  -- BUSINESS_MANAGE_EXPENSE: 全部样本为空, 默认 TEXT
  BUSINESS_MANAGE_EXPENSE VARCHAR,
  OTHER_CREDITOR_INVEST DOUBLE,
  OTHER_EQUITY_INVEST DOUBLE,
  LONG_RECE DOUBLE,
  AVAILABLE_SALE_FINASSET DOUBLE,
  -- HOLD_MATURITY_INVEST: 全部样本为空, 默认 TEXT
  HOLD_MATURITY_INVEST VARCHAR,
  -- FEE_COMMISSION_EXPENSE: 全部样本为空, 默认 TEXT
  FEE_COMMISSION_EXPENSE VARCHAR,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_dupont_report_date ON rpt_f10_finance_dupont(REPORT_DATE);
