-- ============================================================
-- RPT_F10_CORETHEME_CONTENT
-- themes/题材亮点 / 详情 (static)
-- 样本行数: 100, 字段数: 13
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_coretheme_content (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  KEYWORD VARCHAR NOT NULL,
  MAINPOINT INTEGER NOT NULL,
  MAINPOINT_CONTENT VARCHAR,
  KEY_CLASSIF VARCHAR NOT NULL,
  KEY_CLASSIF_CODE VARCHAR NOT NULL,
  IS_POINT VARCHAR NOT NULL,
  MAINPOINT_NUM VARCHAR NOT NULL,
  MAINPOINT_RANK INTEGER NOT NULL,
  IS_HISTORY VARCHAR NOT NULL,
  SECURITY_CODE4 VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, KEY_CLASSIF_CODE)
);
