-- ============================================================
-- RPT_MUTUAL_STOCK_HOLDRANKN_NEW
-- shareholder/沪深港通持股 (daily)
-- 样本行数: 100, 字段数: 27
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_mutual_stock_holdrankn_new (
  MUTUAL_TYPE VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  SECURITY_NAME VARCHAR NOT NULL,
  ADD_MARKET_CAP DOUBLE NOT NULL,
  ADD_SHARES_AMP DOUBLE,
  HOLD_SHARES_CHANGE INTEGER NOT NULL,
  HOLDSHARES_CHANGE_FREERATIO DOUBLE NOT NULL,
  HOLDSHARES_CHANGE_TOTALRATIO DOUBLE NOT NULL,
  HOLD_MARKET_CAP DOUBLE NOT NULL,
  HOLD_SHARES INTEGER NOT NULL,
  FREE_SHARES_RATIO DOUBLE NOT NULL,
  TOTAL_SHARES_RATIO DOUBLE NOT NULL,
  DATE_TYPE VARCHAR NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  CHANGE_RATE DOUBLE NOT NULL,
  REGION_CHANGE_RATE DOUBLE,
  INDUSTRY VARCHAR NOT NULL,
  BOARD_CODE VARCHAR NOT NULL,
  INTERVAL_TYPE VARCHAR NOT NULL,
  PARTICIPANT_NUM INTEGER NOT NULL,
  SECUCODE_HQ VARCHAR NOT NULL,
  BK_BOARD_NAME VARCHAR NOT NULL,
  BK_BOARD_CODE VARCHAR NOT NULL,
  CC_DATE TIMESTAMP NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_mutual_stock_holdrankn_new_trade_date ON rpt_mutual_stock_holdrankn_new(TRADE_DATE);
