-- ============================================================
-- RPT_F10_TRADE_EXCHANGEHOLD
-- executives/高管及相关人员持股变动 (event)
-- 兼容字段 RPT_EXECUTIVE_HOLD_DETAILS
-- 样本行数: 100, 字段数: 15
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_trade_exchangehold (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  SECURITY_PINYIN VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  HOLDER_NAME VARCHAR NOT NULL,
  CHANGE_NUM INTEGER NOT NULL,
  AVERAGE_PRICE DOUBLE,
  CHANGE_AFTER_HOLDNUM INTEGER NOT NULL,
  TRADE_WAY VARCHAR NOT NULL,
  EXECUTIVE_NAME VARCHAR NOT NULL,
  POSITION VARCHAR NOT NULL,
  EXECUTIVE_RELATION VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE)
);
