-- ============================================================
-- RPT_F10_DIVIDEND_CURVE
-- dividend/除权除息曲线 (daily)
-- 样本行数: 100, 字段数: 15
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividend_curve (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  DIVIDEND_RATIO_YSS DOUBLE NOT NULL,
  DIVIDEND_RATIO_HYY DOUBLE NOT NULL,
  YIELD_7DAYS DOUBLE NOT NULL,
  DIVIDEND_7DAYS DOUBLE NOT NULL,
  IS_SHOW VARCHAR NOT NULL,
  IS_EX_DIVIDEND_DATE VARCHAR NOT NULL,
  IMPL_PLAN_PROFILE VARCHAR,
  DIVIDEND_NEWRATIO_HYY DOUBLE NOT NULL,
  DIVIDEND_NEWRATIO_YSS DOUBLE NOT NULL,
  DIVIDEND_LFYRATIO DOUBLE NOT NULL,
  DIVIDEND_NEW7DAYS DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_dividend_curve_trade_date ON rpt_f10_dividend_curve(TRADE_DATE);
