-- ============================================================
-- RPT_HSF10_RES_PREDICTDETAIL
-- forecast/预测明细 (机构-分析师-发布日) (weekly)
-- 样本行数: 100, 字段数: 25
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_hsf10_res_predictdetail (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  PUBLISH_DATE TIMESTAMP NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_NAME_ABBR VARCHAR NOT NULL,
  RESEARCHER VARCHAR NOT NULL,
  YEAR1 INTEGER NOT NULL,
  YEAR_MARK1 VARCHAR NOT NULL,
  EPS1 DOUBLE NOT NULL,
  PARENT_NETPROFIT1 DOUBLE NOT NULL,
  YEAR2 INTEGER NOT NULL,
  YEAR_MARK2 VARCHAR NOT NULL,
  EPS2 DOUBLE,
  PARENT_NETPROFIT2 BIGINT NOT NULL,
  YEAR3 INTEGER NOT NULL,
  YEAR_MARK3 VARCHAR NOT NULL,
  EPS3 DOUBLE,
  PARENT_NETPROFIT3 BIGINT NOT NULL,
  YEAR4 INTEGER,
  YEAR_MARK4 VARCHAR,
  EPS4 DOUBLE,
  PARENT_NETPROFIT4 BIGINT,
  RATING VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, ORG_CODE)
);
