-- ============================================================
-- RPT_F10_BASIC_ORGINFO
-- profile/基本资料 (static)
-- 样本行数: 100, 字段数: 57
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_basic_orginfo (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_NAME VARCHAR NOT NULL,
  ORG_NAME_EN VARCHAR NOT NULL,
  FORMERNAME VARCHAR,
  STR_CODEA VARCHAR,
  STR_NAMEA VARCHAR,
  STR_CODEB VARCHAR,
  STR_NAMEB VARCHAR,
  STR_CODEH VARCHAR,
  STR_NAMEH VARCHAR,
  SECURITY_TYPE VARCHAR NOT NULL,
  EM2016 VARCHAR NOT NULL,
  TRADE_MARKET VARCHAR NOT NULL,
  INDUSTRYCSRC1 VARCHAR,
  PRESIDENT VARCHAR,
  LEGAL_PERSON VARCHAR NOT NULL,
  SECRETARY VARCHAR,
  CHAIRMAN VARCHAR,
  SECPRESENT VARCHAR,
  INDEDIRECTORS VARCHAR,
  ORG_TEL VARCHAR NOT NULL,
  ORG_EMAIL VARCHAR NOT NULL,
  ORG_FAX VARCHAR NOT NULL,
  ORG_WEB VARCHAR,
  ADDRESS VARCHAR NOT NULL,
  REG_ADDRESS VARCHAR NOT NULL,
  PROVINCE VARCHAR NOT NULL,
  ADDRESS_POSTCODE VARCHAR NOT NULL,
  REG_CAPITAL DOUBLE NOT NULL,
  REG_NUM VARCHAR,
  EMP_NUM INTEGER,
  TATOLNUMBER INTEGER NOT NULL,
  LAW_FIRM VARCHAR NOT NULL,
  ACCOUNTFIRM_NAME VARCHAR NOT NULL,
  ORG_PROFILE VARCHAR,
  BUSINESS_SCOPE VARCHAR NOT NULL,
  TRADE_MARKETT VARCHAR NOT NULL,
  TRADE_MARKET_CODE VARCHAR NOT NULL,
  SECURITY_TYPEE VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  -- EXPAND_NAME_ABBRN: 全部样本为空, 默认 TEXT
  EXPAND_NAME_ABBRN VARCHAR,
  -- EXPAND_NAME_PINYIN: 全部样本为空, 默认 TEXT
  EXPAND_NAME_PINYIN VARCHAR,
  -- EXPAND_NAME_ABBR: 全部样本为空, 默认 TEXT
  EXPAND_NAME_ABBR VARCHAR,
  LISTING_DATE TIMESTAMP NOT NULL,
  FOUND_DATE TIMESTAMP NOT NULL,
  MAIN_BUSINESS VARCHAR NOT NULL,
  HOST_BROKER VARCHAR,
  -- TRANSFER_WAY: 全部样本为空, 默认 TEXT
  TRANSFER_WAY VARCHAR,
  ACTUAL_HOLDER VARCHAR NOT NULL,
  -- MARKETING_START_DATE: 全部样本为空, 默认 TEXT
  MARKETING_START_DATE VARCHAR,
  -- MARKET_MAKER: 全部样本为空, 默认 TEXT
  MARKET_MAKER VARCHAR,
  -- TRADE_MARKET_TYPE: 全部样本为空, 默认 TEXT
  TRADE_MARKET_TYPE VARCHAR,
  CURRENCY VARCHAR NOT NULL,
  BOARD_NAME_LEVEL VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE)
);
