-- ============================================================
-- RPT_OPERATEDEPT_TRADE
-- trading/龙虎榜营业部 (买/卖) (event)
-- TRADE_DIRECTION=0 买 / 1 卖
-- 样本行数: 100, 字段数: 33
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_operatedept_trade (
  TRADE_ID VARCHAR NOT NULL,
  OPERATEDEPT_NAME VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  RANK INTEGER NOT NULL,
  TRADE_DIRECTION VARCHAR NOT NULL,
  OPERATEDEPT_CODE VARCHAR,
  STATISTICS_DAYS VARCHAR,
  BUY_AMT_REAL DOUBLE NOT NULL,
  SELL_AMT_REAL DOUBLE,
  ACCUM_AMOUNT BIGINT NOT NULL,
  BUY_RATIO DOUBLE NOT NULL,
  SELL_RATIO DOUBLE,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  BUY_AMT DOUBLE NOT NULL,
  SELL_AMT DOUBLE,
  EXPLANATION VARCHAR NOT NULL,
  NET_BUY DOUBLE NOT NULL,
  BUY_RATIO_TOTAL DOUBLE NOT NULL,
  SELL_RATIO_TOTAL DOUBLE NOT NULL,
  BUY_BUY_TOTAL DOUBLE NOT NULL,
  BUY_SELL_TOTAL DOUBLE NOT NULL,
  SELL_BUY_TOTAL DOUBLE NOT NULL,
  SELL_SELL_TOTAL DOUBLE NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  CHANGE_RATE DOUBLE NOT NULL,
  BUY_TOTAL DOUBLE NOT NULL,
  SELL_TOTAL DOUBLE NOT NULL,
  NET DOUBLE NOT NULL,
  TOTAL_BUYRIO DOUBLE NOT NULL,
  TOTAL_SELLRIO DOUBLE NOT NULL,
  BUY_TOTAL_NET DOUBLE NOT NULL,
  SELL_TOTAL_NET DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE, OPERATEDEPT_NAME, TRADE_DIRECTION)
);

CREATE INDEX IF NOT EXISTS idx_rpt_operatedept_trade_trade_date ON rpt_operatedept_trade(TRADE_DATE);
