-- ============================================================
-- RPT_PCF10_INDUSTRY_MARKET
-- peer/公司规模 (同行排序) (quarterly)
-- 样本行数: 100, 字段数: 20
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_industry_market (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  BOARD_CODE VARCHAR NOT NULL,
  BOARD_NAME VARCHAR NOT NULL,
  BOARD_TYPE_NEW VARCHAR NOT NULL,
  CORRE_SECUCODE VARCHAR NOT NULL,
  CORRE_SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECURITY_NAME VARCHAR NOT NULL,
  CORRE_ORG_CODE VARCHAR NOT NULL,
  TOTAL_CAP DOUBLE NOT NULL,
  FREECAP DOUBLE NOT NULL,
  TOTAL_OPERATEINCOME DOUBLE,
  NETPROFIT DOUBLE,
  REPORT_TYPE VARCHAR NOT NULL,
  TOTAL_CAP_RANK INTEGER,
  FREECAP_RANK INTEGER,
  TOTAL_OPERATEINCOME_RANK INTEGER,
  NETPROFIT_RANK INTEGER,
  PRIMARY KEY (SECUCODE)
);
