-- ============================================================
-- RPT_F10_EH_HOLDERS
-- shareholder/十大股东 (quarterly)
-- 样本行数: 100, 字段数: 26
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_eh_holders (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  END_DATE TIMESTAMP NOT NULL,
  HOLDER_NAME VARCHAR NOT NULL,
  HOLD_NUM INTEGER NOT NULL,
  HOLD_NUM_RATIO DOUBLE NOT NULL,
  HOLD_NUM_CHANGE VARCHAR NOT NULL,
  CHANGE_RATIO DOUBLE,
  HOLDER_CODE VARCHAR NOT NULL,
  IS_HOLDORG VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  HOLDER_RANK INTEGER NOT NULL,
  HOLDER_STATE VARCHAR,
  HOLDER_MARKET_CAP DOUBLE NOT NULL,
  HOLDER_NEW VARCHAR NOT NULL,
  HOLD_RATIO_QOQ VARCHAR NOT NULL,
  IS_REPORT VARCHAR NOT NULL,
  HOLDER_STATEE VARCHAR,
  SHARES_TYPE VARCHAR NOT NULL,
  HOLDER_CODE_OLD VARCHAR NOT NULL,
  NEW_CHANGE_RATIO VARCHAR NOT NULL,
  HOLDER_STATE_NEW VARCHAR NOT NULL,
  TOTAL_SHARES_NUM INTEGER NOT NULL,
  HOLD_NUM_ABBR VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, END_DATE, HOLDER_RANK)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_eh_holders_end_date ON rpt_f10_eh_holders(END_DATE);
