-- ============================================================
-- RPT_F10_QTR_MAINFINADATA
-- financial/主要指标 (按单季) (quarterly)
-- 样本行数: 100, 字段数: 26
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_qtr_mainfinadata (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  EPSJB DOUBLE NOT NULL,
  BPS DOUBLE NOT NULL,
  PER_CAPITAL_RESERVE DOUBLE NOT NULL,
  PER_UNASSIGN_PROFIT DOUBLE NOT NULL,
  PER_NETCASH DOUBLE NOT NULL,
  TOTALOPERATEREVE DOUBLE NOT NULL,
  GROSS_PROFIT DOUBLE,
  PARENTNETPROFIT DOUBLE NOT NULL,
  DEDU_PARENT_PROFIT DOUBLE NOT NULL,
  TOTALOPERATEREVETZ DOUBLE NOT NULL,
  PARENTNETPROFITTZ DOUBLE NOT NULL,
  DPNP_YOY_RATIO DOUBLE NOT NULL,
  YYZSRGDHBZC DOUBLE NOT NULL,
  NETPROFITRPHBZC DOUBLE NOT NULL,
  KFJLRGDHBZC DOUBLE NOT NULL,
  ROE_DILUTED DOUBLE NOT NULL,
  JROA DOUBLE NOT NULL,
  GROSS_PROFIT_RATIO DOUBLE,
  NET_PROFIT_RATIO DOUBLE NOT NULL,
  SEASON_LABEL VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_qtr_mainfinadata_report_date ON rpt_f10_qtr_mainfinadata(REPORT_DATE);
