-- ============================================================
-- RPT_F10_DIVIDENDNEW_LITY
-- dividend/分红提示 (派现概率) (quarterly)
-- 样本行数: 100, 字段数: 22
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividendnew_lity (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  DIVIDEND_LEVEL VARCHAR NOT NULL,
  SCORE INTEGER NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  BASIC_EPS DOUBLE NOT NULL,
  PER_UNASSIGN_PROFIT DOUBLE NOT NULL,
  PER_NETCASH_OPERATE DOUBLE NOT NULL,
  REPORT_YEAR_TYPE VARCHAR,
  PER_DIVIDEND DOUBLE,
  REPORT_MID_TYPE VARCHAR,
  IS_DIVIDEND VARCHAR NOT NULL,
  PUBLISH_INFO VARCHAR,
  IMPL_PLAN_PROFILE VARCHAR,
  IS_LXWFH VARCHAR NOT NULL,
  LXWFH_MARK VARCHAR,
  DIVIDEND_SUM_2Y INTEGER NOT NULL,
  IS_LISTING_5Y VARCHAR NOT NULL,
  DISCOUNT DOUBLE NOT NULL,
  LXWFH_NUM INTEGER,
  DIVIDEND_SUM_5Y INTEGER NOT NULL,
  PRIMARY KEY (SECUCODE)
);
