-- ============================================================
-- RPT_PCF10_INDUSTRY_GROWTH
-- peer/成长性同行比较 (quarterly)
-- EPS/营收 多年复合增长率 + 行业平均/中值/排名
-- 样本行数: 100, 字段数: 26
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_industry_growth (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECUCODE VARCHAR NOT NULL,
  CORRE_SECURITY_CODE VARCHAR NOT NULL,
  CORRE_SECURITY_NAME VARCHAR NOT NULL,
  YYSRTB DOUBLE NOT NULL,
  MGSYTB DOUBLE NOT NULL,
  JLRTB DOUBLE NOT NULL,
  JLR_3Y DOUBLE NOT NULL,
  YYSR_3Y DOUBLE NOT NULL,
  MGSY_3Y DOUBLE NOT NULL,
  YYSRTTM DOUBLE NOT NULL,
  MGSYTTM DOUBLE,
  JLRTTM DOUBLE NOT NULL,
  MGSY_1E DOUBLE,
  MGSY_2E DOUBLE,
  MGSY_3E DOUBLE,
  JLR_1E DOUBLE,
  JLR_2E DOUBLE,
  JLR_3E DOUBLE,
  YYSR_1E DOUBLE,
  YYSR_2E DOUBLE,
  YYSR_3E DOUBLE,
  PAIMING INTEGER NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  TOTAL_COUNT INTEGER NOT NULL,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_pcf10_industry_growth_report_date ON rpt_pcf10_industry_growth(REPORT_DATE);
