-- ============================================================
-- RPT_F10_FINANCE_GCASHFLOWQC
-- financial/现金流量表 (单季) (quarterly)
-- 样本行数: 100, 字段数: 372
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_gcashflowqc (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP,
  CURRENCY VARCHAR,
  SALES_SERVICES DOUBLE,
  -- DEPOSIT_INTERBANK_ADD: 全部样本为空, 默认 TEXT
  DEPOSIT_INTERBANK_ADD VARCHAR,
  -- LOAN_PBC_ADD: 全部样本为空, 默认 TEXT
  LOAN_PBC_ADD VARCHAR,
  -- OFI_BF_ADD: 全部样本为空, 默认 TEXT
  OFI_BF_ADD VARCHAR,
  -- RECEIVE_ORIGIC_PREMIUM: 全部样本为空, 默认 TEXT
  RECEIVE_ORIGIC_PREMIUM VARCHAR,
  -- RECEIVE_REINSURE_NET: 全部样本为空, 默认 TEXT
  RECEIVE_REINSURE_NET VARCHAR,
  -- INSURED_INVEST_ADD: 全部样本为空, 默认 TEXT
  INSURED_INVEST_ADD VARCHAR,
  -- DISPOSAL_TFA_ADD: 全部样本为空, 默认 TEXT
  DISPOSAL_TFA_ADD VARCHAR,
  -- RECEIVE_INTEREST_COMMISSION: 全部样本为空, 默认 TEXT
  RECEIVE_INTEREST_COMMISSION VARCHAR,
  -- BORROW_FUND_ADD: 全部样本为空, 默认 TEXT
  BORROW_FUND_ADD VARCHAR,
  -- LOAN_ADVANCE_REDUCE: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_REDUCE VARCHAR,
  -- REPO_BUSINESS_ADD: 全部样本为空, 默认 TEXT
  REPO_BUSINESS_ADD VARCHAR,
  RECEIVE_TAX_REFUND DOUBLE,
  RECEIVE_OTHER_OPERATE DOUBLE,
  -- OPERATE_INFLOW_OTHER: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_OTHER VARCHAR,
  OPERATE_INFLOW_BALANCE DOUBLE,
  TOTAL_OPERATE_INFLOW DOUBLE,
  BUY_SERVICES DOUBLE,
  -- LOAN_ADVANCE_ADD: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_ADD VARCHAR,
  -- PBC_INTERBANK_ADD: 全部样本为空, 默认 TEXT
  PBC_INTERBANK_ADD VARCHAR,
  -- PAY_ORIGIC_COMPENSATE: 全部样本为空, 默认 TEXT
  PAY_ORIGIC_COMPENSATE VARCHAR,
  -- PAY_INTEREST_COMMISSION: 全部样本为空, 默认 TEXT
  PAY_INTEREST_COMMISSION VARCHAR,
  -- PAY_POLICY_BONUS: 全部样本为空, 默认 TEXT
  PAY_POLICY_BONUS VARCHAR,
  PAY_STAFF_CASH DOUBLE,
  PAY_ALL_TAX DOUBLE,
  PAY_OTHER_OPERATE DOUBLE,
  -- OPERATE_OUTFLOW_OTHER: 全部样本为空, 默认 TEXT
  OPERATE_OUTFLOW_OTHER VARCHAR,
  OPERATE_OUTFLOW_BALANCE DOUBLE,
  TOTAL_OPERATE_OUTFLOW DOUBLE,
  -- OPERATE_NETCASH_OTHER: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHER VARCHAR,
  OPERATE_NETCASH_BALANCE INTEGER,
  NETCASH_OPERATE DOUBLE NOT NULL,
  WITHDRAW_INVEST DOUBLE,
  RECEIVE_INVEST_INCOME DOUBLE,
  DISPOSAL_LONG_ASSET DOUBLE,
  -- DISPOSAL_SUBSIDIARY_OTHER: 全部样本为空, 默认 TEXT
  DISPOSAL_SUBSIDIARY_OTHER VARCHAR,
  -- REDUCE_PLEDGE_TIMEDEPOSITS: 全部样本为空, 默认 TEXT
  REDUCE_PLEDGE_TIMEDEPOSITS VARCHAR,
  RECEIVE_OTHER_INVEST DOUBLE,
  -- INVEST_INFLOW_OTHER: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_OTHER VARCHAR,
  INVEST_INFLOW_BALANCE INTEGER,
  TOTAL_INVEST_INFLOW DOUBLE,
  CONSTRUCT_LONG_ASSET DOUBLE,
  INVEST_PAY_CASH DOUBLE,
  -- PLEDGE_LOAN_ADD: 全部样本为空, 默认 TEXT
  PLEDGE_LOAN_ADD VARCHAR,
  -- OBTAIN_SUBSIDIARY_OTHER: 全部样本为空, 默认 TEXT
  OBTAIN_SUBSIDIARY_OTHER VARCHAR,
  -- ADD_PLEDGE_TIMEDEPOSITS: 全部样本为空, 默认 TEXT
  ADD_PLEDGE_TIMEDEPOSITS VARCHAR,
  PAY_OTHER_INVEST DOUBLE,
  -- INVEST_OUTFLOW_OTHER: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_OTHER VARCHAR,
  INVEST_OUTFLOW_BALANCE INTEGER,
  TOTAL_INVEST_OUTFLOW DOUBLE,
  -- INVEST_NETCASH_OTHER: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_OTHER VARCHAR,
  INVEST_NETCASH_BALANCE INTEGER,
  NETCASH_INVEST DOUBLE,
  ACCEPT_INVEST_CASH DOUBLE,
  -- SUBSIDIARY_ACCEPT_INVEST: 全部样本为空, 默认 TEXT
  SUBSIDIARY_ACCEPT_INVEST VARCHAR,
  RECEIVE_LOAN_CASH DOUBLE,
  -- ISSUE_BOND: 全部样本为空, 默认 TEXT
  ISSUE_BOND VARCHAR,
  RECEIVE_OTHER_FINANCE DOUBLE,
  -- FINANCE_INFLOW_OTHER: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_OTHER VARCHAR,
  FINANCE_INFLOW_BALANCE INTEGER,
  TOTAL_FINANCE_INFLOW DOUBLE,
  PAY_DEBT_CASH DOUBLE,
  ASSIGN_DIVIDEND_PORFIT DOUBLE,
  SUBSIDIARY_PAY_DIVIDEND INTEGER,
  -- BUY_SUBSIDIARY_EQUITY: 全部样本为空, 默认 TEXT
  BUY_SUBSIDIARY_EQUITY VARCHAR,
  PAY_OTHER_FINANCE DOUBLE,
  -- SUBSIDIARY_REDUCE_CASH: 全部样本为空, 默认 TEXT
  SUBSIDIARY_REDUCE_CASH VARCHAR,
  -- FINANCE_OUTFLOW_OTHER: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_OTHER VARCHAR,
  FINANCE_OUTFLOW_BALANCE INTEGER,
  TOTAL_FINANCE_OUTFLOW DOUBLE,
  -- FINANCE_NETCASH_OTHER: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_OTHER VARCHAR,
  FINANCE_NETCASH_BALANCE INTEGER,
  NETCASH_FINANCE DOUBLE,
  RATE_CHANGE_EFFECT DOUBLE,
  -- CCE_ADD_OTHER: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHER VARCHAR,
  CCE_ADD_BALANCE INTEGER,
  CCE_ADD DOUBLE,
  -- BEGIN_CCE: 全部样本为空, 默认 TEXT
  BEGIN_CCE VARCHAR,
  -- END_CCE_OTHER: 全部样本为空, 默认 TEXT
  END_CCE_OTHER VARCHAR,
  -- END_CCE_BALANCE: 全部样本为空, 默认 TEXT
  END_CCE_BALANCE VARCHAR,
  -- END_CCE: 全部样本为空, 默认 TEXT
  END_CCE VARCHAR,
  SALES_SERVICES_QOQ DOUBLE,
  -- DEPOSIT_INTERBANK_ADD_QOQ: 全部样本为空, 默认 TEXT
  DEPOSIT_INTERBANK_ADD_QOQ VARCHAR,
  -- LOAN_PBC_ADD_QOQ: 全部样本为空, 默认 TEXT
  LOAN_PBC_ADD_QOQ VARCHAR,
  -- OFI_BF_ADD_QOQ: 全部样本为空, 默认 TEXT
  OFI_BF_ADD_QOQ VARCHAR,
  -- RECEIVE_ORIGIC_PREMIUM_QOQ: 全部样本为空, 默认 TEXT
  RECEIVE_ORIGIC_PREMIUM_QOQ VARCHAR,
  -- RECEIVE_REINSURE_NET_QOQ: 全部样本为空, 默认 TEXT
  RECEIVE_REINSURE_NET_QOQ VARCHAR,
  -- INSURED_INVEST_ADD_QOQ: 全部样本为空, 默认 TEXT
  INSURED_INVEST_ADD_QOQ VARCHAR,
  -- DISPOSAL_TFA_ADD_QOQ: 全部样本为空, 默认 TEXT
  DISPOSAL_TFA_ADD_QOQ VARCHAR,
  -- RECEIVE_INTEREST_COMMISSION_QOQ: 全部样本为空, 默认 TEXT
  RECEIVE_INTEREST_COMMISSION_QOQ VARCHAR,
  -- BORROW_FUND_ADD_QOQ: 全部样本为空, 默认 TEXT
  BORROW_FUND_ADD_QOQ VARCHAR,
  -- LOAN_ADVANCE_REDUCE_QOQ: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_REDUCE_QOQ VARCHAR,
  -- REPO_BUSINESS_ADD_QOQ: 全部样本为空, 默认 TEXT
  REPO_BUSINESS_ADD_QOQ VARCHAR,
  RECEIVE_TAX_REFUND_QOQ DOUBLE,
  RECEIVE_OTHER_OPERATE_QOQ DOUBLE,
  -- OPERATE_INFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_OTHER_QOQ VARCHAR,
  -- OPERATE_INFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_OPERATE_INFLOW_QOQ DOUBLE,
  BUY_SERVICES_QOQ DOUBLE,
  -- LOAN_ADVANCE_ADD_QOQ: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_ADD_QOQ VARCHAR,
  -- PBC_INTERBANK_ADD_QOQ: 全部样本为空, 默认 TEXT
  PBC_INTERBANK_ADD_QOQ VARCHAR,
  -- PAY_ORIGIC_COMPENSATE_QOQ: 全部样本为空, 默认 TEXT
  PAY_ORIGIC_COMPENSATE_QOQ VARCHAR,
  -- PAY_INTEREST_COMMISSION_QOQ: 全部样本为空, 默认 TEXT
  PAY_INTEREST_COMMISSION_QOQ VARCHAR,
  -- PAY_POLICY_BONUS_QOQ: 全部样本为空, 默认 TEXT
  PAY_POLICY_BONUS_QOQ VARCHAR,
  PAY_STAFF_CASH_QOQ DOUBLE,
  PAY_ALL_TAX_QOQ DOUBLE,
  PAY_OTHER_OPERATE_QOQ DOUBLE,
  -- OPERATE_OUTFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_OUTFLOW_OTHER_QOQ VARCHAR,
  -- OPERATE_OUTFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_OUTFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_OPERATE_OUTFLOW_QOQ DOUBLE,
  -- OPERATE_NETCASH_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHER_QOQ VARCHAR,
  -- OPERATE_NETCASH_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_BALANCE_QOQ VARCHAR,
  NETCASH_OPERATE_QOQ DOUBLE,
  WITHDRAW_INVEST_QOQ DOUBLE,
  RECEIVE_INVEST_INCOME_QOQ DOUBLE,
  DISPOSAL_LONG_ASSET_QOQ DOUBLE,
  -- DISPOSAL_SUBSIDIARY_OTHER_QOQ: 全部样本为空, 默认 TEXT
  DISPOSAL_SUBSIDIARY_OTHER_QOQ VARCHAR,
  -- REDUCE_PLEDGE_TIMEDEPOSITS_QOQ: 全部样本为空, 默认 TEXT
  REDUCE_PLEDGE_TIMEDEPOSITS_QOQ VARCHAR,
  RECEIVE_OTHER_INVEST_QOQ DOUBLE,
  -- INVEST_INFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_OTHER_QOQ VARCHAR,
  -- INVEST_INFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_INVEST_INFLOW_QOQ DOUBLE,
  CONSTRUCT_LONG_ASSET_QOQ DOUBLE,
  INVEST_PAY_CASH_QOQ DOUBLE,
  -- PLEDGE_LOAN_ADD_QOQ: 全部样本为空, 默认 TEXT
  PLEDGE_LOAN_ADD_QOQ VARCHAR,
  -- OBTAIN_SUBSIDIARY_OTHER_QOQ: 全部样本为空, 默认 TEXT
  OBTAIN_SUBSIDIARY_OTHER_QOQ VARCHAR,
  -- ADD_PLEDGE_TIMEDEPOSITS_QOQ: 全部样本为空, 默认 TEXT
  ADD_PLEDGE_TIMEDEPOSITS_QOQ VARCHAR,
  PAY_OTHER_INVEST_QOQ DOUBLE,
  -- INVEST_OUTFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_OTHER_QOQ VARCHAR,
  -- INVEST_OUTFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_INVEST_OUTFLOW_QOQ DOUBLE,
  -- INVEST_NETCASH_OTHER_QOQ: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_OTHER_QOQ VARCHAR,
  -- INVEST_NETCASH_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_BALANCE_QOQ VARCHAR,
  NETCASH_INVEST_QOQ DOUBLE,
  ACCEPT_INVEST_CASH_QOQ DOUBLE,
  -- SUBSIDIARY_ACCEPT_INVEST_QOQ: 全部样本为空, 默认 TEXT
  SUBSIDIARY_ACCEPT_INVEST_QOQ VARCHAR,
  RECEIVE_LOAN_CASH_QOQ DOUBLE,
  -- ISSUE_BOND_QOQ: 全部样本为空, 默认 TEXT
  ISSUE_BOND_QOQ VARCHAR,
  RECEIVE_OTHER_FINANCE_QOQ DOUBLE,
  -- FINANCE_INFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_OTHER_QOQ VARCHAR,
  -- FINANCE_INFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_FINANCE_INFLOW_QOQ DOUBLE,
  PAY_DEBT_CASH_QOQ DOUBLE,
  ASSIGN_DIVIDEND_PORFIT_QOQ DOUBLE,
  -- SUBSIDIARY_PAY_DIVIDEND_QOQ: 全部样本为空, 默认 TEXT
  SUBSIDIARY_PAY_DIVIDEND_QOQ VARCHAR,
  -- BUY_SUBSIDIARY_EQUITY_QOQ: 全部样本为空, 默认 TEXT
  BUY_SUBSIDIARY_EQUITY_QOQ VARCHAR,
  PAY_OTHER_FINANCE_QOQ DOUBLE,
  -- SUBSIDIARY_REDUCE_CASH_QOQ: 全部样本为空, 默认 TEXT
  SUBSIDIARY_REDUCE_CASH_QOQ VARCHAR,
  -- FINANCE_OUTFLOW_OTHER_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_OTHER_QOQ VARCHAR,
  -- FINANCE_OUTFLOW_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_BALANCE_QOQ VARCHAR,
  TOTAL_FINANCE_OUTFLOW_QOQ DOUBLE,
  -- FINANCE_NETCASH_OTHER_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_OTHER_QOQ VARCHAR,
  -- FINANCE_NETCASH_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_BALANCE_QOQ VARCHAR,
  NETCASH_FINANCE_QOQ DOUBLE,
  RATE_CHANGE_EFFECT_QOQ DOUBLE,
  -- CCE_ADD_OTHER_QOQ: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHER_QOQ VARCHAR,
  -- CCE_ADD_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCE_QOQ VARCHAR,
  CCE_ADD_QOQ DOUBLE,
  -- BEGIN_CCE_QOQ: 全部样本为空, 默认 TEXT
  BEGIN_CCE_QOQ VARCHAR,
  -- END_CCE_OTHER_QOQ: 全部样本为空, 默认 TEXT
  END_CCE_OTHER_QOQ VARCHAR,
  -- END_CCE_BALANCE_QOQ: 全部样本为空, 默认 TEXT
  END_CCE_BALANCE_QOQ VARCHAR,
  -- END_CCE_QOQ: 全部样本为空, 默认 TEXT
  END_CCE_QOQ VARCHAR,
  -- NETPROFIT: 全部样本为空, 默认 TEXT
  NETPROFIT VARCHAR,
  -- ASSET_IMPAIRMENT: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT VARCHAR,
  -- FA_IR_DEPR: 全部样本为空, 默认 TEXT
  FA_IR_DEPR VARCHAR,
  -- OILGAS_BIOLOGY_DEPR: 全部样本为空, 默认 TEXT
  OILGAS_BIOLOGY_DEPR VARCHAR,
  -- IR_DEPR: 全部样本为空, 默认 TEXT
  IR_DEPR VARCHAR,
  -- IA_AMORTIZE: 全部样本为空, 默认 TEXT
  IA_AMORTIZE VARCHAR,
  -- LPE_AMORTIZE: 全部样本为空, 默认 TEXT
  LPE_AMORTIZE VARCHAR,
  -- DEFER_INCOME_AMORTIZE: 全部样本为空, 默认 TEXT
  DEFER_INCOME_AMORTIZE VARCHAR,
  -- PREPAID_EXPENSE_REDUCE: 全部样本为空, 默认 TEXT
  PREPAID_EXPENSE_REDUCE VARCHAR,
  -- ACCRUED_EXPENSE_ADD: 全部样本为空, 默认 TEXT
  ACCRUED_EXPENSE_ADD VARCHAR,
  -- DISPOSAL_LONGASSET_LOSS: 全部样本为空, 默认 TEXT
  DISPOSAL_LONGASSET_LOSS VARCHAR,
  -- FA_SCRAP_LOSS: 全部样本为空, 默认 TEXT
  FA_SCRAP_LOSS VARCHAR,
  -- FAIRVALUE_CHANGE_LOSS: 全部样本为空, 默认 TEXT
  FAIRVALUE_CHANGE_LOSS VARCHAR,
  -- FINANCE_EXPENSE: 全部样本为空, 默认 TEXT
  FINANCE_EXPENSE VARCHAR,
  -- INVEST_LOSS: 全部样本为空, 默认 TEXT
  INVEST_LOSS VARCHAR,
  -- DEFER_TAX: 全部样本为空, 默认 TEXT
  DEFER_TAX VARCHAR,
  -- DT_ASSET_REDUCE: 全部样本为空, 默认 TEXT
  DT_ASSET_REDUCE VARCHAR,
  -- DT_LIAB_ADD: 全部样本为空, 默认 TEXT
  DT_LIAB_ADD VARCHAR,
  -- PREDICT_LIAB_ADD: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_ADD VARCHAR,
  -- INVENTORY_REDUCE: 全部样本为空, 默认 TEXT
  INVENTORY_REDUCE VARCHAR,
  -- OPERATE_RECE_REDUCE: 全部样本为空, 默认 TEXT
  OPERATE_RECE_REDUCE VARCHAR,
  -- OPERATE_PAYABLE_ADD: 全部样本为空, 默认 TEXT
  OPERATE_PAYABLE_ADD VARCHAR,
  -- OTHER: 全部样本为空, 默认 TEXT
  OTHER VARCHAR,
  -- OPERATE_NETCASH_OTHERNOTE: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHERNOTE VARCHAR,
  -- OPERATE_NETCASH_BALANCENOTE: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_BALANCENOTE VARCHAR,
  -- NETCASH_OPERATENOTE: 全部样本为空, 默认 TEXT
  NETCASH_OPERATENOTE VARCHAR,
  -- DEBT_TRANSFER_CAPITAL: 全部样本为空, 默认 TEXT
  DEBT_TRANSFER_CAPITAL VARCHAR,
  -- CONVERT_BOND_1YEAR: 全部样本为空, 默认 TEXT
  CONVERT_BOND_1YEAR VARCHAR,
  -- FINLEASE_OBTAIN_FA: 全部样本为空, 默认 TEXT
  FINLEASE_OBTAIN_FA VARCHAR,
  -- UNINVOLVE_INVESTFIN_OTHER: 全部样本为空, 默认 TEXT
  UNINVOLVE_INVESTFIN_OTHER VARCHAR,
  -- END_CASH: 全部样本为空, 默认 TEXT
  END_CASH VARCHAR,
  -- BEGIN_CASH: 全部样本为空, 默认 TEXT
  BEGIN_CASH VARCHAR,
  -- END_CASH_EQUIVALENTS: 全部样本为空, 默认 TEXT
  END_CASH_EQUIVALENTS VARCHAR,
  -- BEGIN_CASH_EQUIVALENTS: 全部样本为空, 默认 TEXT
  BEGIN_CASH_EQUIVALENTS VARCHAR,
  -- CCE_ADD_OTHERNOTE: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHERNOTE VARCHAR,
  -- CCE_ADD_BALANCENOTE: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCENOTE VARCHAR,
  -- CCE_ADDNOTE: 全部样本为空, 默认 TEXT
  CCE_ADDNOTE VARCHAR,
  -- MINORITY_INTEREST: 全部样本为空, 默认 TEXT
  MINORITY_INTEREST VARCHAR,
  -- NETPROFIT_QOQ: 全部样本为空, 默认 TEXT
  NETPROFIT_QOQ VARCHAR,
  -- ASSET_IMPAIRMENT_QOQ: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_QOQ VARCHAR,
  -- FA_IR_DEPR_QOQ: 全部样本为空, 默认 TEXT
  FA_IR_DEPR_QOQ VARCHAR,
  -- OILGAS_BIOLOGY_DEPR_QOQ: 全部样本为空, 默认 TEXT
  OILGAS_BIOLOGY_DEPR_QOQ VARCHAR,
  -- IR_DEPR_QOQ: 全部样本为空, 默认 TEXT
  IR_DEPR_QOQ VARCHAR,
  -- IA_AMORTIZE_QOQ: 全部样本为空, 默认 TEXT
  IA_AMORTIZE_QOQ VARCHAR,
  -- LPE_AMORTIZE_QOQ: 全部样本为空, 默认 TEXT
  LPE_AMORTIZE_QOQ VARCHAR,
  -- DEFER_INCOME_AMORTIZE_QOQ: 全部样本为空, 默认 TEXT
  DEFER_INCOME_AMORTIZE_QOQ VARCHAR,
  -- PREPAID_EXPENSE_REDUCE_QOQ: 全部样本为空, 默认 TEXT
  PREPAID_EXPENSE_REDUCE_QOQ VARCHAR,
  -- ACCRUED_EXPENSE_ADD_QOQ: 全部样本为空, 默认 TEXT
  ACCRUED_EXPENSE_ADD_QOQ VARCHAR,
  -- DISPOSAL_LONGASSET_LOSS_QOQ: 全部样本为空, 默认 TEXT
  DISPOSAL_LONGASSET_LOSS_QOQ VARCHAR,
  -- FA_SCRAP_LOSS_QOQ: 全部样本为空, 默认 TEXT
  FA_SCRAP_LOSS_QOQ VARCHAR,
  -- FAIRVALUE_CHANGE_LOSS_QOQ: 全部样本为空, 默认 TEXT
  FAIRVALUE_CHANGE_LOSS_QOQ VARCHAR,
  -- FINANCE_EXPENSE_QOQ: 全部样本为空, 默认 TEXT
  FINANCE_EXPENSE_QOQ VARCHAR,
  -- INVEST_LOSS_QOQ: 全部样本为空, 默认 TEXT
  INVEST_LOSS_QOQ VARCHAR,
  -- DEFER_TAX_QOQ: 全部样本为空, 默认 TEXT
  DEFER_TAX_QOQ VARCHAR,
  -- DT_ASSET_REDUCE_QOQ: 全部样本为空, 默认 TEXT
  DT_ASSET_REDUCE_QOQ VARCHAR,
  -- DT_LIAB_ADD_QOQ: 全部样本为空, 默认 TEXT
  DT_LIAB_ADD_QOQ VARCHAR,
  -- PREDICT_LIAB_ADD_QOQ: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_ADD_QOQ VARCHAR,
  -- INVENTORY_REDUCE_QOQ: 全部样本为空, 默认 TEXT
  INVENTORY_REDUCE_QOQ VARCHAR,
  -- OPERATE_RECE_REDUCE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_RECE_REDUCE_QOQ VARCHAR,
  -- OPERATE_PAYABLE_ADD_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_PAYABLE_ADD_QOQ VARCHAR,
  -- OTHER_QOQ: 全部样本为空, 默认 TEXT
  OTHER_QOQ VARCHAR,
  -- OPERATE_NETCASH_OTHERNOTE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHERNOTE_QOQ VARCHAR,
  -- OPERATE_NETCASH_BALANCENOTE_QOQ: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_BALANCENOTE_QOQ VARCHAR,
  -- NETCASH_OPERATENOTE_QOQ: 全部样本为空, 默认 TEXT
  NETCASH_OPERATENOTE_QOQ VARCHAR,
  -- DEBT_TRANSFER_CAPITAL_QOQ: 全部样本为空, 默认 TEXT
  DEBT_TRANSFER_CAPITAL_QOQ VARCHAR,
  -- CONVERT_BOND_1YEAR_QOQ: 全部样本为空, 默认 TEXT
  CONVERT_BOND_1YEAR_QOQ VARCHAR,
  -- FINLEASE_OBTAIN_FA_QOQ: 全部样本为空, 默认 TEXT
  FINLEASE_OBTAIN_FA_QOQ VARCHAR,
  -- UNINVOLVE_INVESTFIN_OTHER_QOQ: 全部样本为空, 默认 TEXT
  UNINVOLVE_INVESTFIN_OTHER_QOQ VARCHAR,
  -- END_CASH_QOQ: 全部样本为空, 默认 TEXT
  END_CASH_QOQ VARCHAR,
  -- BEGIN_CASH_QOQ: 全部样本为空, 默认 TEXT
  BEGIN_CASH_QOQ VARCHAR,
  -- END_CASH_EQUIVALENTS_QOQ: 全部样本为空, 默认 TEXT
  END_CASH_EQUIVALENTS_QOQ VARCHAR,
  -- BEGIN_CASH_EQUIVALENTS_QOQ: 全部样本为空, 默认 TEXT
  BEGIN_CASH_EQUIVALENTS_QOQ VARCHAR,
  -- CCE_ADD_OTHERNOTE_QOQ: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHERNOTE_QOQ VARCHAR,
  -- CCE_ADD_BALANCENOTE_QOQ: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCENOTE_QOQ VARCHAR,
  -- CCE_ADDNOTE_QOQ: 全部样本为空, 默认 TEXT
  CCE_ADDNOTE_QOQ VARCHAR,
  -- MINORITY_INTEREST_QOQ: 全部样本为空, 默认 TEXT
  MINORITY_INTEREST_QOQ VARCHAR,
  OPINION_TYPE VARCHAR,
  -- OSOPINION_TYPE: 全部样本为空, 默认 TEXT
  OSOPINION_TYPE VARCHAR,
  LISTING_STATE VARCHAR NOT NULL,
  -- SALES_SERVICES_YOY: 全部样本为空, 默认 TEXT
  SALES_SERVICES_YOY VARCHAR,
  -- DEPOSIT_INTERBANK_ADD_YOY: 全部样本为空, 默认 TEXT
  DEPOSIT_INTERBANK_ADD_YOY VARCHAR,
  -- LOAN_PBC_ADD_YOY: 全部样本为空, 默认 TEXT
  LOAN_PBC_ADD_YOY VARCHAR,
  -- OFI_BF_ADD_YOY: 全部样本为空, 默认 TEXT
  OFI_BF_ADD_YOY VARCHAR,
  -- RECEIVE_ORIGIC_PREMIUM_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_ORIGIC_PREMIUM_YOY VARCHAR,
  -- RECEIVE_REINSURE_NET_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_REINSURE_NET_YOY VARCHAR,
  -- INSURED_INVEST_ADD_YOY: 全部样本为空, 默认 TEXT
  INSURED_INVEST_ADD_YOY VARCHAR,
  -- DISPOSAL_TFA_ADD_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_TFA_ADD_YOY VARCHAR,
  -- RECEIVE_INTEREST_COMMISSION_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_INTEREST_COMMISSION_YOY VARCHAR,
  -- BORROW_FUND_ADD_YOY: 全部样本为空, 默认 TEXT
  BORROW_FUND_ADD_YOY VARCHAR,
  -- LOAN_ADVANCE_REDUCE_YOY: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_REDUCE_YOY VARCHAR,
  -- REPO_BUSINESS_ADD_YOY: 全部样本为空, 默认 TEXT
  REPO_BUSINESS_ADD_YOY VARCHAR,
  -- RECEIVE_TAX_REFUND_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_TAX_REFUND_YOY VARCHAR,
  -- RECEIVE_OTHER_OPERATE_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_OTHER_OPERATE_YOY VARCHAR,
  -- OPERATE_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_OTHER_YOY VARCHAR,
  -- OPERATE_INFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_INFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_OPERATE_INFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_OPERATE_INFLOW_YOY VARCHAR,
  -- BUY_SERVICES_YOY: 全部样本为空, 默认 TEXT
  BUY_SERVICES_YOY VARCHAR,
  -- LOAN_ADVANCE_ADD_YOY: 全部样本为空, 默认 TEXT
  LOAN_ADVANCE_ADD_YOY VARCHAR,
  -- PBC_INTERBANK_ADD_YOY: 全部样本为空, 默认 TEXT
  PBC_INTERBANK_ADD_YOY VARCHAR,
  -- PAY_ORIGIC_COMPENSATE_YOY: 全部样本为空, 默认 TEXT
  PAY_ORIGIC_COMPENSATE_YOY VARCHAR,
  -- PAY_INTEREST_COMMISSION_YOY: 全部样本为空, 默认 TEXT
  PAY_INTEREST_COMMISSION_YOY VARCHAR,
  -- PAY_POLICY_BONUS_YOY: 全部样本为空, 默认 TEXT
  PAY_POLICY_BONUS_YOY VARCHAR,
  -- PAY_STAFF_CASH_YOY: 全部样本为空, 默认 TEXT
  PAY_STAFF_CASH_YOY VARCHAR,
  -- PAY_ALL_TAX_YOY: 全部样本为空, 默认 TEXT
  PAY_ALL_TAX_YOY VARCHAR,
  -- PAY_OTHER_OPERATE_YOY: 全部样本为空, 默认 TEXT
  PAY_OTHER_OPERATE_YOY VARCHAR,
  -- OPERATE_OUTFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_OUTFLOW_OTHER_YOY VARCHAR,
  -- OPERATE_OUTFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_OUTFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_OPERATE_OUTFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_OPERATE_OUTFLOW_YOY VARCHAR,
  -- OPERATE_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHER_YOY VARCHAR,
  -- OPERATE_NETCASH_BALANCE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_BALANCE_YOY VARCHAR,
  -- NETCASH_OPERATE_YOY: 全部样本为空, 默认 TEXT
  NETCASH_OPERATE_YOY VARCHAR,
  -- WITHDRAW_INVEST_YOY: 全部样本为空, 默认 TEXT
  WITHDRAW_INVEST_YOY VARCHAR,
  -- RECEIVE_INVEST_INCOME_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_INVEST_INCOME_YOY VARCHAR,
  -- DISPOSAL_LONG_ASSET_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_LONG_ASSET_YOY VARCHAR,
  -- DISPOSAL_SUBSIDIARY_OTHER_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_SUBSIDIARY_OTHER_YOY VARCHAR,
  -- REDUCE_PLEDGE_TIMEDEPOSITS_YOY: 全部样本为空, 默认 TEXT
  REDUCE_PLEDGE_TIMEDEPOSITS_YOY VARCHAR,
  -- RECEIVE_OTHER_INVEST_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_OTHER_INVEST_YOY VARCHAR,
  -- INVEST_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_OTHER_YOY VARCHAR,
  -- INVEST_INFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  INVEST_INFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_INVEST_INFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_INVEST_INFLOW_YOY VARCHAR,
  -- CONSTRUCT_LONG_ASSET_YOY: 全部样本为空, 默认 TEXT
  CONSTRUCT_LONG_ASSET_YOY VARCHAR,
  -- INVEST_PAY_CASH_YOY: 全部样本为空, 默认 TEXT
  INVEST_PAY_CASH_YOY VARCHAR,
  -- PLEDGE_LOAN_ADD_YOY: 全部样本为空, 默认 TEXT
  PLEDGE_LOAN_ADD_YOY VARCHAR,
  -- OBTAIN_SUBSIDIARY_OTHER_YOY: 全部样本为空, 默认 TEXT
  OBTAIN_SUBSIDIARY_OTHER_YOY VARCHAR,
  -- ADD_PLEDGE_TIMEDEPOSITS_YOY: 全部样本为空, 默认 TEXT
  ADD_PLEDGE_TIMEDEPOSITS_YOY VARCHAR,
  -- PAY_OTHER_INVEST_YOY: 全部样本为空, 默认 TEXT
  PAY_OTHER_INVEST_YOY VARCHAR,
  -- INVEST_OUTFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_OTHER_YOY VARCHAR,
  -- INVEST_OUTFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  INVEST_OUTFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_INVEST_OUTFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_INVEST_OUTFLOW_YOY VARCHAR,
  -- INVEST_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_OTHER_YOY VARCHAR,
  -- INVEST_NETCASH_BALANCE_YOY: 全部样本为空, 默认 TEXT
  INVEST_NETCASH_BALANCE_YOY VARCHAR,
  -- NETCASH_INVEST_YOY: 全部样本为空, 默认 TEXT
  NETCASH_INVEST_YOY VARCHAR,
  -- ACCEPT_INVEST_CASH_YOY: 全部样本为空, 默认 TEXT
  ACCEPT_INVEST_CASH_YOY VARCHAR,
  -- SUBSIDIARY_ACCEPT_INVEST_YOY: 全部样本为空, 默认 TEXT
  SUBSIDIARY_ACCEPT_INVEST_YOY VARCHAR,
  -- RECEIVE_LOAN_CASH_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_LOAN_CASH_YOY VARCHAR,
  -- ISSUE_BOND_YOY: 全部样本为空, 默认 TEXT
  ISSUE_BOND_YOY VARCHAR,
  -- RECEIVE_OTHER_FINANCE_YOY: 全部样本为空, 默认 TEXT
  RECEIVE_OTHER_FINANCE_YOY VARCHAR,
  -- FINANCE_INFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_OTHER_YOY VARCHAR,
  -- FINANCE_INFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_INFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_FINANCE_INFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_FINANCE_INFLOW_YOY VARCHAR,
  -- PAY_DEBT_CASH_YOY: 全部样本为空, 默认 TEXT
  PAY_DEBT_CASH_YOY VARCHAR,
  -- ASSIGN_DIVIDEND_PORFIT_YOY: 全部样本为空, 默认 TEXT
  ASSIGN_DIVIDEND_PORFIT_YOY VARCHAR,
  -- SUBSIDIARY_PAY_DIVIDEND_YOY: 全部样本为空, 默认 TEXT
  SUBSIDIARY_PAY_DIVIDEND_YOY VARCHAR,
  -- BUY_SUBSIDIARY_EQUITY_YOY: 全部样本为空, 默认 TEXT
  BUY_SUBSIDIARY_EQUITY_YOY VARCHAR,
  -- PAY_OTHER_FINANCE_YOY: 全部样本为空, 默认 TEXT
  PAY_OTHER_FINANCE_YOY VARCHAR,
  -- SUBSIDIARY_REDUCE_CASH_YOY: 全部样本为空, 默认 TEXT
  SUBSIDIARY_REDUCE_CASH_YOY VARCHAR,
  -- FINANCE_OUTFLOW_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_OTHER_YOY VARCHAR,
  -- FINANCE_OUTFLOW_BALANCE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_OUTFLOW_BALANCE_YOY VARCHAR,
  -- TOTAL_FINANCE_OUTFLOW_YOY: 全部样本为空, 默认 TEXT
  TOTAL_FINANCE_OUTFLOW_YOY VARCHAR,
  -- FINANCE_NETCASH_OTHER_YOY: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_OTHER_YOY VARCHAR,
  -- FINANCE_NETCASH_BALANCE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_NETCASH_BALANCE_YOY VARCHAR,
  -- NETCASH_FINANCE_YOY: 全部样本为空, 默认 TEXT
  NETCASH_FINANCE_YOY VARCHAR,
  -- RATE_CHANGE_EFFECT_YOY: 全部样本为空, 默认 TEXT
  RATE_CHANGE_EFFECT_YOY VARCHAR,
  -- CCE_ADD_OTHER_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHER_YOY VARCHAR,
  -- CCE_ADD_BALANCE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCE_YOY VARCHAR,
  -- CCE_ADD_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_YOY VARCHAR,
  -- BEGIN_CCE_YOY: 全部样本为空, 默认 TEXT
  BEGIN_CCE_YOY VARCHAR,
  -- END_CCE_OTHER_YOY: 全部样本为空, 默认 TEXT
  END_CCE_OTHER_YOY VARCHAR,
  -- END_CCE_BALANCE_YOY: 全部样本为空, 默认 TEXT
  END_CCE_BALANCE_YOY VARCHAR,
  -- END_CCE_YOY: 全部样本为空, 默认 TEXT
  END_CCE_YOY VARCHAR,
  -- NETPROFIT_YOY: 全部样本为空, 默认 TEXT
  NETPROFIT_YOY VARCHAR,
  -- ASSET_IMPAIRMENT_YOY: 全部样本为空, 默认 TEXT
  ASSET_IMPAIRMENT_YOY VARCHAR,
  -- FA_IR_DEPR_YOY: 全部样本为空, 默认 TEXT
  FA_IR_DEPR_YOY VARCHAR,
  -- OILGAS_BIOLOGY_DEPR_YOY: 全部样本为空, 默认 TEXT
  OILGAS_BIOLOGY_DEPR_YOY VARCHAR,
  -- IR_DEPR_YOY: 全部样本为空, 默认 TEXT
  IR_DEPR_YOY VARCHAR,
  -- IA_AMORTIZE_YOY: 全部样本为空, 默认 TEXT
  IA_AMORTIZE_YOY VARCHAR,
  -- LPE_AMORTIZE_YOY: 全部样本为空, 默认 TEXT
  LPE_AMORTIZE_YOY VARCHAR,
  -- DEFER_INCOME_AMORTIZE_YOY: 全部样本为空, 默认 TEXT
  DEFER_INCOME_AMORTIZE_YOY VARCHAR,
  -- PREPAID_EXPENSE_REDUCE_YOY: 全部样本为空, 默认 TEXT
  PREPAID_EXPENSE_REDUCE_YOY VARCHAR,
  -- ACCRUED_EXPENSE_ADD_YOY: 全部样本为空, 默认 TEXT
  ACCRUED_EXPENSE_ADD_YOY VARCHAR,
  -- DISPOSAL_LONGASSET_LOSS_YOY: 全部样本为空, 默认 TEXT
  DISPOSAL_LONGASSET_LOSS_YOY VARCHAR,
  -- FA_SCRAP_LOSS_YOY: 全部样本为空, 默认 TEXT
  FA_SCRAP_LOSS_YOY VARCHAR,
  -- FAIRVALUE_CHANGE_LOSS_YOY: 全部样本为空, 默认 TEXT
  FAIRVALUE_CHANGE_LOSS_YOY VARCHAR,
  -- FINANCE_EXPENSE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_EXPENSE_YOY VARCHAR,
  -- INVEST_LOSS_YOY: 全部样本为空, 默认 TEXT
  INVEST_LOSS_YOY VARCHAR,
  -- DEFER_TAX_YOY: 全部样本为空, 默认 TEXT
  DEFER_TAX_YOY VARCHAR,
  -- DT_ASSET_REDUCE_YOY: 全部样本为空, 默认 TEXT
  DT_ASSET_REDUCE_YOY VARCHAR,
  -- DT_LIAB_ADD_YOY: 全部样本为空, 默认 TEXT
  DT_LIAB_ADD_YOY VARCHAR,
  -- PREDICT_LIAB_ADD_YOY: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_ADD_YOY VARCHAR,
  -- INVENTORY_REDUCE_YOY: 全部样本为空, 默认 TEXT
  INVENTORY_REDUCE_YOY VARCHAR,
  -- OPERATE_RECE_REDUCE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_RECE_REDUCE_YOY VARCHAR,
  -- OPERATE_PAYABLE_ADD_YOY: 全部样本为空, 默认 TEXT
  OPERATE_PAYABLE_ADD_YOY VARCHAR,
  -- OTHER_YOY: 全部样本为空, 默认 TEXT
  OTHER_YOY VARCHAR,
  -- OPERATE_NETCASH_OTHERNOTE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_OTHERNOTE_YOY VARCHAR,
  -- OPERATE_NETCASH_BALANCENOTE_YOY: 全部样本为空, 默认 TEXT
  OPERATE_NETCASH_BALANCENOTE_YOY VARCHAR,
  -- NETCASH_OPERATENOTE_YOY: 全部样本为空, 默认 TEXT
  NETCASH_OPERATENOTE_YOY VARCHAR,
  -- DEBT_TRANSFER_CAPITAL_YOY: 全部样本为空, 默认 TEXT
  DEBT_TRANSFER_CAPITAL_YOY VARCHAR,
  -- CONVERT_BOND_1YEAR_YOY: 全部样本为空, 默认 TEXT
  CONVERT_BOND_1YEAR_YOY VARCHAR,
  -- FINLEASE_OBTAIN_FA_YOY: 全部样本为空, 默认 TEXT
  FINLEASE_OBTAIN_FA_YOY VARCHAR,
  -- UNINVOLVE_INVESTFIN_OTHER_YOY: 全部样本为空, 默认 TEXT
  UNINVOLVE_INVESTFIN_OTHER_YOY VARCHAR,
  -- END_CASH_YOY: 全部样本为空, 默认 TEXT
  END_CASH_YOY VARCHAR,
  -- BEGIN_CASH_YOY: 全部样本为空, 默认 TEXT
  BEGIN_CASH_YOY VARCHAR,
  -- END_CASH_EQUIVALENTS_YOY: 全部样本为空, 默认 TEXT
  END_CASH_EQUIVALENTS_YOY VARCHAR,
  -- BEGIN_CASH_EQUIVALENTS_YOY: 全部样本为空, 默认 TEXT
  BEGIN_CASH_EQUIVALENTS_YOY VARCHAR,
  -- CCE_ADD_OTHERNOTE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_OTHERNOTE_YOY VARCHAR,
  -- CCE_ADD_BALANCENOTE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADD_BALANCENOTE_YOY VARCHAR,
  -- CCE_ADDNOTE_YOY: 全部样本为空, 默认 TEXT
  CCE_ADDNOTE_YOY VARCHAR,
  -- MINORITY_INTEREST_YOY: 全部样本为空, 默认 TEXT
  MINORITY_INTEREST_YOY VARCHAR,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_gcashflowqc_report_date ON rpt_f10_finance_gcashflowqc(REPORT_DATE);
