-- ============================================================
-- RPT_F10_DIVIDEND_3YEAR
-- dividend/近 3 年分红汇总 (yearly)
-- 样本行数: 100, 字段数: 17
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_dividend_3year (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  DIVIDEND_REPO DOUBLE,
  AVG_NET_PROFIT DOUBLE,
  RATIO DOUBLE,
  NET_PROFIT_1Y DOUBLE NOT NULL,
  NET_PROFIT_2Y DOUBLE NOT NULL,
  NET_PROFIT_3Y DOUBLE NOT NULL,
  LISTING_YEAR INTEGER,
  LISTING_DIVIDEND_NUM INTEGER,
  LISTING_PROFIT DOUBLE,
  LISTING_DIVIDEND DOUBLE,
  LISTING_A_DIVIDEND DOUBLE,
  LISTING_DIVIDEND_RATIO DOUBLE,
  DIVIDEND_REPO_HYA DOUBLE,
  RATIO_HYA DOUBLE,
  PRIMARY KEY (SECUCODE)
);
