-- ============================================================
-- RPT_MARGIN_STATISTICS_STOCKS
-- trading/融资融券 (daily)
-- 融资余额 / 融资买入 / 融券余量 / 融券卖出
-- 样本行数: 100, 字段数: 32
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_margin_statistics_stocks (
  SECUCODE VARCHAR NOT NULL,
  TRADE_DATE TIMESTAMP NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  MARGIN_BALANCE DOUBLE NOT NULL,
  MARGIN_BALANCE_RATIO DOUBLE NOT NULL,
  FIN_BALANCE BIGINT NOT NULL,
  FIN_BALANCE_RATIO DOUBLE NOT NULL,
  LOAN_BALANCE DOUBLE NOT NULL,
  LOAN_BALANCE_RATIO DOUBLE NOT NULL,
  FIN_NETBUY_AMT INTEGER NOT NULL,
  FIN_TVAL_RATIO DOUBLE NOT NULL,
  FIN_BUY_AMT INTEGER NOT NULL,
  FIN_REPAY_AMT BIGINT NOT NULL,
  LOAN_BALANCE_VOL INTEGER NOT NULL,
  LOAN_NETSELL_AMT DOUBLE NOT NULL,
  LOAN_NETSELL_VOL INTEGER NOT NULL,
  LOAN_SELL_VOL INTEGER NOT NULL,
  LOAN_REPAY_VOL INTEGER NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  CHANGE_RATE DOUBLE NOT NULL,
  FIN_DEGREE DOUBLE NOT NULL,
  LOAN_DEGREE DOUBLE NOT NULL,
  LOAN_SHARE_RATIO DOUBLE NOT NULL,
  TRADE_YEAR VARCHAR NOT NULL,
  NEW_SECUCODE VARCHAR NOT NULL,
  FIN_AMOUNT_RATIO DOUBLE NOT NULL,
  FIN_LOAN_DIFF DOUBLE NOT NULL,
  FINLOAN_DIFF_RATIO DOUBLE NOT NULL,
  CLOSE_PRICE DOUBLE NOT NULL,
  CLOSE_FORWARD_ADJPRICE DOUBLE NOT NULL,
  CLOSE_ADJPRICE DOUBLE NOT NULL,
  LOAN_TVAL_RATIO DOUBLE NOT NULL,
  PRIMARY KEY (SECUCODE, TRADE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_margin_statistics_stocks_trade_date ON rpt_margin_statistics_stocks(TRADE_DATE);
