-- ============================================================
-- RPT_PCF10_FINANCEMAINFINADATA
-- trading/最新指标 (财务主指标) (quarterly)
-- EPS / ROE / 毛利率 / 营收同比 / 归母净利同比 等数十项, 8 期历史
-- 样本行数: 100, 字段数: 43
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_pcf10_financemainfinadata (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  EPSJB DOUBLE NOT NULL,
  -- EPSKCJB: 全部样本为空, 默认 TEXT
  EPSKCJB VARCHAR,
  EPSXS DOUBLE,
  BPS DOUBLE NOT NULL,
  MGZBGJ DOUBLE NOT NULL,
  MGWFPLR DOUBLE NOT NULL,
  MGJYXJJE DOUBLE NOT NULL,
  TOTAL_OPERATEINCOME DOUBLE NOT NULL,
  TOTAL_OPERATEINCOME_LAST DOUBLE NOT NULL,
  PARENT_NETPROFIT DOUBLE NOT NULL,
  PARENT_NETPROFIT_LAST DOUBLE NOT NULL,
  KCFJCXSYJLR DOUBLE NOT NULL,
  KCFJCXSYJLR_LAST DOUBLE NOT NULL,
  ROEJQ DOUBLE NOT NULL,
  ROEJQ_LAST DOUBLE NOT NULL,
  XSMLL DOUBLE,
  XSMLL_LAST DOUBLE,
  ZCFZL DOUBLE NOT NULL,
  ZCFZL_LAST DOUBLE,
  YYZSRGDHBZC_LAST DOUBLE,
  YYZSRGDHBZC DOUBLE NOT NULL,
  NETPROFITRPHBZC DOUBLE NOT NULL,
  NETPROFITRPHBZC_LAST DOUBLE,
  KFJLRGDHBZC DOUBLE NOT NULL,
  KFJLRGDHBZC_LAST DOUBLE,
  TOTALOPERATEREVETZ DOUBLE NOT NULL,
  TOTALOPERATEREVETZ_LAST DOUBLE,
  PARENTNETPROFITTZ DOUBLE NOT NULL,
  PARENTNETPROFITTZ_LAST DOUBLE,
  KCFJCXSYJLRTZ DOUBLE NOT NULL,
  KCFJCXSYJLRTZ_LAST DOUBLE,
  TOTAL_SHARE BIGINT NOT NULL,
  FREE_SHARE BIGINT,
  FORMERNAME VARCHAR,
  EPSJB_PL DOUBLE NOT NULL,
  BPS_PL DOUBLE NOT NULL,
  MAKET_CODE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_pcf10_financemainfinadata_report_date ON rpt_pcf10_financemainfinadata(REPORT_DATE);
