-- ============================================================
-- RPT_EXECUTIVE_HOLD_DETAILS
-- events/高管持股变动 (event)
-- 替代 ak.stock_ggcg_em
-- 样本行数: 100, 字段数: 19
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_executive_hold_details (
  SECURITY_CODE VARCHAR NOT NULL,
  DERIVE_SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME VARCHAR NOT NULL,
  CHANGE_DATE TIMESTAMP NOT NULL,
  PERSON_NAME VARCHAR NOT NULL,
  CHANGE_SHARES INTEGER NOT NULL,
  AVERAGE_PRICE DOUBLE NOT NULL,
  CHANGE_AMOUNT DOUBLE NOT NULL,
  CHANGE_REASON VARCHAR NOT NULL,
  CHANGE_RATIO DOUBLE NOT NULL,
  CHANGE_AFTER_HOLDNUM INTEGER,
  HOLD_TYPE VARCHAR NOT NULL,
  DSE_PERSON_NAME VARCHAR NOT NULL,
  POSITION_NAME VARCHAR NOT NULL,
  PERSON_DSE_RELATION VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  GGEID BIGINT NOT NULL,
  BEGIN_HOLD_NUM INTEGER,
  END_HOLD_NUM INTEGER,
  PRIMARY KEY (CHANGE_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_executive_hold_details_change_date ON rpt_executive_hold_details(CHANGE_DATE);
