-- ============================================================
-- RPT_F10_FINANCE_MAINFINADATA
-- financial/主要指标 (按报告期) (quarterly)
-- v0 接口, 历史 200 期
-- 样本行数: 100, 字段数: 165
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_mainfinadata (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  EPSJB DOUBLE NOT NULL,
  -- EPSKCJB: 全部样本为空, 默认 TEXT
  EPSKCJB VARCHAR,
  EPSXS DOUBLE NOT NULL,
  BPS DOUBLE,
  MGZBGJ DOUBLE,
  MGWFPLR DOUBLE,
  MGJYXJJE DOUBLE NOT NULL,
  TOTALOPERATEREVE DOUBLE NOT NULL,
  MLR DOUBLE,
  PARENTNETPROFIT DOUBLE NOT NULL,
  KCFJCXSYJLR DOUBLE NOT NULL,
  TOTALOPERATEREVETZ DOUBLE NOT NULL,
  PARENTNETPROFITTZ DOUBLE NOT NULL,
  KCFJCXSYJLRTZ DOUBLE NOT NULL,
  YYZSRGDHBZC DOUBLE NOT NULL,
  NETPROFITRPHBZC DOUBLE NOT NULL,
  KFJLRGDHBZC DOUBLE NOT NULL,
  ROEJQ DOUBLE NOT NULL,
  -- ROEKCJQ: 全部样本为空, 默认 TEXT
  ROEKCJQ VARCHAR,
  ZZCJLL DOUBLE,
  XSJLL DOUBLE NOT NULL,
  XSMLL DOUBLE,
  YSZKYYSR DOUBLE,
  XSJXLYYSR DOUBLE,
  JYXJLYYSR DOUBLE NOT NULL,
  TAXRATE DOUBLE,
  LD DOUBLE,
  SD DOUBLE,
  XJLLB DOUBLE,
  ZCFZL DOUBLE,
  QYCS DOUBLE,
  CQBL DOUBLE,
  ZZCZZTS DOUBLE,
  CHZZTS DOUBLE,
  YSZKZZTS DOUBLE,
  TOAZZL DOUBLE,
  CHZZL DOUBLE,
  YSZKZZL DOUBLE,
  -- TOTALDEPOSITS: 全部样本为空, 默认 TEXT
  TOTALDEPOSITS VARCHAR,
  -- GROSSLOANS: 全部样本为空, 默认 TEXT
  GROSSLOANS VARCHAR,
  -- LTDRR: 全部样本为空, 默认 TEXT
  LTDRR VARCHAR,
  -- NEWCAPITALADER: 全部样本为空, 默认 TEXT
  NEWCAPITALADER VARCHAR,
  -- HXYJBCZL: 全部样本为空, 默认 TEXT
  HXYJBCZL VARCHAR,
  -- NONPERLOAN: 全部样本为空, 默认 TEXT
  NONPERLOAN VARCHAR,
  -- BLDKBBL: 全部样本为空, 默认 TEXT
  BLDKBBL VARCHAR,
  -- NZBJE: 全部样本为空, 默认 TEXT
  NZBJE VARCHAR,
  -- TOTAL_ROI: 全部样本为空, 默认 TEXT
  TOTAL_ROI VARCHAR,
  -- NET_ROI: 全部样本为空, 默认 TEXT
  NET_ROI VARCHAR,
  -- EARNED_PREMIUM: 全部样本为空, 默认 TEXT
  EARNED_PREMIUM VARCHAR,
  -- COMPENSATE_EXPENSE: 全部样本为空, 默认 TEXT
  COMPENSATE_EXPENSE VARCHAR,
  -- SURRENDER_RATE_LIFE: 全部样本为空, 默认 TEXT
  SURRENDER_RATE_LIFE VARCHAR,
  -- SOLVENCY_AR: 全部样本为空, 默认 TEXT
  SOLVENCY_AR VARCHAR,
  -- JZB: 全部样本为空, 默认 TEXT
  JZB VARCHAR,
  -- JZC: 全部样本为空, 默认 TEXT
  JZC VARCHAR,
  -- JZBJZC: 全部样本为空, 默认 TEXT
  JZBJZC VARCHAR,
  -- ZYGPGMJZC: 全部样本为空, 默认 TEXT
  ZYGPGMJZC VARCHAR,
  -- ZYGDSYLZQJZB: 全部样本为空, 默认 TEXT
  ZYGDSYLZQJZB VARCHAR,
  -- YYFXZB: 全部样本为空, 默认 TEXT
  YYFXZB VARCHAR,
  -- JJYWFXZB: 全部样本为空, 默认 TEXT
  JJYWFXZB VARCHAR,
  -- ZQZYYWFXZB: 全部样本为空, 默认 TEXT
  ZQZYYWFXZB VARCHAR,
  -- ZQCXYWFXZB: 全部样本为空, 默认 TEXT
  ZQCXYWFXZB VARCHAR,
  -- RZRQYWFXZB: 全部样本为空, 默认 TEXT
  RZRQYWFXZB VARCHAR,
  EPSJBTZ DOUBLE NOT NULL,
  BPSTZ DOUBLE,
  MGZBGJTZ DOUBLE,
  MGWFPLRTZ DOUBLE,
  MGJYXJJETZ DOUBLE,
  ROEJQTZ DOUBLE,
  ZZCJLLTZ DOUBLE,
  ZCFZLTZ DOUBLE,
  REPORT_YEAR VARCHAR NOT NULL,
  ROIC DOUBLE,
  ROICTZ DOUBLE,
  -- NBV_LIFE: 全部样本为空, 默认 TEXT
  NBV_LIFE VARCHAR,
  -- NBV_RATE: 全部样本为空, 默认 TEXT
  NBV_RATE VARCHAR,
  -- NHJZ_CURRENT_AMT: 全部样本为空, 默认 TEXT
  NHJZ_CURRENT_AMT VARCHAR,
  TOTAL_ASSETS_PK DOUBLE,
  OPERATE_INCOME_PK DOUBLE NOT NULL,
  OPERATE_PROFIT_PK DOUBLE NOT NULL,
  NETCASH_OPERATE_PK DOUBLE NOT NULL,
  NETCASH_INVEST_PK DOUBLE NOT NULL,
  NETCASH_FINANCE_PK DOUBLE,
  SALE_ER_PK DOUBLE NOT NULL,
  RE_RATIO_PK DOUBLE,
  OI_YOYRATIO_PK DOUBLE NOT NULL,
  TA_YOYRATIO_PK DOUBLE,
  EQUITY_YOYRATIO_PK DOUBLE,
  TOTAL_EQUITY_PK DOUBLE,
  TOTAL_SHARE BIGINT NOT NULL,
  A_FREE_SHARE BIGINT NOT NULL,
  B_FREE_SHARE INTEGER,
  DJD_TOI_YOY DOUBLE NOT NULL,
  DJD_DPNP_YOY DOUBLE NOT NULL,
  DJD_DEDUCTDPNP_YOY DOUBLE NOT NULL,
  DJD_TOI_QOQ DOUBLE NOT NULL,
  DJD_DPNP_QOQ DOUBLE NOT NULL,
  DJD_DEDUCTDPNP_QOQ DOUBLE NOT NULL,
  XSMLL_TB DOUBLE,
  PER_TOI DOUBLE NOT NULL,
  PER_OI DOUBLE NOT NULL,
  PER_EBIT DOUBLE,
  -- STAFF_NUM: 全部样本为空, 默认 TEXT
  STAFF_NUM VARCHAR,
  -- AVG_TOI: 全部样本为空, 默认 TEXT
  AVG_TOI VARCHAR,
  -- AVG_NET_PROFIT: 全部样本为空, 默认 TEXT
  AVG_NET_PROFIT VARCHAR,
  PREPAID_ACCOUNTS_RATIO DOUBLE,
  ACCOUNTS_PAYABLE_TR DOUBLE,
  FIXED_ASSET_TR DOUBLE NOT NULL,
  CURRENT_ASSET_TR DOUBLE,
  PREPAID_ACCOUNTS_TDAYS DOUBLE,
  INVENTORY_TR_YOY DOUBLE,
  PAYABLE_TDAYS DOUBLE,
  OPERATE_CYCLE DOUBLE,
  GUARD_SPEED_RATIO DOUBLE,
  CASH_RATIO DOUBLE,
  -- INTEREST_COVERAGE_RATIO: 全部样本为空, 默认 TEXT
  INTEREST_COVERAGE_RATIO VARCHAR,
  CA_TA DOUBLE,
  NCA_TA DOUBLE,
  LIQUIDATION_RATIO DOUBLE,
  INTEREST_DEBT_RATIO DOUBLE,
  FC_LIABILITIES DOUBLE,
  FCFF_FORWARD DOUBLE NOT NULL,
  FCFF_BACK DOUBLE,
  SS_OI DOUBLE,
  SS_TA DOUBLE,
  NCO_OP DOUBLE NOT NULL,
  NCO_NETPROFIT DOUBLE,
  NCO_FIXED DOUBLE,
  -- FIRST_ADEQUACY_RATIO: 全部样本为空, 默认 TEXT
  FIRST_ADEQUACY_RATIO VARCHAR,
  -- NET_INTEREST_SPREAD: 全部样本为空, 默认 TEXT
  NET_INTEREST_SPREAD VARCHAR,
  -- NET_INTEREST_MARGIN: 全部样本为空, 默认 TEXT
  NET_INTEREST_MARGIN VARCHAR,
  -- LOAN_ADVANCES: 全部样本为空, 默认 TEXT
  LOAN_ADVANCES VARCHAR,
  -- NON_PERFORMING_LOAN: 全部样本为空, 默认 TEXT
  NON_PERFORMING_LOAN VARCHAR,
  -- OVERDUE_LOANS: 全部样本为空, 默认 TEXT
  OVERDUE_LOANS VARCHAR,
  -- LOAN_PROVISION_RATIO: 全部样本为空, 默认 TEXT
  LOAN_PROVISION_RATIO VARCHAR,
  -- REVENUE_RATIO: 全部样本为空, 默认 TEXT
  REVENUE_RATIO VARCHAR,
  LIABILITY DOUBLE,
  -- CAPITAL_PROVISIONS_SUM: 全部样本为空, 默认 TEXT
  CAPITAL_PROVISIONS_SUM VARCHAR,
  -- RISK_COVERAGE: 全部样本为空, 默认 TEXT
  RISK_COVERAGE VARCHAR,
  -- CAPITAL_LEVERAGE_RATIO: 全部样本为空, 默认 TEXT
  CAPITAL_LEVERAGE_RATIO VARCHAR,
  -- LIQUIDITY_COVERAGE_RATIO: 全部样本为空, 默认 TEXT
  LIQUIDITY_COVERAGE_RATIO VARCHAR,
  -- NET_FUNDING_RATIO: 全部样本为空, 默认 TEXT
  NET_FUNDING_RATIO VARCHAR,
  -- NET_CAPITAL_LIABILITIES: 全部样本为空, 默认 TEXT
  NET_CAPITAL_LIABILITIES VARCHAR,
  -- NET_ASSETS_LIABILITIES: 全部样本为空, 默认 TEXT
  NET_ASSETS_LIABILITIES VARCHAR,
  -- PROPRIETARY_CAPITAL: 全部样本为空, 默认 TEXT
  PROPRIETARY_CAPITAL VARCHAR,
  IS_BZ VARCHAR NOT NULL,
  -- RDPERSONNEL: 全部样本为空, 默认 TEXT
  RDPERSONNEL VARCHAR,
  -- PRATIO: 全部样本为空, 默认 TEXT
  PRATIO VARCHAR,
  RDEXPEND DOUBLE,
  -- RCAPITAL_RATIO: 全部样本为空, 默认 TEXT
  RCAPITAL_RATIO VARCHAR,
  -- RCOST_RATIO: 全部样本为空, 默认 TEXT
  RCOST_RATIO VARCHAR,
  TOTALOPER_RATIO DOUBLE,
  INTSTCOVRATE DOUBLE,
  CL_TL DOUBLE,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_mainfinadata_report_date ON rpt_f10_finance_mainfinadata(REPORT_DATE);
