-- ============================================================
-- RPT_F10_FN_MAINOP
-- business/主营构成 (行业/产品/地区) (quarterly)
-- MAINOP_TYPE: 1=行业 / 2=产品 / 3=地区
-- 样本行数: 100, 字段数: 26
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_fn_mainop (
  SECURITY_INNER_CODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECUCODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  MAINOP_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_NAME VARCHAR NOT NULL,
  ITEM_NAME VARCHAR NOT NULL,
  MAIN_BUSINESS_INCOME DOUBLE NOT NULL,
  MBI_RATIO DOUBLE,
  GROSS_RPOFIT_RATIO DOUBLE,
  ITEM_CODE VARCHAR,
  MAIN_BUSINESS_COST DOUBLE,
  MAIN_BUSINESS_RPOFIT DOUBLE,
  MBC_RATIO DOUBLE,
  MBR_RATIO DOUBLE,
  RANK INTEGER NOT NULL,
  RANKNEW INTEGER NOT NULL,
  RANK3 INTEGER NOT NULL,
  IS_NEW INTEGER NOT NULL,
  REPORT_DATE_CODE VARCHAR NOT NULL,
  TOTAL_BUSINESS_INCOME DOUBLE NOT NULL,
  TOTAL_BUSINESS_RPOFIT DOUBLE,
  TOTAL_MBI_RATIO DOUBLE,
  TOTAL_MBR_RATIO DOUBLE,
  PRIMARY KEY (SECUCODE, REPORT_DATE, MAINOP_TYPE, ITEM_NAME)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_fn_mainop_report_date ON rpt_f10_fn_mainop(REPORT_DATE);
