-- ============================================================
-- RPT_F10_FINANCE_GBALANCE
-- financial/资产负债表 (quarterly)
-- 样本行数: 100, 字段数: 319
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt_f10_finance_gbalance (
  SECUCODE VARCHAR NOT NULL,
  SECURITY_CODE VARCHAR NOT NULL,
  SECURITY_NAME_ABBR VARCHAR NOT NULL,
  ORG_CODE VARCHAR NOT NULL,
  ORG_TYPE VARCHAR NOT NULL,
  REPORT_DATE TIMESTAMP NOT NULL,
  REPORT_TYPE VARCHAR NOT NULL,
  REPORT_DATE_NAME VARCHAR NOT NULL,
  SECURITY_TYPE_CODE VARCHAR NOT NULL,
  NOTICE_DATE TIMESTAMP NOT NULL,
  UPDATE_DATE TIMESTAMP NOT NULL,
  CURRENCY VARCHAR NOT NULL,
  ACCEPT_DEPOSIT_INTERBANK DOUBLE,
  ACCOUNTS_PAYABLE DOUBLE,
  ACCOUNTS_RECE DOUBLE,
  ACCRUED_EXPENSE DOUBLE,
  ADVANCE_RECEIVABLES DOUBLE,
  -- AGENT_TRADE_SECURITY: 全部样本为空, 默认 TEXT
  AGENT_TRADE_SECURITY VARCHAR,
  -- AGENT_UNDERWRITE_SECURITY: 全部样本为空, 默认 TEXT
  AGENT_UNDERWRITE_SECURITY VARCHAR,
  -- AMORTIZE_COST_FINASSET: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_FINASSET VARCHAR,
  -- AMORTIZE_COST_FINLIAB: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_FINLIAB VARCHAR,
  -- AMORTIZE_COST_NCFINASSET: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_NCFINASSET VARCHAR,
  -- AMORTIZE_COST_NCFINLIAB: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_NCFINLIAB VARCHAR,
  -- APPOINT_FVTPL_FINASSET: 全部样本为空, 默认 TEXT
  APPOINT_FVTPL_FINASSET VARCHAR,
  -- APPOINT_FVTPL_FINLIAB: 全部样本为空, 默认 TEXT
  APPOINT_FVTPL_FINLIAB VARCHAR,
  ASSET_BALANCE INTEGER,
  ASSET_OTHER INTEGER,
  -- ASSIGN_CASH_DIVIDEND: 全部样本为空, 默认 TEXT
  ASSIGN_CASH_DIVIDEND VARCHAR,
  AVAILABLE_SALE_FINASSET INTEGER,
  -- BOND_PAYABLE: 全部样本为空, 默认 TEXT
  BOND_PAYABLE VARCHAR,
  -- BORROW_FUND: 全部样本为空, 默认 TEXT
  BORROW_FUND VARCHAR,
  BUY_RESALE_FINASSET DOUBLE,
  CAPITAL_RESERVE DOUBLE NOT NULL,
  CIP DOUBLE,
  -- CONSUMPTIVE_BIOLOGICAL_ASSET: 全部样本为空, 默认 TEXT
  CONSUMPTIVE_BIOLOGICAL_ASSET VARCHAR,
  -- CONTRACT_ASSET: 全部样本为空, 默认 TEXT
  CONTRACT_ASSET VARCHAR,
  CONTRACT_LIAB DOUBLE,
  -- CONVERT_DIFF: 全部样本为空, 默认 TEXT
  CONVERT_DIFF VARCHAR,
  CREDITOR_INVEST DOUBLE,
  CURRENT_ASSET_BALANCE DOUBLE,
  CURRENT_ASSET_OTHER DOUBLE,
  CURRENT_LIAB_BALANCE DOUBLE,
  CURRENT_LIAB_OTHER DOUBLE,
  DEFER_INCOME DOUBLE,
  -- DEFER_INCOME_1YEAR: 全部样本为空, 默认 TEXT
  DEFER_INCOME_1YEAR VARCHAR,
  DEFER_TAX_ASSET DOUBLE,
  DEFER_TAX_LIAB DOUBLE,
  -- DERIVE_FINASSET: 全部样本为空, 默认 TEXT
  DERIVE_FINASSET VARCHAR,
  -- DERIVE_FINLIAB: 全部样本为空, 默认 TEXT
  DERIVE_FINLIAB VARCHAR,
  DEVELOP_EXPENSE DOUBLE,
  -- DIV_HOLDSALE_ASSET: 全部样本为空, 默认 TEXT
  DIV_HOLDSALE_ASSET VARCHAR,
  -- DIV_HOLDSALE_LIAB: 全部样本为空, 默认 TEXT
  DIV_HOLDSALE_LIAB VARCHAR,
  DIVIDEND_PAYABLE DOUBLE,
  DIVIDEND_RECE DOUBLE,
  EQUITY_BALANCE INTEGER,
  EQUITY_OTHER INTEGER,
  -- EXPORT_REFUND_RECE: 全部样本为空, 默认 TEXT
  EXPORT_REFUND_RECE VARCHAR,
  -- FEE_COMMISSION_PAYABLE: 全部样本为空, 默认 TEXT
  FEE_COMMISSION_PAYABLE VARCHAR,
  -- FIN_FUND: 全部样本为空, 默认 TEXT
  FIN_FUND VARCHAR,
  FINANCE_RECE DOUBLE,
  FIXED_ASSET DOUBLE NOT NULL,
  FIXED_ASSET_DISPOSAL DOUBLE,
  -- FVTOCI_FINASSET: 全部样本为空, 默认 TEXT
  FVTOCI_FINASSET VARCHAR,
  -- FVTOCI_NCFINASSET: 全部样本为空, 默认 TEXT
  FVTOCI_NCFINASSET VARCHAR,
  -- FVTPL_FINASSET: 全部样本为空, 默认 TEXT
  FVTPL_FINASSET VARCHAR,
  -- FVTPL_FINLIAB: 全部样本为空, 默认 TEXT
  FVTPL_FINLIAB VARCHAR,
  GENERAL_RISK_RESERVE DOUBLE,
  -- GOODWILL: 全部样本为空, 默认 TEXT
  GOODWILL VARCHAR,
  HOLD_MATURITY_INVEST INTEGER,
  -- HOLDSALE_ASSET: 全部样本为空, 默认 TEXT
  HOLDSALE_ASSET VARCHAR,
  -- HOLDSALE_LIAB: 全部样本为空, 默认 TEXT
  HOLDSALE_LIAB VARCHAR,
  -- INSURANCE_CONTRACT_RESERVE: 全部样本为空, 默认 TEXT
  INSURANCE_CONTRACT_RESERVE VARCHAR,
  INTANGIBLE_ASSET DOUBLE NOT NULL,
  INTEREST_PAYABLE DOUBLE,
  INTEREST_RECE DOUBLE,
  -- INTERNAL_PAYABLE: 全部样本为空, 默认 TEXT
  INTERNAL_PAYABLE VARCHAR,
  -- INTERNAL_RECE: 全部样本为空, 默认 TEXT
  INTERNAL_RECE VARCHAR,
  INVENTORY DOUBLE NOT NULL,
  INVEST_REALESTATE DOUBLE,
  LEASE_LIAB DOUBLE,
  LEND_FUND DOUBLE,
  LIAB_BALANCE INTEGER,
  LIAB_EQUITY_BALANCE DOUBLE,
  -- LIAB_EQUITY_OTHER: 全部样本为空, 默认 TEXT
  LIAB_EQUITY_OTHER VARCHAR,
  LIAB_OTHER INTEGER,
  LOAN_ADVANCE DOUBLE,
  -- LOAN_PBC: 全部样本为空, 默认 TEXT
  LOAN_PBC VARCHAR,
  LONG_EQUITY_INVEST DOUBLE,
  -- LONG_LOAN: 全部样本为空, 默认 TEXT
  LONG_LOAN VARCHAR,
  LONG_PAYABLE INTEGER,
  LONG_PREPAID_EXPENSE DOUBLE NOT NULL,
  -- LONG_RECE: 全部样本为空, 默认 TEXT
  LONG_RECE VARCHAR,
  LONG_STAFFSALARY_PAYABLE INTEGER,
  MINORITY_EQUITY DOUBLE,
  MONETARYFUNDS DOUBLE NOT NULL,
  NONCURRENT_ASSET_1YEAR DOUBLE,
  NONCURRENT_ASSET_BALANCE DOUBLE,
  NONCURRENT_ASSET_OTHER INTEGER,
  NONCURRENT_LIAB_1YEAR DOUBLE,
  NONCURRENT_LIAB_BALANCE INTEGER,
  NONCURRENT_LIAB_OTHER INTEGER,
  NOTE_ACCOUNTS_PAYABLE DOUBLE NOT NULL,
  NOTE_ACCOUNTS_RECE DOUBLE,
  -- NOTE_PAYABLE: 全部样本为空, 默认 TEXT
  NOTE_PAYABLE VARCHAR,
  NOTE_RECE DOUBLE,
  -- OIL_GAS_ASSET: 全部样本为空, 默认 TEXT
  OIL_GAS_ASSET VARCHAR,
  OTHER_COMPRE_INCOME DOUBLE,
  OTHER_CREDITOR_INVEST DOUBLE,
  OTHER_CURRENT_ASSET DOUBLE,
  OTHER_CURRENT_LIAB DOUBLE,
  -- OTHER_EQUITY_INVEST: 全部样本为空, 默认 TEXT
  OTHER_EQUITY_INVEST VARCHAR,
  OTHER_EQUITY_OTHER INTEGER,
  OTHER_EQUITY_TOOL INTEGER,
  OTHER_NONCURRENT_ASSET DOUBLE,
  OTHER_NONCURRENT_FINASSET DOUBLE,
  -- OTHER_NONCURRENT_LIAB: 全部样本为空, 默认 TEXT
  OTHER_NONCURRENT_LIAB VARCHAR,
  OTHER_PAYABLE DOUBLE,
  OTHER_RECE DOUBLE,
  PARENT_EQUITY_BALANCE DOUBLE,
  PARENT_EQUITY_OTHER INTEGER,
  PERPETUAL_BOND INTEGER,
  PERPETUAL_BOND_PAYBALE INTEGER,
  -- PREDICT_CURRENT_LIAB: 全部样本为空, 默认 TEXT
  PREDICT_CURRENT_LIAB VARCHAR,
  -- PREDICT_LIAB: 全部样本为空, 默认 TEXT
  PREDICT_LIAB VARCHAR,
  PREFERRED_SHARES INTEGER,
  PREFERRED_SHARES_PAYBALE INTEGER,
  -- PREMIUM_RECE: 全部样本为空, 默认 TEXT
  PREMIUM_RECE VARCHAR,
  PREPAYMENT DOUBLE NOT NULL,
  -- PRODUCTIVE_BIOLOGY_ASSET: 全部样本为空, 默认 TEXT
  PRODUCTIVE_BIOLOGY_ASSET VARCHAR,
  PROJECT_MATERIAL DOUBLE,
  -- RC_RESERVE_RECE: 全部样本为空, 默认 TEXT
  RC_RESERVE_RECE VARCHAR,
  -- REINSURE_PAYABLE: 全部样本为空, 默认 TEXT
  REINSURE_PAYABLE VARCHAR,
  -- REINSURE_RECE: 全部样本为空, 默认 TEXT
  REINSURE_RECE VARCHAR,
  -- SELL_REPO_FINASSET: 全部样本为空, 默认 TEXT
  SELL_REPO_FINASSET VARCHAR,
  -- SETTLE_EXCESS_RESERVE: 全部样本为空, 默认 TEXT
  SETTLE_EXCESS_RESERVE VARCHAR,
  SHARE_CAPITAL INTEGER NOT NULL,
  -- SHORT_BOND_PAYABLE: 全部样本为空, 默认 TEXT
  SHORT_BOND_PAYABLE VARCHAR,
  -- SHORT_FIN_PAYABLE: 全部样本为空, 默认 TEXT
  SHORT_FIN_PAYABLE VARCHAR,
  SHORT_LOAN INTEGER,
  SPECIAL_PAYABLE INTEGER,
  -- SPECIAL_RESERVE: 全部样本为空, 默认 TEXT
  SPECIAL_RESERVE VARCHAR,
  STAFF_SALARY_PAYABLE DOUBLE,
  -- SUBSIDY_RECE: 全部样本为空, 默认 TEXT
  SUBSIDY_RECE VARCHAR,
  SURPLUS_RESERVE DOUBLE NOT NULL,
  TAX_PAYABLE DOUBLE NOT NULL,
  TOTAL_ASSETS DOUBLE NOT NULL,
  TOTAL_CURRENT_ASSETS DOUBLE NOT NULL,
  TOTAL_CURRENT_LIAB DOUBLE NOT NULL,
  TOTAL_EQUITY DOUBLE NOT NULL,
  TOTAL_LIAB_EQUITY DOUBLE NOT NULL,
  TOTAL_LIABILITIES DOUBLE NOT NULL,
  TOTAL_NONCURRENT_ASSETS DOUBLE NOT NULL,
  TOTAL_NONCURRENT_LIAB DOUBLE,
  TOTAL_OTHER_PAYABLE DOUBLE NOT NULL,
  TOTAL_OTHER_RECE DOUBLE NOT NULL,
  TOTAL_PARENT_EQUITY DOUBLE NOT NULL,
  -- TRADE_FINASSET: 全部样本为空, 默认 TEXT
  TRADE_FINASSET VARCHAR,
  TRADE_FINASSET_NOTFVTPL DOUBLE,
  -- TRADE_FINLIAB: 全部样本为空, 默认 TEXT
  TRADE_FINLIAB VARCHAR,
  -- TRADE_FINLIAB_NOTFVTPL: 全部样本为空, 默认 TEXT
  TRADE_FINLIAB_NOTFVTPL VARCHAR,
  TREASURY_SHARES DOUBLE,
  UNASSIGN_RPOFIT DOUBLE NOT NULL,
  -- UNCONFIRM_INVEST_LOSS: 全部样本为空, 默认 TEXT
  UNCONFIRM_INVEST_LOSS VARCHAR,
  USERIGHT_ASSET DOUBLE,
  ACCEPT_DEPOSIT_INTERBANK_YOY DOUBLE,
  ACCOUNTS_PAYABLE_YOY DOUBLE,
  ACCOUNTS_RECE_YOY DOUBLE,
  ACCRUED_EXPENSE_YOY DOUBLE,
  ADVANCE_RECEIVABLES_YOY DOUBLE,
  -- AGENT_TRADE_SECURITY_YOY: 全部样本为空, 默认 TEXT
  AGENT_TRADE_SECURITY_YOY VARCHAR,
  -- AGENT_UNDERWRITE_SECURITY_YOY: 全部样本为空, 默认 TEXT
  AGENT_UNDERWRITE_SECURITY_YOY VARCHAR,
  -- AMORTIZE_COST_FINASSET_YOY: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_FINASSET_YOY VARCHAR,
  -- AMORTIZE_COST_FINLIAB_YOY: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_FINLIAB_YOY VARCHAR,
  -- AMORTIZE_COST_NCFINASSET_YOY: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_NCFINASSET_YOY VARCHAR,
  -- AMORTIZE_COST_NCFINLIAB_YOY: 全部样本为空, 默认 TEXT
  AMORTIZE_COST_NCFINLIAB_YOY VARCHAR,
  -- APPOINT_FVTPL_FINASSET_YOY: 全部样本为空, 默认 TEXT
  APPOINT_FVTPL_FINASSET_YOY VARCHAR,
  -- APPOINT_FVTPL_FINLIAB_YOY: 全部样本为空, 默认 TEXT
  APPOINT_FVTPL_FINLIAB_YOY VARCHAR,
  -- ASSET_BALANCE_YOY: 全部样本为空, 默认 TEXT
  ASSET_BALANCE_YOY VARCHAR,
  -- ASSET_OTHER_YOY: 全部样本为空, 默认 TEXT
  ASSET_OTHER_YOY VARCHAR,
  -- ASSIGN_CASH_DIVIDEND_YOY: 全部样本为空, 默认 TEXT
  ASSIGN_CASH_DIVIDEND_YOY VARCHAR,
  AVAILABLE_SALE_FINASSET_YOY INTEGER,
  -- BOND_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  BOND_PAYABLE_YOY VARCHAR,
  -- BORROW_FUND_YOY: 全部样本为空, 默认 TEXT
  BORROW_FUND_YOY VARCHAR,
  BUY_RESALE_FINASSET_YOY DOUBLE,
  CAPITAL_RESERVE_YOY DOUBLE,
  CIP_YOY DOUBLE,
  -- CONSUMPTIVE_BIOLOGICAL_ASSET_YOY: 全部样本为空, 默认 TEXT
  CONSUMPTIVE_BIOLOGICAL_ASSET_YOY VARCHAR,
  -- CONTRACT_ASSET_YOY: 全部样本为空, 默认 TEXT
  CONTRACT_ASSET_YOY VARCHAR,
  CONTRACT_LIAB_YOY DOUBLE,
  -- CONVERT_DIFF_YOY: 全部样本为空, 默认 TEXT
  CONVERT_DIFF_YOY VARCHAR,
  CREDITOR_INVEST_YOY DOUBLE,
  CURRENT_ASSET_BALANCE_YOY DOUBLE,
  CURRENT_ASSET_OTHER_YOY DOUBLE,
  CURRENT_LIAB_BALANCE_YOY INTEGER,
  CURRENT_LIAB_OTHER_YOY DOUBLE,
  -- DEFER_INCOME_1YEAR_YOY: 全部样本为空, 默认 TEXT
  DEFER_INCOME_1YEAR_YOY VARCHAR,
  -- DEFER_INCOME_YOY: 全部样本为空, 默认 TEXT
  DEFER_INCOME_YOY VARCHAR,
  DEFER_TAX_ASSET_YOY DOUBLE,
  DEFER_TAX_LIAB_YOY DOUBLE,
  -- DERIVE_FINASSET_YOY: 全部样本为空, 默认 TEXT
  DERIVE_FINASSET_YOY VARCHAR,
  -- DERIVE_FINLIAB_YOY: 全部样本为空, 默认 TEXT
  DERIVE_FINLIAB_YOY VARCHAR,
  DEVELOP_EXPENSE_YOY DOUBLE,
  -- DIV_HOLDSALE_ASSET_YOY: 全部样本为空, 默认 TEXT
  DIV_HOLDSALE_ASSET_YOY VARCHAR,
  -- DIV_HOLDSALE_LIAB_YOY: 全部样本为空, 默认 TEXT
  DIV_HOLDSALE_LIAB_YOY VARCHAR,
  DIVIDEND_PAYABLE_YOY DOUBLE,
  -- DIVIDEND_RECE_YOY: 全部样本为空, 默认 TEXT
  DIVIDEND_RECE_YOY VARCHAR,
  -- EQUITY_BALANCE_YOY: 全部样本为空, 默认 TEXT
  EQUITY_BALANCE_YOY VARCHAR,
  -- EQUITY_OTHER_YOY: 全部样本为空, 默认 TEXT
  EQUITY_OTHER_YOY VARCHAR,
  -- EXPORT_REFUND_RECE_YOY: 全部样本为空, 默认 TEXT
  EXPORT_REFUND_RECE_YOY VARCHAR,
  -- FEE_COMMISSION_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  FEE_COMMISSION_PAYABLE_YOY VARCHAR,
  -- FIN_FUND_YOY: 全部样本为空, 默认 TEXT
  FIN_FUND_YOY VARCHAR,
  -- FINANCE_RECE_YOY: 全部样本为空, 默认 TEXT
  FINANCE_RECE_YOY VARCHAR,
  FIXED_ASSET_DISPOSAL_YOY DOUBLE,
  FIXED_ASSET_YOY DOUBLE,
  -- FVTOCI_FINASSET_YOY: 全部样本为空, 默认 TEXT
  FVTOCI_FINASSET_YOY VARCHAR,
  -- FVTOCI_NCFINASSET_YOY: 全部样本为空, 默认 TEXT
  FVTOCI_NCFINASSET_YOY VARCHAR,
  -- FVTPL_FINASSET_YOY: 全部样本为空, 默认 TEXT
  FVTPL_FINASSET_YOY VARCHAR,
  -- FVTPL_FINLIAB_YOY: 全部样本为空, 默认 TEXT
  FVTPL_FINLIAB_YOY VARCHAR,
  GENERAL_RISK_RESERVE_YOY DOUBLE,
  -- GOODWILL_YOY: 全部样本为空, 默认 TEXT
  GOODWILL_YOY VARCHAR,
  HOLD_MATURITY_INVEST_YOY DOUBLE,
  -- HOLDSALE_ASSET_YOY: 全部样本为空, 默认 TEXT
  HOLDSALE_ASSET_YOY VARCHAR,
  -- HOLDSALE_LIAB_YOY: 全部样本为空, 默认 TEXT
  HOLDSALE_LIAB_YOY VARCHAR,
  -- INSURANCE_CONTRACT_RESERVE_YOY: 全部样本为空, 默认 TEXT
  INSURANCE_CONTRACT_RESERVE_YOY VARCHAR,
  INTANGIBLE_ASSET_YOY DOUBLE,
  INTEREST_PAYABLE_YOY DOUBLE,
  INTEREST_RECE_YOY DOUBLE,
  -- INTERNAL_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  INTERNAL_PAYABLE_YOY VARCHAR,
  -- INTERNAL_RECE_YOY: 全部样本为空, 默认 TEXT
  INTERNAL_RECE_YOY VARCHAR,
  INVENTORY_YOY DOUBLE,
  INVEST_REALESTATE_YOY DOUBLE,
  LEASE_LIAB_YOY DOUBLE,
  LEND_FUND_YOY DOUBLE,
  -- LIAB_BALANCE_YOY: 全部样本为空, 默认 TEXT
  LIAB_BALANCE_YOY VARCHAR,
  LIAB_EQUITY_BALANCE_YOY INTEGER,
  -- LIAB_EQUITY_OTHER_YOY: 全部样本为空, 默认 TEXT
  LIAB_EQUITY_OTHER_YOY VARCHAR,
  -- LIAB_OTHER_YOY: 全部样本为空, 默认 TEXT
  LIAB_OTHER_YOY VARCHAR,
  LOAN_ADVANCE_YOY DOUBLE,
  -- LOAN_PBC_YOY: 全部样本为空, 默认 TEXT
  LOAN_PBC_YOY VARCHAR,
  LONG_EQUITY_INVEST_YOY DOUBLE,
  -- LONG_LOAN_YOY: 全部样本为空, 默认 TEXT
  LONG_LOAN_YOY VARCHAR,
  -- LONG_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  LONG_PAYABLE_YOY VARCHAR,
  LONG_PREPAID_EXPENSE_YOY DOUBLE,
  -- LONG_RECE_YOY: 全部样本为空, 默认 TEXT
  LONG_RECE_YOY VARCHAR,
  -- LONG_STAFFSALARY_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  LONG_STAFFSALARY_PAYABLE_YOY VARCHAR,
  MINORITY_EQUITY_YOY DOUBLE,
  MONETARYFUNDS_YOY DOUBLE,
  NONCURRENT_ASSET_1YEAR_YOY DOUBLE,
  NONCURRENT_ASSET_BALANCE_YOY INTEGER,
  -- NONCURRENT_ASSET_OTHER_YOY: 全部样本为空, 默认 TEXT
  NONCURRENT_ASSET_OTHER_YOY VARCHAR,
  NONCURRENT_LIAB_1YEAR_YOY DOUBLE,
  -- NONCURRENT_LIAB_BALANCE_YOY: 全部样本为空, 默认 TEXT
  NONCURRENT_LIAB_BALANCE_YOY VARCHAR,
  -- NONCURRENT_LIAB_OTHER_YOY: 全部样本为空, 默认 TEXT
  NONCURRENT_LIAB_OTHER_YOY VARCHAR,
  NOTE_ACCOUNTS_PAYABLE_YOY DOUBLE,
  NOTE_ACCOUNTS_RECE_YOY DOUBLE,
  -- NOTE_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  NOTE_PAYABLE_YOY VARCHAR,
  NOTE_RECE_YOY DOUBLE,
  -- OIL_GAS_ASSET_YOY: 全部样本为空, 默认 TEXT
  OIL_GAS_ASSET_YOY VARCHAR,
  OTHER_COMPRE_INCOME_YOY DOUBLE,
  -- OTHER_CREDITOR_INVEST_YOY: 全部样本为空, 默认 TEXT
  OTHER_CREDITOR_INVEST_YOY VARCHAR,
  OTHER_CURRENT_ASSET_YOY DOUBLE,
  OTHER_CURRENT_LIAB_YOY DOUBLE,
  -- OTHER_EQUITY_INVEST_YOY: 全部样本为空, 默认 TEXT
  OTHER_EQUITY_INVEST_YOY VARCHAR,
  -- OTHER_EQUITY_OTHER_YOY: 全部样本为空, 默认 TEXT
  OTHER_EQUITY_OTHER_YOY VARCHAR,
  -- OTHER_EQUITY_TOOL_YOY: 全部样本为空, 默认 TEXT
  OTHER_EQUITY_TOOL_YOY VARCHAR,
  OTHER_NONCURRENT_ASSET_YOY DOUBLE,
  OTHER_NONCURRENT_FINASSET_YOY DOUBLE,
  -- OTHER_NONCURRENT_LIAB_YOY: 全部样本为空, 默认 TEXT
  OTHER_NONCURRENT_LIAB_YOY VARCHAR,
  OTHER_PAYABLE_YOY DOUBLE,
  OTHER_RECE_YOY DOUBLE,
  PARENT_EQUITY_BALANCE_YOY DOUBLE,
  PARENT_EQUITY_OTHER_YOY DOUBLE,
  -- PERPETUAL_BOND_PAYBALE_YOY: 全部样本为空, 默认 TEXT
  PERPETUAL_BOND_PAYBALE_YOY VARCHAR,
  -- PERPETUAL_BOND_YOY: 全部样本为空, 默认 TEXT
  PERPETUAL_BOND_YOY VARCHAR,
  -- PREDICT_CURRENT_LIAB_YOY: 全部样本为空, 默认 TEXT
  PREDICT_CURRENT_LIAB_YOY VARCHAR,
  -- PREDICT_LIAB_YOY: 全部样本为空, 默认 TEXT
  PREDICT_LIAB_YOY VARCHAR,
  -- PREFERRED_SHARES_PAYBALE_YOY: 全部样本为空, 默认 TEXT
  PREFERRED_SHARES_PAYBALE_YOY VARCHAR,
  -- PREFERRED_SHARES_YOY: 全部样本为空, 默认 TEXT
  PREFERRED_SHARES_YOY VARCHAR,
  -- PREMIUM_RECE_YOY: 全部样本为空, 默认 TEXT
  PREMIUM_RECE_YOY VARCHAR,
  PREPAYMENT_YOY DOUBLE,
  -- PRODUCTIVE_BIOLOGY_ASSET_YOY: 全部样本为空, 默认 TEXT
  PRODUCTIVE_BIOLOGY_ASSET_YOY VARCHAR,
  PROJECT_MATERIAL_YOY DOUBLE,
  -- RC_RESERVE_RECE_YOY: 全部样本为空, 默认 TEXT
  RC_RESERVE_RECE_YOY VARCHAR,
  -- REINSURE_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  REINSURE_PAYABLE_YOY VARCHAR,
  -- REINSURE_RECE_YOY: 全部样本为空, 默认 TEXT
  REINSURE_RECE_YOY VARCHAR,
  -- SELL_REPO_FINASSET_YOY: 全部样本为空, 默认 TEXT
  SELL_REPO_FINASSET_YOY VARCHAR,
  -- SETTLE_EXCESS_RESERVE_YOY: 全部样本为空, 默认 TEXT
  SETTLE_EXCESS_RESERVE_YOY VARCHAR,
  SHARE_CAPITAL_YOY DOUBLE,
  -- SHORT_BOND_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  SHORT_BOND_PAYABLE_YOY VARCHAR,
  -- SHORT_FIN_PAYABLE_YOY: 全部样本为空, 默认 TEXT
  SHORT_FIN_PAYABLE_YOY VARCHAR,
  SHORT_LOAN_YOY DOUBLE,
  SPECIAL_PAYABLE_YOY DOUBLE,
  -- SPECIAL_RESERVE_YOY: 全部样本为空, 默认 TEXT
  SPECIAL_RESERVE_YOY VARCHAR,
  STAFF_SALARY_PAYABLE_YOY DOUBLE,
  -- SUBSIDY_RECE_YOY: 全部样本为空, 默认 TEXT
  SUBSIDY_RECE_YOY VARCHAR,
  SURPLUS_RESERVE_YOY DOUBLE,
  TAX_PAYABLE_YOY DOUBLE,
  TOTAL_ASSETS_YOY DOUBLE,
  TOTAL_CURRENT_ASSETS_YOY DOUBLE,
  TOTAL_CURRENT_LIAB_YOY DOUBLE,
  TOTAL_EQUITY_YOY DOUBLE,
  TOTAL_LIAB_EQUITY_YOY DOUBLE,
  TOTAL_LIABILITIES_YOY DOUBLE,
  TOTAL_NONCURRENT_ASSETS_YOY DOUBLE,
  TOTAL_NONCURRENT_LIAB_YOY DOUBLE,
  TOTAL_OTHER_PAYABLE_YOY DOUBLE,
  TOTAL_OTHER_RECE_YOY DOUBLE,
  TOTAL_PARENT_EQUITY_YOY DOUBLE,
  TRADE_FINASSET_NOTFVTPL_YOY DOUBLE,
  -- TRADE_FINASSET_YOY: 全部样本为空, 默认 TEXT
  TRADE_FINASSET_YOY VARCHAR,
  -- TRADE_FINLIAB_NOTFVTPL_YOY: 全部样本为空, 默认 TEXT
  TRADE_FINLIAB_NOTFVTPL_YOY VARCHAR,
  -- TRADE_FINLIAB_YOY: 全部样本为空, 默认 TEXT
  TRADE_FINLIAB_YOY VARCHAR,
  TREASURY_SHARES_YOY DOUBLE,
  UNASSIGN_RPOFIT_YOY DOUBLE,
  -- UNCONFIRM_INVEST_LOSS_YOY: 全部样本为空, 默认 TEXT
  UNCONFIRM_INVEST_LOSS_YOY VARCHAR,
  USERIGHT_ASSET_YOY DOUBLE,
  OPINION_TYPE VARCHAR,
  -- OSOPINION_TYPE: 全部样本为空, 默认 TEXT
  OSOPINION_TYPE VARCHAR,
  LISTING_STATE VARCHAR NOT NULL,
  PRIMARY KEY (SECUCODE, REPORT_DATE)
);

CREATE INDEX IF NOT EXISTS idx_rpt_f10_finance_gbalance_report_date ON rpt_f10_finance_gbalance(REPORT_DATE);
